import {
  TenantUserRole,
  TenantLeadSource,
  TenantProjectType,
  TenantCommissionSlab,
  TenantTaxConfiguration,
  TenantTemplate,
  TenantDocumentType,
  TenantESignatureProvider,
  TenantOrganization,
  TenantDepartment,
  AdminSettingsAnalytics,
} from "./types";

export const mockTenantUserRoles: TenantUserRole[] = [
  {
    id: "role_001",
    tenantId: "tenant_001",
    name: "Project Manager",
    description: "Manages construction projects and teams",
    permissions: [
      "projects.view",
      "projects.create",
      "projects.edit",
      "teams.manage",
      "reports.view",
    ],
    isActive: true,
    userCount: 8,
    isSystem: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    createdBy: "admin_001",
  },
  {
    id: "role_002",
    tenantId: "tenant_001",
    name: "Site Engineer",
    description: "On-site engineering and quality control",
    permissions: [
      "projects.view",
      "quality.check",
      "safety.report",
      "materials.track",
    ],
    isActive: true,
    userCount: 15,
    isSystem: false,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-10T14:20:00Z",
    createdBy: "admin_001",
  },
  {
    id: "role_003",
    tenantId: "tenant_001",
    name: "Safety Officer",
    description: "Ensures workplace safety and compliance",
    permissions: [
      "safety.view",
      "safety.create",
      "safety.audit",
      "incidents.report",
      "compliance.check",
    ],
    isActive: true,
    userCount: 5,
    isSystem: false,
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-12T16:45:00Z",
    createdBy: "admin_001",
  },
  // Tenant 2 - Metro Realty Group
  {
    id: "role_004",
    tenantId: "tenant_002",
    name: "Sales Manager",
    description: "Manages real estate sales operations",
    permissions: [
      "leads.view",
      "leads.create",
      "properties.view",
      "clients.manage",
      "reports.sales",
    ],
    isActive: true,
    userCount: 12,
    isSystem: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-18T09:15:00Z",
    createdBy: "admin_002",
  },
  {
    id: "role_005",
    tenantId: "tenant_002",
    name: "Property Manager",
    description: "Oversees property management and maintenance",
    permissions: [
      "properties.view",
      "properties.edit",
      "maintenance.manage",
      "tenants.manage",
    ],
    isActive: true,
    userCount: 8,
    isSystem: false,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    createdBy: "admin_002",
  },
  // Tenant 3 - Skyline Developers
  {
    id: "role_006",
    tenantId: "tenant_003",
    name: "Development Manager",
    description: "Manages development projects and planning",
    permissions: [
      "projects.view",
      "projects.create",
      "planning.manage",
      "approvals.track",
      "budgets.view",
    ],
    isActive: true,
    userCount: 6,
    isSystem: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-16T11:45:00Z",
    createdBy: "admin_003",
  },
  {
    id: "role_007",
    tenantId: "tenant_003",
    name: "Architect",
    description: "Design and architectural oversight",
    permissions: [
      "designs.view",
      "designs.create",
      "approvals.architectural",
      "planning.review",
    ],
    isActive: true,
    userCount: 4,
    isSystem: false,
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-19T16:20:00Z",
    createdBy: "admin_003",
  },
];

export const mockTenantLeadSources: TenantLeadSource[] = [
  {
    id: "lead_001",
    tenantId: "tenant_001",
    name: "Digital Marketing",
    type: "Online",
    category: "Paid",
    description: "Google Ads and social media campaigns",
    isActive: true,
    priority: 1,
    conversionRate: 12.5,
    cost: 25000,
    leadsGenerated: 145,
    createdAt: "2024-01-01T00:00:00Z",
    settings: {
      autoAssignment: true,
      followUpRequired: true,
      scoringWeight: 85,
    },
  },
  {
    id: "lead_002",
    tenantId: "tenant_001",
    name: "Referral Program",
    type: "Referral",
    category: "Organic",
    description: "Customer and partner referrals",
    isActive: true,
    priority: 2,
    conversionRate: 28.3,
    cost: 8000,
    leadsGenerated: 89,
    createdAt: "2024-01-05T00:00:00Z",
    settings: {
      autoAssignment: true,
      followUpRequired: true,
      scoringWeight: 95,
    },
  },
  {
    id: "lead_003",
    tenantId: "tenant_001",
    name: "Trade Shows",
    type: "Event",
    category: "Offline",
    description: "Construction and real estate exhibitions",
    isActive: true,
    priority: 3,
    conversionRate: 18.7,
    cost: 45000,
    leadsGenerated: 67,
    createdAt: "2024-01-08T00:00:00Z",
    settings: {
      autoAssignment: false,
      followUpRequired: true,
      scoringWeight: 75,
    },
  },
  // Tenant 2 - Metro Realty Group
  {
    id: "lead_003",
    tenantId: "tenant_002",
    name: "Property Portals",
    type: "Online",
    category: "Paid",
    description: "99acres, Magicbricks, and Housing.com listings",
    isActive: true,
    priority: 1,
    conversionRate: 8.2,
    cost: 35000,
    leadsGenerated: 98,
    createdAt: "2024-01-01T00:00:00Z",
    settings: {
      autoAssignment: true,
      followUpRequired: true,
      scoringWeight: 75,
    },
  },
  {
    id: "lead_004",
    tenantId: "tenant_002",
    name: "Broker Network",
    type: "Referral",
    category: "Partnership",
    description: "Real estate broker partnerships",
    isActive: true,
    priority: 2,
    conversionRate: 15.5,
    cost: 0,
    leadsGenerated: 67,
    createdAt: "2024-01-02T00:00:00Z",
    settings: {
      autoAssignment: false,
      followUpRequired: true,
      scoringWeight: 85,
    },
  },
  // Tenant 3 - Skyline Developers
  {
    id: "lead_005",
    tenantId: "tenant_003",
    name: "Trade Shows",
    type: "Event",
    category: "Organic",
    description: "Real estate exhibitions and trade shows",
    isActive: true,
    priority: 1,
    conversionRate: 22.1,
    cost: 50000,
    leadsGenerated: 45,
    createdAt: "2024-01-01T00:00:00Z",
    settings: {
      autoAssignment: true,
      followUpRequired: true,
      scoringWeight: 90,
    },
  },
  {
    id: "lead_006",
    tenantId: "tenant_003",
    name: "Luxury Magazines",
    type: "Print",
    category: "Paid",
    description: "Premium lifestyle and real estate magazines",
    isActive: true,
    priority: 2,
    conversionRate: 18.7,
    cost: 25000,
    leadsGenerated: 32,
    createdAt: "2024-01-03T00:00:00Z",
    settings: {
      autoAssignment: false,
      followUpRequired: true,
      scoringWeight: 80,
    },
  },
];

export const mockTenantProjectTypes: TenantProjectType[] = [
  {
    id: "proj_001",
    tenantId: "tenant_001",
    name: "Residential Tower",
    category: "Residential",
    description: "Multi-story residential apartment complexes",
    isActive: true,
    defaultDuration: 24,
    phases: [
      "Planning",
      "Foundation",
      "Structure",
      "MEP",
      "Finishing",
      "Handover",
    ],
    milestones: 10,
    approvals: ["Municipal", "Fire Safety", "Lift", "Electrical"],
    documents: ["Building Plan", "Occupancy Certificate", "NOC"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "proj_002",
    tenantId: "tenant_001",
    name: "Commercial Complex",
    category: "Commercial",
    description: "Office buildings and retail spaces",
    isActive: true,
    defaultDuration: 18,
    phases: [
      "Design",
      "Foundation",
      "Structure",
      "MEP",
      "Interior",
      "Handover",
    ],
    milestones: 8,
    approvals: ["Municipal", "Fire Safety", "Environmental"],
    documents: ["Commercial License", "Fire NOC", "Completion Certificate"],
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
];

export const mockTenantCommissionSlabs: TenantCommissionSlab[] = [
  {
    id: "comm_001",
    tenantId: "tenant_001",
    name: "Channel Partner - Premium",
    type: "Channel Partner",
    category: "Premium",
    description: "Top performing channel partners",
    slabs: [
      { from: 0, to: 10000000, rate: 2.5, type: "percentage" },
      { from: 10000000, to: 25000000, rate: 3.0, type: "percentage" },
      { from: 25000000, to: null, rate: 3.5, type: "percentage" },
    ],
    isActive: true,
    effectiveFrom: new Date("2024-01-01"),
    effectiveTo: null,
    partners: 25,
    totalCommission: 2850000,
  },
  {
    id: "comm_002",
    tenantId: "tenant_001",
    name: "Sales Team",
    type: "Employee",
    category: "Internal",
    description: "Internal sales team commission structure",
    slabs: [
      { from: 0, to: 5000000, rate: 1.0, type: "percentage" },
      { from: 5000000, to: 10000000, rate: 1.5, type: "percentage" },
      { from: 10000000, to: null, rate: 2.0, type: "percentage" },
    ],
    isActive: true,
    effectiveFrom: new Date("2024-01-01"),
    effectiveTo: null,
    partners: 12,
    totalCommission: 875000,
  },
];

export const mockTenantTaxConfiguration: TenantTaxConfiguration[] = [
  {
    id: "tax_001",
    tenantId: "tenant_001",
    name: "GST",
    type: "Goods and Services Tax",
    category: "Government Tax",
    description: "Central and State GST applicable on real estate",
    rates: [
      { type: "Under Construction", rate: 5, isActive: true },
      { type: "Ready to Move", rate: 0, isActive: true },
      { type: "Commercial", rate: 12, isActive: true },
    ],
    isActive: true,
    hsnCode: "9999",
    effectiveFrom: new Date("2017-07-01"),
    applicableTo: ["Residential", "Commercial"],
  },
  {
    id: "tax_002",
    tenantId: "tenant_001",
    name: "Stamp Duty",
    type: "State Government Charge",
    category: "Registration",
    description: "Property registration charges",
    rates: [
      { type: "Residential", rate: 5, isActive: true },
      { type: "Commercial", rate: 7, isActive: true },
    ],
    isActive: true,
    effectiveFrom: new Date("2020-01-01"),
    applicableTo: ["Residential", "Commercial"],
  },
];

export const mockTenantTemplates: TenantTemplate[] = [
  {
    id: "temp_001",
    tenantId: "tenant_001",
    name: "Welcome Email",
    type: "Email",
    category: "Customer Communication",
    description: "Welcome message for new customers",
    isActive: true,
    version: "2.1",
    content: {
      subject: "Welcome to {{company_name}}!",
      body: "Dear {{customer_name}}, welcome to our real estate family...",
      variables: ["company_name", "customer_name", "project_name"],
    },
    usage: {
      sent: 234,
      opened: 198,
      clicked: 45,
    },
    lastUsed: new Date("2024-01-20T10:30:00Z"),
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T16:20:00Z",
  },
  {
    id: "temp_002",
    tenantId: "tenant_001",
    name: "Payment Reminder",
    type: "SMS",
    category: "Payment",
    description: "Payment due reminder for customers",
    isActive: true,
    version: "1.5",
    content: {
      body: "Dear {{customer_name}}, your payment of {{amount}} is due on {{due_date}}",
      variables: ["customer_name", "amount", "due_date"],
    },
    usage: {
      sent: 156,
      opened: 156,
      clicked: 12,
    },
    lastUsed: new Date("2024-01-18T14:45:00Z"),
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-10T11:30:00Z",
  },
];

export const mockTenantOrganization: TenantOrganization = {
  id: "org_001",
  tenantId: "tenant_001",
  name: "BuildCorp Constructions",
  industry: "Construction & Real Estate",
  size: "50-200 employees",
  founded: "2018",
  headquarters: "Mumbai, India",
  structure: {
    ceo: {
      name: "Rajesh Kumar",
      position: "Chief Executive Officer",
      department: "Executive",
      reports: 4,
      email: "rajesh.kumar@buildcorp.com",
      phone: "+91-98765-43210",
    },
    departments: [
      {
        id: "dept_001",
        tenantId: "tenant_001",
        organizationId: "org_001",
        name: "Construction",
        head: {
          name: "Suresh Patel",
          position: "Construction Director",
          email: "suresh.patel@buildcorp.com",
          phone: "+91-98765-43211",
        },
        employees: 45,
        budget: 8500000,
        performance: 92,
        color: "#2563eb",
        units: [
          { name: "Civil Engineering", head: "Amit Sharma", employees: 18 },
          {
            name: "Structural Engineering",
            head: "Priya Singh",
            employees: 15,
          },
          { name: "MEP", head: "Vikram Reddy", employees: 12 },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-15T00:00:00Z",
      },
      {
        id: "dept_002",
        tenantId: "tenant_001",
        organizationId: "org_001",
        name: "Sales & Marketing",
        head: {
          name: "Neha Agarwal",
          position: "Sales Director",
          email: "neha.agarwal@buildcorp.com",
          phone: "+91-98765-43212",
        },
        employees: 28,
        budget: 4200000,
        performance: 88,
        color: "#059669",
        units: [
          { name: "Direct Sales", head: "Rohit Kumar", employees: 15 },
          { name: "Channel Partners", head: "Deepika Rao", employees: 13 },
        ],
        createdAt: "2024-01-01T00:00:00Z",
        updatedAt: "2024-01-12T00:00:00Z",
      },
    ],
    totalEmployees: 85,
    locations: ["Mumbai", "Pune", "Nashik"],
  },
  settings: {
    workingHours: {
      start: "09:00",
      end: "18:00",
      timezone: "Asia/Kolkata",
    },
    holidays: ["2024-01-26", "2024-03-14", "2024-08-15", "2024-10-02"],
    fiscalYearStart: "April",
  },
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2024-01-20T00:00:00Z",
};

export const mockAdminAnalytics: AdminSettingsAnalytics = {
  tenantId: "tenant_001",
  period: "current_month",
  totalUsers: 85,
  activeRoles: 12,
  leadSources: 8,
  templates: 15,
  documentsGenerated: 234,
  configurationChanges: 47,
  lastActivity: "2024-01-25T16:30:00Z",
};

// Helper function to filter data by tenant
export const getTenantData = <T extends { tenantId: string }>(
  data: T[],
  tenantId: string,
): T[] => {
  return data.filter((item) => item.tenantId === tenantId);
};

// Helper function to create new tenant-scoped item
export const createTenantItem = <T>(
  baseItem: Omit<T, "tenantId">,
  tenantId: string,
): T => {
  return {
    ...baseItem,
    tenantId,
  } as T;
};
