import {
  PossessionUnit,
  InspectionChecklistItem,
  HandoverChecklistItem,
  DefectReport,
  MaintenanceSchedule,
  WarrantyItem,
  PossessionAnalytics,
} from "./types";

export const mockPossessionUnits: PossessionUnit[] = [
  {
    id: "unit-001",
    projectId: "proj-skyline",
    projectName: "Skyline Towers",
    unitNumber: "A-1201",
    unitType: "3BHK",
    floor: 12,
    area: 1450,
    facing: "East",
    customer: {
      id: "cust-001",
      name: "Rajesh Kumar",
      email: "rajesh.kumar@email.com",
      phone: "+91 98765 43210",
      secondaryPhone: "+91 87654 32109",
      address: "Sector 14, Gurgaon, Haryana",
      panNumber: "ABCDE1234F",
      aadharNumber: "1234 5678 9012",
      registrationDate: "2023-03-15",
      totalAmount: 8500000,
      paidAmount: 8000000,
      balanceAmount: 500000,
    },
    possession: {
      scheduledDate: "2024-02-15",
      actualDate: "2024-02-18",
      possessionLetter: {
        generated: true,
        sentDate: "2024-01-15",
        acknowledgedDate: "2024-01-20",
        documentUrl: "/documents/possession-letter-A1201.pdf",
      },
      registrationCompleted: true,
      registrationDate: "2024-02-10",
      loanApproved: true,
      loanDetails: {
        bankName: "HDFC Bank",
        loanAmount: 6000000,
        approvalDate: "2024-01-30",
      },
    },
    finalDues: {
      status: "cleared",
      totalDues: 245000,
      breakdown: [
        {
          id: "due-001",
          category: "Maintenance",
          description: "Advance maintenance charges (12 months)",
          amount: 120000,
          dueDate: "2024-02-10",
          status: "paid",
          paidDate: "2024-02-08",
          paymentMode: "online",
          receiptNumber: "REC001",
        },
        {
          id: "due-002",
          category: "Utilities",
          description: "Electricity connection charges",
          amount: 25000,
          dueDate: "2024-02-10",
          status: "paid",
          paidDate: "2024-02-08",
          paymentMode: "online",
          receiptNumber: "REC002",
        },
        {
          id: "due-003",
          category: "Documentation",
          description: "Registration and documentation charges",
          amount: 85000,
          dueDate: "2024-02-10",
          status: "paid",
          paidDate: "2024-02-09",
          paymentMode: "cheque",
          receiptNumber: "REC003",
        },
        {
          id: "due-004",
          category: "Club Membership",
          description: "Lifetime club membership",
          amount: 15000,
          dueDate: "2024-02-10",
          status: "paid",
          paidDate: "2024-02-09",
          paymentMode: "online",
          receiptNumber: "REC004",
        },
      ],
      paymentHistory: [
        {
          id: "pay-001",
          amount: 245000,
          paymentDate: "2024-02-09",
          paymentMode: "online",
          transactionId: "TXN123456789",
          receiptNumber: "REC-FINAL-001",
          collectedBy: "Finance Team",
        },
      ],
      clearanceDate: "2024-02-09",
      certificateGenerated: true,
      certificateUrl: "/documents/clearance-certificate-A1201.pdf",
    },
    inspection: {
      status: "completed",
      scheduledDate: "2024-02-12",
      actualDate: "2024-02-12",
      inspector: "Suresh Patel",
      checklist: [
        {
          id: "check-001",
          category: "Civil Work",
          item: "Wall finishing and paint quality",
          status: "ok",
          photoRequired: true,
          photoUrls: ["/photos/wall-finish-A1201-1.jpg"],
          priority: "medium",
        },
        {
          id: "check-002",
          category: "Electrical",
          item: "All electrical points working",
          status: "ok",
          photoRequired: false,
          priority: "high",
        },
        {
          id: "check-003",
          category: "Plumbing",
          item: "Water pressure and drainage",
          status: "defect",
          remarks: "Low water pressure in master bedroom",
          photoRequired: true,
          photoUrls: ["/photos/plumbing-issue-A1201.jpg"],
          priority: "high",
        },
        {
          id: "check-004",
          category: "Flooring",
          item: "Tiles and marble finishing",
          status: "minor_issue",
          remarks: "Minor scratches on living room tiles",
          photoRequired: true,
          photoUrls: ["/photos/flooring-A1201.jpg"],
          priority: "low",
        },
        {
          id: "check-005",
          category: "Doors & Windows",
          item: "All doors and windows functioning",
          status: "ok",
          photoRequired: false,
          priority: "medium",
        },
      ],
      customerPresent: true,
      customerSignature: "/signatures/rajesh-kumar-inspection.png",
      inspectorNotes:
        "Overall unit is in good condition. Minor plumbing issue needs attention before handover.",
      overallRating: 8.5,
      photosUploaded: [
        "/photos/unit-overview-A1201.jpg",
        "/photos/living-room-A1201.jpg",
        "/photos/kitchen-A1201.jpg",
      ],
      reportGenerated: true,
      reportUrl: "/reports/inspection-report-A1201.pdf",
    },
    handover: {
      status: "completed",
      scheduledDate: "2024-02-18",
      actualDate: "2024-02-18",
      documentsGenerated: true,
      documentsHandedOver: true,
      keysHandedOver: true,
      welcomeKitGiven: true,
      handoverChecklist: [
        {
          id: "hand-001",
          item: "Original possession letter",
          category: "Documents",
          completed: true,
          handedOverBy: "Sales Team",
          receivedBy: "Rajesh Kumar",
          timestamp: "2024-02-18T10:30:00Z",
        },
        {
          id: "hand-002",
          item: "All unit keys (3 sets)",
          category: "Keys",
          completed: true,
          handedOverBy: "Security Team",
          receivedBy: "Rajesh Kumar",
          timestamp: "2024-02-18T10:35:00Z",
        },
        {
          id: "hand-003",
          item: "Welcome kit with amenities guide",
          category: "Welcome Kit",
          completed: true,
          handedOverBy: "Customer Relations",
          receivedBy: "Rajesh Kumar",
          timestamp: "2024-02-18T10:40:00Z",
        },
        {
          id: "hand-004",
          item: "Warranty booklet and manuals",
          category: "Documents",
          completed: true,
          handedOverBy: "Sales Team",
          receivedBy: "Rajesh Kumar",
          timestamp: "2024-02-18T10:45:00Z",
        },
      ],
      customerFeedback: {
        overallSatisfaction: 9,
        constructionQuality: 8,
        timelyDelivery: 9,
        customerService: 10,
        documentation: 9,
        comments:
          "Excellent service and quality. Very happy with the possession process.",
        recommendToFriends: true,
        submittedAt: "2024-02-18T11:00:00Z",
      },
      handoverCertificate: {
        generated: true,
        signedByCustomer: true,
        signedByCompany: true,
        documentUrl: "/documents/handover-certificate-A1201.pdf",
      },
      communicationSent: {
        welcomeEmail: true,
        welcomeSMS: true,
        handoverConfirmation: true,
      },
    },
    defectLiability: {
      period: 12,
      startDate: "2024-02-18",
      endDate: "2025-02-18",
      defectReports: [
        {
          id: "defect-001",
          reportedDate: "2024-03-15",
          category: "Plumbing",
          description: "Water leakage in master bathroom",
          severity: "high",
          status: "resolved",
          reportedBy: "Rajesh Kumar",
          assignedTo: "Maintenance Team A",
          targetResolutionDate: "2024-03-20",
          actualResolutionDate: "2024-03-18",
          resolutionDetails: "Replaced faulty pipe connection. Issue resolved.",
          customerSatisfied: true,
          photosUrls: ["/photos/defect-plumbing-A1201.jpg"],
          cost: 3500,
        },
      ],
      maintenanceSchedule: [
        {
          id: "maint-001",
          type: "routine",
          description: "AC servicing and filter cleaning",
          scheduledDate: "2024-06-18",
          frequency: "quarterly",
          assignedTeam: "AC Maintenance Team",
          status: "scheduled",
          cost: 2500,
        },
        {
          id: "maint-002",
          type: "preventive",
          description: "Elevator maintenance check",
          scheduledDate: "2024-03-18",
          completedDate: "2024-03-18",
          frequency: "monthly",
          assignedTeam: "Elevator Team",
          status: "completed",
          cost: 0,
          notes: "All systems functioning normally",
        },
      ],
      warrantyItems: [
        {
          id: "warranty-001",
          itemName: "Modular Kitchen",
          category: "Kitchen",
          warrantyPeriod: 24,
          startDate: "2024-02-18",
          endDate: "2026-02-18",
          vendor: "Godrej Interio",
          warrantyTerms: "Manufacturing defects and fittings",
          status: "active",
          claimHistory: [],
        },
        {
          id: "warranty-002",
          itemName: "Bathroom Fittings",
          category: "Plumbing",
          warrantyPeriod: 12,
          startDate: "2024-02-18",
          endDate: "2025-02-18",
          vendor: "Kohler",
          warrantyTerms: "Manufacturing defects only",
          status: "active",
          claimHistory: [],
        },
      ],
      contactPerson: {
        name: "Priya Sharma",
        phone: "+91 98765 11111",
        email: "maintenance@skylinetowers.com",
        designation: "Maintenance Manager",
      },
    },
    status: "possession_completed",
    createdAt: "2023-03-15T09:00:00Z",
    updatedAt: "2024-02-18T11:00:00Z",
  },
  {
    id: "unit-002",
    projectId: "proj-greenvalley",
    projectName: "Green Valley Homes",
    unitNumber: "B-504",
    unitType: "2BHK",
    floor: 5,
    area: 1080,
    facing: "North",
    customer: {
      id: "cust-002",
      name: "Priya Mehta",
      email: "priya.mehta@email.com",
      phone: "+91 87654 32109",
      address: "Bandra West, Mumbai, Maharashtra",
      panNumber: "FGHIJ5678K",
      aadharNumber: "9876 5432 1098",
      registrationDate: "2023-06-20",
      totalAmount: 5200000,
      paidAmount: 4800000,
      balanceAmount: 400000,
    },
    possession: {
      scheduledDate: "2024-03-30",
      possessionLetter: {
        generated: true,
        sentDate: "2024-02-28",
        acknowledgedDate: "2024-03-05",
        documentUrl: "/documents/possession-letter-B504.pdf",
      },
      registrationCompleted: false,
      loanApproved: true,
      loanDetails: {
        bankName: "SBI",
        loanAmount: 3500000,
        approvalDate: "2024-02-15",
      },
    },
    finalDues: {
      status: "pending",
      totalDues: 185000,
      breakdown: [
        {
          id: "due-005",
          category: "Maintenance",
          description: "Advance maintenance charges (12 months)",
          amount: 90000,
          dueDate: "2024-03-25",
          status: "pending",
        },
        {
          id: "due-006",
          category: "Utilities",
          description: "Electricity and water connection",
          amount: 35000,
          dueDate: "2024-03-25",
          status: "pending",
        },
        {
          id: "due-007",
          category: "Documentation",
          description: "Registration charges",
          amount: 60000,
          dueDate: "2024-03-25",
          status: "pending",
        },
      ],
      paymentHistory: [],
      certificateGenerated: false,
    },
    inspection: {
      status: "in_progress",
      scheduledDate: "2024-03-20",
      inspector: "Amit Singh",
      checklist: [
        {
          id: "check-006",
          category: "Civil Work",
          item: "Wall finishing and paint quality",
          status: "ok",
          photoRequired: true,
          priority: "medium",
        },
        {
          id: "check-007",
          category: "Electrical",
          item: "All electrical points working",
          status: "ok",
          photoRequired: false,
          priority: "high",
        },
      ],
      customerPresent: false,
      inspectorNotes:
        "Inspection in progress. Customer to be present for final verification.",
      overallRating: 0,
      photosUploaded: [],
      reportGenerated: false,
    },
    handover: {
      status: "pending",
      scheduledDate: "2024-03-30",
      documentsGenerated: false,
      documentsHandedOver: false,
      keysHandedOver: false,
      welcomeKitGiven: false,
      handoverChecklist: [],
      handoverCertificate: {
        generated: false,
        signedByCustomer: false,
        signedByCompany: false,
      },
      communicationSent: {
        welcomeEmail: false,
        welcomeSMS: false,
        handoverConfirmation: false,
      },
    },
    defectLiability: {
      period: 12,
      startDate: "",
      endDate: "",
      defectReports: [],
      maintenanceSchedule: [],
      warrantyItems: [],
      contactPerson: {
        name: "Ravi Kumar",
        phone: "+91 98765 22222",
        email: "maintenance@greenvalley.com",
        designation: "Maintenance Supervisor",
      },
    },
    status: "inspection_scheduled",
    createdAt: "2023-06-20T09:00:00Z",
    updatedAt: "2024-03-15T10:30:00Z",
  },
  {
    id: "unit-003",
    projectId: "proj-metro",
    projectName: "Metro Plaza",
    unitNumber: "C-802",
    unitType: "4BHK",
    floor: 8,
    area: 1850,
    facing: "South-West",
    customer: {
      id: "cust-003",
      name: "Arjun Reddy",
      email: "arjun.reddy@email.com",
      phone: "+91 76543 21098",
      address: "Electronic City, Bangalore, Karnataka",
      panNumber: "KLMNO9012P",
      aadharNumber: "5432 1098 7654",
      registrationDate: "2023-09-10",
      totalAmount: 12500000,
      paidAmount: 11000000,
      balanceAmount: 1500000,
    },
    possession: {
      scheduledDate: "2024-05-15",
      possessionLetter: {
        generated: false,
      },
      registrationCompleted: false,
      loanApproved: false,
    },
    finalDues: {
      status: "calculated",
      totalDues: 325000,
      breakdown: [
        {
          id: "due-008",
          category: "Maintenance",
          description: "Advance maintenance charges (12 months)",
          amount: 180000,
          dueDate: "2024-05-10",
          status: "pending",
        },
        {
          id: "due-009",
          category: "Utilities",
          description: "Electricity, water, and gas connections",
          amount: 45000,
          dueDate: "2024-05-10",
          status: "pending",
        },
        {
          id: "due-010",
          category: "Documentation",
          description: "Registration and legal charges",
          amount: 85000,
          dueDate: "2024-05-10",
          status: "pending",
        },
        {
          id: "due-011",
          category: "Amenities",
          description: "Club membership and amenities access",
          amount: 15000,
          dueDate: "2024-05-10",
          status: "pending",
        },
      ],
      paymentHistory: [],
      certificateGenerated: false,
    },
    inspection: {
      status: "not_started",
      scheduledDate: "2024-05-05",
      inspector: "TBD",
      checklist: [],
      customerPresent: false,
      inspectorNotes: "",
      overallRating: 0,
      photosUploaded: [],
      reportGenerated: false,
    },
    handover: {
      status: "pending",
      scheduledDate: "2024-05-15",
      documentsGenerated: false,
      documentsHandedOver: false,
      keysHandedOver: false,
      welcomeKitGiven: false,
      handoverChecklist: [],
      handoverCertificate: {
        generated: false,
        signedByCustomer: false,
        signedByCompany: false,
      },
      communicationSent: {
        welcomeEmail: false,
        welcomeSMS: false,
        handoverConfirmation: false,
      },
    },
    defectLiability: {
      period: 12,
      startDate: "",
      endDate: "",
      defectReports: [],
      maintenanceSchedule: [],
      warrantyItems: [],
      contactPerson: {
        name: "Deepak Verma",
        phone: "+91 98765 33333",
        email: "maintenance@metroplaza.com",
        designation: "Facility Manager",
      },
    },
    status: "dues_clearance",
    createdAt: "2023-09-10T09:00:00Z",
    updatedAt: "2024-03-20T15:45:00Z",
  },
];

export const mockInspectionChecklist: InspectionChecklistItem[] = [
  {
    id: "std-001",
    category: "Civil Work",
    item: "Wall finishing and paint quality",
    status: "ok",
    photoRequired: true,
    priority: "medium",
  },
  {
    id: "std-002",
    category: "Civil Work",
    item: "Ceiling finishing and alignment",
    status: "ok",
    photoRequired: true,
    priority: "medium",
  },
  {
    id: "std-003",
    category: "Electrical",
    item: "All electrical points working",
    status: "ok",
    photoRequired: false,
    priority: "high",
  },
  {
    id: "std-004",
    category: "Electrical",
    item: "Main electrical panel labeling",
    status: "ok",
    photoRequired: false,
    priority: "medium",
  },
  {
    id: "std-005",
    category: "Plumbing",
    item: "Water pressure in all taps",
    status: "ok",
    photoRequired: false,
    priority: "high",
  },
  {
    id: "std-006",
    category: "Plumbing",
    item: "Drainage and sewage connections",
    status: "ok",
    photoRequired: false,
    priority: "high",
  },
  {
    id: "std-007",
    category: "Flooring",
    item: "Tiles and marble finishing quality",
    status: "ok",
    photoRequired: true,
    priority: "medium",
  },
  {
    id: "std-008",
    category: "Doors & Windows",
    item: "All doors opening and closing properly",
    status: "ok",
    photoRequired: false,
    priority: "medium",
  },
  {
    id: "std-009",
    category: "Doors & Windows",
    item: "Window locks and handles functioning",
    status: "ok",
    photoRequired: false,
    priority: "medium",
  },
  {
    id: "std-010",
    category: "Kitchen",
    item: "Modular kitchen installation",
    status: "ok",
    photoRequired: true,
    priority: "high",
  },
  {
    id: "std-011",
    category: "Bathroom",
    item: "Bathroom fittings and fixtures",
    status: "ok",
    photoRequired: true,
    priority: "high",
  },
  {
    id: "std-012",
    category: "Safety",
    item: "Fire safety equipment installed",
    status: "ok",
    photoRequired: false,
    priority: "critical",
  },
];

export const mockHandoverChecklist: HandoverChecklistItem[] = [
  {
    id: "hand-std-001",
    item: "Original possession letter",
    category: "Legal Documents",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-002",
    item: "Sale deed copy",
    category: "Legal Documents",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-003",
    item: "Occupancy certificate",
    category: "Legal Documents",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-004",
    item: "All unit keys (3 sets)",
    category: "Keys & Access",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-005",
    item: "Common area access cards",
    category: "Keys & Access",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-006",
    item: "Welcome kit with amenities guide",
    category: "Welcome Kit",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-007",
    item: "Warranty booklet and user manuals",
    category: "Documentation",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-008",
    item: "Maintenance contact details",
    category: "Information",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-009",
    item: "Society rules and regulations",
    category: "Information",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
  {
    id: "hand-std-010",
    item: "Utility connection details",
    category: "Information",
    completed: false,
    handedOverBy: "",
    receivedBy: "",
  },
];

export const mockAnalytics: PossessionAnalytics = {
  totalUnits: 156,
  unitsInProcess: 45,
  unitsCompleted: 111,
  averageCompletionTime: 28, // days
  customerSatisfactionAvg: 8.7,
  pendingDefects: 12,
  onTimeDeliveryRate: 87.5, // percentage
  revenueCollected: 850000000, // in rupees
  pendingDues: 12500000, // in rupees
};
