import {
  OrgLocation,
  OrgUnit,
  Employee,
  ReportingLine,
  OrgStructureAnalytics,
  OrgChangeRequest,
} from "./types";

// Organization Locations
export const orgLocations: OrgLocation[] = [
  {
    id: "loc_001",
    name: "Corporate Headquarters",
    address: "123 Business District",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    postalCode: "400001",
    timezone: "Asia/Kolkata",
    isHeadOffice: true,
    capacity: 500,
    employeeCount: 342,
    facilities: ["Conference Rooms", "Cafeteria", "Gym", "Parking"],
    contactPerson: "Priya Sharma",
    phone: "+91-22-12345678",
    email: "mumbai@buildsaathi.com",
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    id: "loc_002",
    name: "Delhi NCR Office",
    address: "456 Cyber City",
    city: "Gurgaon",
    state: "Haryana",
    country: "India",
    postalCode: "122002",
    timezone: "Asia/Kolkata",
    isHeadOffice: false,
    capacity: 200,
    employeeCount: 156,
    facilities: ["Conference Rooms", "Cafeteria", "Parking"],
    contactPerson: "Rahul Gupta",
    phone: "+91-124-9876543",
    email: "delhi@buildsaathi.com",
    coordinates: { lat: 28.4595, lng: 77.0266 },
  },
  {
    id: "loc_003",
    name: "Bangalore Tech Hub",
    address: "789 Electronics City",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    postalCode: "560100",
    timezone: "Asia/Kolkata",
    isHeadOffice: false,
    capacity: 300,
    employeeCount: 245,
    facilities: ["Conference Rooms", "Cafeteria", "Game Room", "Parking"],
    contactPerson: "Sneha Reddy",
    phone: "+91-80-11223344",
    email: "bangalore@buildsaathi.com",
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },
  {
    id: "loc_004",
    name: "Pune Development Center",
    address: "321 IT Park",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    postalCode: "411057",
    timezone: "Asia/Kolkata",
    isHeadOffice: false,
    capacity: 150,
    employeeCount: 98,
    facilities: ["Conference Rooms", "Cafeteria", "Parking"],
    contactPerson: "Amit Patil",
    phone: "+91-20-55667788",
    email: "pune@buildsaathi.com",
    coordinates: { lat: 18.5204, lng: 73.8567 },
  },
];

// Organization Units
export const orgUnits: OrgUnit[] = [
  {
    id: "org_001",
    name: "BuildSaathi Technologies",
    type: "company",
    code: "BST",
    description: "Parent company for all operations",
    parentId: null,
    locationId: "loc_001",
    managerId: "emp_001",
    budgetCode: "BST-2024",
    costCenter: "CC-000",
    isActive: true,
    establishedDate: "2020-01-01",
    employeeCount: 841,
    level: 0,
    path: ["org_001"],
  },
  {
    id: "org_002",
    name: "Technology Division",
    type: "division",
    code: "TECH",
    description: "Core technology and product development",
    parentId: "org_001",
    locationId: "loc_003",
    managerId: "emp_002",
    budgetCode: "TECH-2024",
    costCenter: "CC-100",
    isActive: true,
    establishedDate: "2020-02-01",
    employeeCount: 425,
    level: 1,
    path: ["org_001", "org_002"],
  },
  {
    id: "org_003",
    name: "Business Operations",
    type: "division",
    code: "BIZ",
    description: "Sales, marketing, and customer operations",
    parentId: "org_001",
    locationId: "loc_001",
    managerId: "emp_003",
    budgetCode: "BIZ-2024",
    costCenter: "CC-200",
    isActive: true,
    establishedDate: "2020-02-01",
    employeeCount: 285,
    level: 1,
    path: ["org_001", "org_003"],
  },
  {
    id: "org_004",
    name: "Corporate Functions",
    type: "division",
    code: "CORP",
    description: "HR, Finance, Legal, and Admin functions",
    parentId: "org_001",
    locationId: "loc_001",
    managerId: "emp_004",
    budgetCode: "CORP-2024",
    costCenter: "CC-300",
    isActive: true,
    establishedDate: "2020-02-01",
    employeeCount: 131,
    level: 1,
    path: ["org_001", "org_004"],
  },
  {
    id: "org_005",
    name: "Software Engineering",
    type: "department",
    code: "SWE",
    description: "Frontend, backend, and mobile development",
    parentId: "org_002",
    locationId: "loc_003",
    managerId: "emp_005",
    budgetCode: "SWE-2024",
    costCenter: "CC-110",
    isActive: true,
    establishedDate: "2020-03-01",
    employeeCount: 156,
    level: 2,
    path: ["org_001", "org_002", "org_005"],
  },
  {
    id: "org_006",
    name: "Product Management",
    type: "department",
    code: "PM",
    description: "Product strategy and roadmap",
    parentId: "org_002",
    locationId: "loc_003",
    managerId: "emp_006",
    budgetCode: "PM-2024",
    costCenter: "CC-120",
    isActive: true,
    establishedDate: "2020-03-01",
    employeeCount: 45,
    level: 2,
    path: ["org_001", "org_002", "org_006"],
  },
  {
    id: "org_007",
    name: "Quality Assurance",
    type: "department",
    code: "QA",
    description: "Testing and quality control",
    parentId: "org_002",
    locationId: "loc_004",
    managerId: "emp_007",
    budgetCode: "QA-2024",
    costCenter: "CC-130",
    isActive: true,
    establishedDate: "2020-03-01",
    employeeCount: 67,
    level: 2,
    path: ["org_001", "org_002", "org_007"],
  },
  {
    id: "org_008",
    name: "DevOps & Infrastructure",
    type: "department",
    code: "DEVOPS",
    description: "Cloud infrastructure and deployment",
    parentId: "org_002",
    locationId: "loc_003",
    managerId: "emp_008",
    budgetCode: "DEVOPS-2024",
    costCenter: "CC-140",
    isActive: true,
    establishedDate: "2020-04-01",
    employeeCount: 34,
    level: 2,
    path: ["org_001", "org_002", "org_008"],
  },
  {
    id: "org_009",
    name: "Data & Analytics",
    type: "department",
    code: "DATA",
    description: "Data science and business intelligence",
    parentId: "org_002",
    locationId: "loc_003",
    managerId: "emp_009",
    budgetCode: "DATA-2024",
    costCenter: "CC-150",
    isActive: true,
    establishedDate: "2020-05-01",
    employeeCount: 28,
    level: 2,
    path: ["org_001", "org_002", "org_009"],
  },
  {
    id: "org_010",
    name: "Frontend Development",
    type: "team",
    code: "FE",
    description: "React, Angular, and mobile app development",
    parentId: "org_005",
    locationId: "loc_003",
    managerId: "emp_010",
    budgetCode: "FE-2024",
    costCenter: "CC-111",
    isActive: true,
    establishedDate: "2020-06-01",
    employeeCount: 45,
    level: 3,
    path: ["org_001", "org_002", "org_005", "org_010"],
  },
  {
    id: "org_011",
    name: "Backend Development",
    type: "team",
    code: "BE",
    description: "Node.js, Python, and API development",
    parentId: "org_005",
    locationId: "loc_003",
    managerId: "emp_011",
    budgetCode: "BE-2024",
    costCenter: "CC-112",
    isActive: true,
    establishedDate: "2020-06-01",
    employeeCount: 52,
    level: 3,
    path: ["org_001", "org_002", "org_005", "org_011"],
  },
  {
    id: "org_012",
    name: "Sales",
    type: "department",
    code: "SALES",
    description: "Direct sales and business development",
    parentId: "org_003",
    locationId: "loc_001",
    managerId: "emp_012",
    budgetCode: "SALES-2024",
    costCenter: "CC-210",
    isActive: true,
    establishedDate: "2020-03-01",
    employeeCount: 89,
    level: 2,
    path: ["org_001", "org_003", "org_012"],
  },
  {
    id: "org_013",
    name: "Marketing",
    type: "department",
    code: "MKT",
    description: "Digital marketing and brand management",
    parentId: "org_003",
    locationId: "loc_002",
    managerId: "emp_013",
    budgetCode: "MKT-2024",
    costCenter: "CC-220",
    isActive: true,
    establishedDate: "2020-03-01",
    employeeCount: 56,
    level: 2,
    path: ["org_001", "org_003", "org_013"],
  },
  {
    id: "org_014",
    name: "Customer Success",
    type: "department",
    code: "CS",
    description: "Customer support and success management",
    parentId: "org_003",
    locationId: "loc_002",
    managerId: "emp_014",
    budgetCode: "CS-2024",
    costCenter: "CC-230",
    isActive: true,
    establishedDate: "2020-04-01",
    employeeCount: 78,
    level: 2,
    path: ["org_001", "org_003", "org_014"],
  },
  {
    id: "org_015",
    name: "Human Resources",
    type: "department",
    code: "HR",
    description: "Talent acquisition and people operations",
    parentId: "org_004",
    locationId: "loc_001",
    managerId: "emp_015",
    budgetCode: "HR-2024",
    costCenter: "CC-310",
    isActive: true,
    establishedDate: "2020-02-01",
    employeeCount: 34,
    level: 2,
    path: ["org_001", "org_004", "org_015"],
  },
  {
    id: "org_016",
    name: "Finance & Accounting",
    type: "department",
    code: "FIN",
    description: "Financial planning and accounting operations",
    parentId: "org_004",
    locationId: "loc_001",
    managerId: "emp_016",
    budgetCode: "FIN-2024",
    costCenter: "CC-320",
    isActive: true,
    establishedDate: "2020-02-01",
    employeeCount: 45,
    level: 2,
    path: ["org_001", "org_004", "org_016"],
  },
];

// Sample Employees (Key positions)
export const employees: Employee[] = [
  {
    id: "emp_001",
    employeeId: "BST001",
    firstName: "Rajesh",
    lastName: "Kumar",
    email: "rajesh.kumar@buildsaathi.com",
    phone: "+91-98765-43210",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh",
    position: "Chief Executive Officer",
    department: "Executive",
    orgUnitId: "org_001",
    locationId: "loc_001",
    managerId: null,
    directReports: ["emp_002", "emp_003", "emp_004"],
    level: 0,
    hireDate: "2020-01-01",
    status: "active",
    skills: ["Leadership", "Strategy", "Business Development"],
    certifications: ["MBA", "Executive Leadership"],
    jobGrade: "C1",
    salary: 5000000,
    workType: "full-time",
  },
  {
    id: "emp_002",
    employeeId: "BST002",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@buildsaathi.com",
    phone: "+91-98765-43211",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    position: "Chief Technology Officer",
    department: "Technology",
    orgUnitId: "org_002",
    locationId: "loc_003",
    managerId: "emp_001",
    directReports: ["emp_005", "emp_006", "emp_007", "emp_008", "emp_009"],
    level: 1,
    hireDate: "2020-01-15",
    status: "active",
    skills: ["Software Architecture", "Team Leadership", "Product Development"],
    certifications: ["AWS Solutions Architect", "Scrum Master"],
    jobGrade: "C2",
    salary: 3500000,
    workType: "full-time",
  },
  {
    id: "emp_003",
    employeeId: "BST003",
    firstName: "Amit",
    lastName: "Patel",
    email: "amit.patel@buildsaathi.com",
    phone: "+91-98765-43212",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=amit",
    position: "Chief Business Officer",
    department: "Business Operations",
    orgUnitId: "org_003",
    locationId: "loc_001",
    managerId: "emp_001",
    directReports: ["emp_012", "emp_013", "emp_014"],
    level: 1,
    hireDate: "2020-02-01",
    status: "active",
    skills: ["Sales Management", "Marketing Strategy", "Customer Relations"],
    certifications: ["Digital Marketing", "Sales Leadership"],
    jobGrade: "C2",
    salary: 3200000,
    workType: "full-time",
  },
  {
    id: "emp_004",
    employeeId: "BST004",
    firstName: "Sneha",
    lastName: "Reddy",
    email: "sneha.reddy@buildsaathi.com",
    phone: "+91-98765-43213",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sneha",
    position: "Chief People Officer",
    department: "Corporate Functions",
    orgUnitId: "org_004",
    locationId: "loc_001",
    managerId: "emp_001",
    directReports: ["emp_015", "emp_016"],
    level: 1,
    hireDate: "2020-02-01",
    status: "active",
    skills: ["People Management", "Organizational Development", "Strategic HR"],
    certifications: ["SHRM-CP", "Executive Coaching"],
    jobGrade: "C2",
    salary: 2800000,
    workType: "full-time",
  },
  {
    id: "emp_005",
    employeeId: "BST005",
    firstName: "Rahul",
    lastName: "Gupta",
    email: "rahul.gupta@buildsaathi.com",
    phone: "+91-98765-43214",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul",
    position: "VP Engineering",
    department: "Software Engineering",
    orgUnitId: "org_005",
    locationId: "loc_003",
    managerId: "emp_002",
    directReports: ["emp_010", "emp_011"],
    level: 2,
    hireDate: "2020-03-01",
    status: "active",
    skills: ["Software Engineering", "Team Management", "System Design"],
    certifications: ["Google Cloud Architect", "Agile Certification"],
    jobGrade: "VP1",
    salary: 2500000,
    workType: "full-time",
  },
];

// Organization Structure Analytics
export const orgAnalytics: OrgStructureAnalytics = {
  totalEmployees: 841,
  totalDepartments: 16,
  totalLocations: 4,
  avgTeamSize: 52.6,
  managementLevels: 4,
  spanOfControl: {
    avg: 6.2,
    max: 12,
    min: 2,
  },
  organizationHealth: {
    score: 85,
    factors: {
      hierarchyBalance: 88,
      spanControl: 82,
      vacantPositions: 85,
    },
  },
  growthMetrics: {
    headcountGrowth: 15.2,
    newHires: 127,
    departures: 23,
  },
};

// Organization Change Requests
export const orgChangeRequests: OrgChangeRequest[] = [
  {
    id: "req_001",
    type: "restructure",
    description: "Create new AI/ML team under Data & Analytics department",
    requestedBy: "emp_009",
    requestDate: "2024-01-15",
    effectiveDate: "2024-02-01",
    status: "pending",
    changes: {
      toOrgUnit: "org_009",
      newManagerId: "emp_009",
    },
    approvals: [
      {
        managerId: "emp_002",
        hrApproval: true,
        financeApproval: true,
        approvedDate: "2024-01-18",
      },
    ],
    impact: {
      affectedEmployees: 8,
      budgetImpact: 1200000,
      implementationEffort: "medium",
    },
  },
  {
    id: "req_002",
    type: "transfer",
    description: "Transfer senior frontend developer to mobile team",
    requestedBy: "emp_010",
    requestDate: "2024-01-20",
    effectiveDate: "2024-02-15",
    status: "approved",
    changes: {
      employeeId: "emp_025",
      fromOrgUnit: "org_010",
      toOrgUnit: "org_010",
      fromPosition: "Senior Frontend Developer",
      toPosition: "Mobile Development Lead",
    },
    approvals: [
      {
        managerId: "emp_005",
        hrApproval: true,
        approvedDate: "2024-01-22",
      },
    ],
    impact: {
      affectedEmployees: 1,
      budgetImpact: 150000,
      implementationEffort: "low",
    },
  },
];

// Helper functions
export const buildOrgHierarchy = (units: OrgUnit[]): OrgUnit[] => {
  const rootUnits = units.filter((unit) => unit.parentId === null);

  const buildChildren = (parentUnit: OrgUnit): OrgUnit => {
    const children = units.filter((unit) => unit.parentId === parentUnit.id);
    return {
      ...parentUnit,
      children: children.map((child) => buildChildren(child)),
    };
  };

  return rootUnits.map((root) => buildChildren(root));
};

export const getOrgUnitsByLocation = (locationId: string): OrgUnit[] => {
  return orgUnits.filter((unit) => unit.locationId === locationId);
};

export const getEmployeesByOrgUnit = (orgUnitId: string): Employee[] => {
  return employees.filter((emp) => emp.orgUnitId === orgUnitId);
};

export const calculateOrgMetrics = (units: OrgUnit[]) => {
  const totalEmployees = units.reduce(
    (sum, unit) => sum + unit.employeeCount,
    0,
  );
  const departments = units.filter((unit) => unit.type === "department");
  const teams = units.filter((unit) => unit.type === "team");

  return {
    totalEmployees,
    departments: departments.length,
    teams: teams.length,
    avgDepartmentSize:
      departments.length > 0 ? totalEmployees / departments.length : 0,
  };
};
