// Comprehensive Mock Data for Tenant-Driven Accounting System

import {
  AccountingTenant,
  TenantAccount,
  TenantJournalEntry,
  TenantFiscalYear,
  TenantBudget,
  TenantFixedAsset,
  TenantBankReconciliation,
  TenantCostCenter,
  TenantAccountingAnalytics,
  TenantAccountingConfiguration,
  AccountType,
  TransactionType,
  IndustryType,
  Currency,
  ConstructionAccountingExtension,
  RealEstateAccountingExtension,
  TechnologyAccountingExtension,
  ManufacturingAccountingExtension,
} from "./types";

// Accounting Tenants with Multi-Industry Coverage
export const accountingTenants: AccountingTenant[] = [
  {
    id: "tenant_buildcorp",
    name: "BuildCorp Constructions",
    legalName: "BuildCorp Constructions Private Limited",
    industryType: "construction",
    configuration: {
      id: "config_buildcorp",
      tenantId: "tenant_buildcorp",
      companyName: "BuildCorp Constructions",
      legalName: "BuildCorp Constructions Private Limited",
      industryType: "construction",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 4, // April
      fiscalYearEnd: 3, // March
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "construction_standard",
      accountCodeFormat: "####",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
      },
      numberingFormats: {
        journalEntry: "JE-{YYYY}-{####}",
        invoice: "INV-{YYYY}-{####}",
        receipt: "RCP-{YYYY}-{####}",
        payment: "PAY-{YYYY}-{####}",
      },
      approvalRequired: true,
      approvalLimits: [
        {
          role: "accountant",
          transactionType: "journal_entry",
          maxAmount: 100000,
          currency: "INR",
        },
        {
          role: "manager",
          transactionType: "journal_entry",
          maxAmount: 500000,
          currency: "INR",
        },
        {
          role: "director",
          transactionType: "journal_entry",
          maxAmount: 10000000,
          currency: "INR",
        },
      ],
      multiCurrencyEnabled: false,
      exchangeRateSource: "manual",
      integrations: {
        banking: true,
        payroll: true,
        inventory: true,
        crm: true,
        projects: true,
      },
      taxConfiguration: {
        gstApplicable: true,
        gstRegistrationNumber: "07AABCU9603R1ZX",
        tdsApplicable: true,
        tanNumber: "DELB12345E",
      },
      auditRequirements: {
        internalAudit: true,
        externalAudit: true,
        auditFrequency: "annually",
      },
      industrySettings: {
        construction: {
          projectAccounting: true,
          jobCosting: true,
          progressBilling: true,
          retentionAccounting: true,
          wipAccounting: {
            method: "percentage_completion",
            recognitionCriteria: ["milestone_completion", "cost_incurred"],
          },
        } as ConstructionAccountingExtension,
      },
      accessControls: {
        restrictPeriodAccess: true,
        allowPostingToClosedPeriods: false,
        requireApprovalForClosedPeriods: true,
      },
      backupSettings: {
        frequency: "daily",
        retentionPeriod: 84, // 7 years
        archiveOldData: true,
        archiveAfterPeriod: 7,
      },
      isActive: true,
      createdBy: "system",
      createdAt: "2023-04-01T00:00:00Z",
      updatedBy: "admin",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    accounts: [], // Will be populated below
    currentFiscalYear: {
      id: "fy_buildcorp_2023_24",
      tenantId: "tenant_buildcorp",
      fiscalYear: "2023-24",
      startDate: "2023-04-01",
      endDate: "2024-03-31",
      status: "current",
      isLocked: false,
      periods: [
        {
          id: "p1",
          periodNumber: 1,
          periodName: "Apr-2023",
          startDate: "2023-04-01",
          endDate: "2023-04-30",
          status: "hard_closed",
          closedBy: "accountant",
          closedAt: "2023-05-05T18:00:00Z",
        },
        {
          id: "p2",
          periodNumber: 2,
          periodName: "May-2023",
          startDate: "2023-05-01",
          endDate: "2023-05-31",
          status: "hard_closed",
          closedBy: "accountant",
          closedAt: "2023-06-05T18:00:00Z",
        },
        // ... more periods
        {
          id: "p12",
          periodNumber: 12,
          periodName: "Mar-2024",
          startDate: "2024-03-01",
          endDate: "2024-03-31",
          status: "open",
        },
      ],
      auditStatus: "in_progress",
      auditFirm: "Deloitte & Associates",
      auditStartDate: "2024-04-15",
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2024-03-01T00:00:00Z",
    },
    isActive: true,
    setupCompleted: true,
    lastActivity: "2024-03-15T14:30:00Z",
    subscriptionPlan: "enterprise",
    enabledFeatures: [
      "multi_project",
      "advanced_reporting",
      "audit_trail",
      "mobile_app",
    ],
    primaryContact: {
      name: "Rajesh Kumar",
      email: "rajesh@buildcorp.com",
      phone: "+91-9876543210",
      role: "CFO",
    },
    accountant: {
      name: "CA Priya Sharma",
      email: "priya@sharma-associates.com",
      phone: "+91-9876543211",
      firm: "Sharma & Associates",
    },
    createdAt: "2023-04-01T00:00:00Z",
    updatedAt: "2024-03-15T14:30:00Z",
  },
  {
    id: "tenant_proptech",
    name: "PropTech Solutions",
    legalName: "PropTech Solutions India Limited",
    industryType: "real_estate",
    configuration: {
      id: "config_proptech",
      tenantId: "tenant_proptech",
      companyName: "PropTech Solutions",
      legalName: "PropTech Solutions India Limited",
      industryType: "real_estate",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 4,
      fiscalYearEnd: 3,
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "real_estate_standard",
      accountCodeFormat: "##-##-##",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
      },
      numberingFormats: {
        journalEntry: "JV-{YYYY}-{####}",
        invoice: "BILL-{YYYY}-{####}",
        receipt: "REC-{YYYY}-{####}",
        payment: "PAY-{YYYY}-{####}",
      },
      approvalRequired: true,
      approvalLimits: [
        {
          role: "accountant",
          transactionType: "journal_entry",
          maxAmount: 50000,
          currency: "INR",
        },
        {
          role: "manager",
          transactionType: "journal_entry",
          maxAmount: 200000,
          currency: "INR",
        },
      ],
      multiCurrencyEnabled: false,
      exchangeRateSource: "manual",
      integrations: {
        banking: true,
        payroll: true,
        inventory: false,
        crm: true,
        projects: true,
      },
      taxConfiguration: {
        gstApplicable: true,
        gstRegistrationNumber: "09BBCDE1234F2Z5",
        tdsApplicable: true,
        tanNumber: "MUMH45678F",
      },
      auditRequirements: {
        internalAudit: false,
        externalAudit: true,
        auditFrequency: "annually",
      },
      industrySettings: {
        real_estate: {
          propertyAccounting: true,
          rentalIncomeTracking: true,
          maintenanceAccounting: true,
          depreciation: {
            buildingDepreciation: true,
            improvementDepreciation: true,
            method: "straight_line",
          },
          propertyDimensions: ["property_id", "tenant_id", "lease_type"],
          tenantAccounting: true,
          securityDepositAccounting: true,
        } as RealEstateAccountingExtension,
      },
      accessControls: {
        restrictPeriodAccess: true,
        allowPostingToClosedPeriods: false,
        requireApprovalForClosedPeriods: true,
      },
      backupSettings: {
        frequency: "weekly",
        retentionPeriod: 60,
        archiveOldData: true,
        archiveAfterPeriod: 5,
      },
      isActive: true,
      createdBy: "system",
      createdAt: "2023-01-01T00:00:00Z",
      updatedBy: "admin",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    accounts: [],
    currentFiscalYear: {
      id: "fy_proptech_2023_24",
      tenantId: "tenant_proptech",
      fiscalYear: "2023-24",
      startDate: "2023-04-01",
      endDate: "2024-03-31",
      status: "current",
      isLocked: false,
      periods: [],
      auditStatus: "not_started",
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2024-03-01T00:00:00Z",
    },
    isActive: true,
    setupCompleted: true,
    lastActivity: "2024-03-15T16:45:00Z",
    subscriptionPlan: "professional",
    enabledFeatures: [
      "property_management",
      "rental_tracking",
      "maintenance_scheduling",
    ],
    primaryContact: {
      name: "Amit Patel",
      email: "amit@proptech.com",
      phone: "+91-9876543212",
      role: "Finance Manager",
    },
    accountant: {
      name: "CA Neha Gupta",
      email: "neha@gupta-co.com",
      phone: "+91-9876543213",
      firm: "Gupta & Co.",
    },
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-03-15T16:45:00Z",
  },
  {
    id: "tenant_techcorp",
    name: "TechCorp Innovations",
    legalName: "TechCorp Innovations Private Limited",
    industryType: "technology",
    configuration: {
      id: "config_techcorp",
      tenantId: "tenant_techcorp",
      companyName: "TechCorp Innovations",
      legalName: "TechCorp Innovations Private Limited",
      industryType: "technology",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "USD",
      fiscalYearStart: 4,
      fiscalYearEnd: 3,
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "technology_saas",
      accountCodeFormat: "####",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
      },
      numberingFormats: {
        journalEntry: "JE-{YYYY}-{####}",
        invoice: "INV-{YYYY}-{####}",
        receipt: "RCP-{YYYY}-{####}",
        payment: "PAY-{YYYY}-{####}",
      },
      approvalRequired: true,
      approvalLimits: [
        {
          role: "accountant",
          transactionType: "journal_entry",
          maxAmount: 100000,
          currency: "INR",
        },
        {
          role: "cfo",
          transactionType: "journal_entry",
          maxAmount: 1000000,
          currency: "INR",
        },
      ],
      multiCurrencyEnabled: true,
      exchangeRateSource: "api",
      exchangeRateProvider: "xe.com",
      integrations: {
        banking: true,
        payroll: true,
        inventory: false,
        crm: true,
        projects: true,
      },
      taxConfiguration: {
        gstApplicable: true,
        gstRegistrationNumber: "29ABCDE1234F1Z5",
        tdsApplicable: true,
        tanNumber: "BANB78901G",
      },
      auditRequirements: {
        internalAudit: true,
        externalAudit: true,
        auditFrequency: "quarterly",
      },
      industrySettings: {
        technology: {
          subscriptionRevenue: true,
          revenueRecognition: {
            method: "saas",
            deferredRevenueTracking: true,
          },
          rdAccounting: true,
          intellectualPropertyAccounting: true,
          esopAccounting: true,
          cacAccounting: true,
          customerLifetimeValue: true,
        } as TechnologyAccountingExtension,
      },
      accessControls: {
        restrictPeriodAccess: true,
        allowPostingToClosedPeriods: false,
        requireApprovalForClosedPeriods: true,
      },
      backupSettings: {
        frequency: "daily",
        retentionPeriod: 84,
        archiveOldData: true,
        archiveAfterPeriod: 7,
      },
      isActive: true,
      createdBy: "system",
      createdAt: "2020-04-01T00:00:00Z",
      updatedBy: "admin",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    accounts: [],
    currentFiscalYear: {
      id: "fy_techcorp_2023_24",
      tenantId: "tenant_techcorp",
      fiscalYear: "2023-24",
      startDate: "2023-04-01",
      endDate: "2024-03-31",
      status: "current",
      isLocked: false,
      periods: [],
      auditStatus: "completed",
      auditFirm: "KPMG India",
      auditStartDate: "2024-01-15",
      auditCompletionDate: "2024-02-28",
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2024-03-01T00:00:00Z",
    },
    isActive: true,
    setupCompleted: true,
    lastActivity: "2024-03-15T11:20:00Z",
    subscriptionPlan: "enterprise",
    enabledFeatures: [
      "multi_currency",
      "revenue_recognition",
      "advanced_analytics",
      "api_integration",
    ],
    primaryContact: {
      name: "Vikram Singh",
      email: "vikram@techcorp.com",
      phone: "+91-9876543214",
      role: "CFO",
    },
    accountant: {
      name: "CA Ravi Mehta",
      email: "ravi@mehta-associates.com",
      phone: "+91-9876543215",
      firm: "Mehta & Associates",
    },
    createdAt: "2020-04-01T00:00:00Z",
    updatedAt: "2024-03-15T11:20:00Z",
  },
  {
    id: "tenant_manufacturing",
    name: "SteelCraft Industries",
    legalName: "SteelCraft Industries Limited",
    industryType: "manufacturing",
    configuration: {
      id: "config_manufacturing",
      tenantId: "tenant_manufacturing",
      companyName: "SteelCraft Industries",
      legalName: "SteelCraft Industries Limited",
      industryType: "manufacturing",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 4,
      fiscalYearEnd: 3,
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "manufacturing_standard",
      accountCodeFormat: "##-##-###",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
      },
      numberingFormats: {
        journalEntry: "JE-{YYYY}-{####}",
        invoice: "SI-{YYYY}-{####}",
        receipt: "RC-{YYYY}-{####}",
        payment: "PV-{YYYY}-{####}",
      },
      approvalRequired: true,
      approvalLimits: [
        {
          role: "cost_accountant",
          transactionType: "journal_entry",
          maxAmount: 250000,
          currency: "INR",
        },
        {
          role: "plant_manager",
          transactionType: "journal_entry",
          maxAmount: 1000000,
          currency: "INR",
        },
      ],
      multiCurrencyEnabled: true,
      exchangeRateSource: "manual",
      integrations: {
        banking: true,
        payroll: true,
        inventory: true,
        crm: true,
        projects: false,
      },
      taxConfiguration: {
        gstApplicable: true,
        gstRegistrationNumber: "24CDEFG5678H3Z6",
        tdsApplicable: true,
        tanNumber: "PUNE56789H",
      },
      auditRequirements: {
        internalAudit: true,
        externalAudit: true,
        auditFrequency: "quarterly",
      },
      industrySettings: {
        manufacturing: {
          inventoryAccounting: true,
          costAccounting: {
            method: "standard",
            varianceAnalysis: true,
          },
          wipInventory: true,
          overheadAllocation: {
            method: "activity_based",
            costDrivers: ["machine_hours", "labor_hours", "material_cost"],
          },
          qualityCostAccounting: true,
        } as ManufacturingAccountingExtension,
      },
      accessControls: {
        restrictPeriodAccess: true,
        allowPostingToClosedPeriods: false,
        requireApprovalForClosedPeriods: true,
      },
      backupSettings: {
        frequency: "daily",
        retentionPeriod: 84,
        archiveOldData: true,
        archiveAfterPeriod: 7,
      },
      isActive: true,
      createdBy: "system",
      createdAt: "2018-04-01T00:00:00Z",
      updatedBy: "admin",
      updatedAt: "2024-01-15T10:30:00Z",
    },
    accounts: [],
    currentFiscalYear: {
      id: "fy_manufacturing_2023_24",
      tenantId: "tenant_manufacturing",
      fiscalYear: "2023-24",
      startDate: "2023-04-01",
      endDate: "2024-03-31",
      status: "current",
      isLocked: false,
      periods: [],
      auditStatus: "in_progress",
      auditFirm: "Ernst & Young",
      auditStartDate: "2024-02-01",
      createdAt: "2023-04-01T00:00:00Z",
      updatedAt: "2024-03-01T00:00:00Z",
    },
    isActive: true,
    setupCompleted: true,
    lastActivity: "2024-03-15T09:15:00Z",
    subscriptionPlan: "enterprise",
    enabledFeatures: [
      "cost_accounting",
      "inventory_valuation",
      "variance_analysis",
      "quality_costing",
    ],
    primaryContact: {
      name: "Suresh Reddy",
      email: "suresh@steelcraft.com",
      phone: "+91-9876543216",
      role: "Finance Director",
    },
    accountant: {
      name: "CA Lakshmi Narayanan",
      email: "lakshmi@narayanan-co.com",
      phone: "+91-9876543217",
      firm: "Narayanan & Co.",
    },
    createdAt: "2018-04-01T00:00:00Z",
    updatedAt: "2024-03-15T09:15:00Z",
  },
];

// Chart of Accounts for Construction Industry (BuildCorp)
export const buildCorpAccounts: TenantAccount[] = [
  // ASSETS
  {
    id: "acc_1000",
    tenantId: "tenant_buildcorp",
    accountCode: "1000",
    accountName: "ASSETS",
    accountType: "assets",
    accountSubType: "current_assets",
    level: 1,
    isActive: true,
    currentBalance: 285750000,
    openingBalance: 245000000,
    ytdBalance: 285750000,
    lastYearBalance: 245000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1100",
    tenantId: "tenant_buildcorp",
    accountCode: "1100",
    accountName: "Current Assets",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1000",
    level: 2,
    isActive: true,
    currentBalance: 185750000,
    openingBalance: 165000000,
    ytdBalance: 185750000,
    lastYearBalance: 165000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1110",
    tenantId: "tenant_buildcorp",
    accountCode: "1110",
    accountName: "Cash and Bank",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1100",
    level: 3,
    isActive: true,
    currentBalance: 45750000,
    openingBalance: 35000000,
    ytdBalance: 45750000,
    lastYearBalance: 35000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1111",
    tenantId: "tenant_buildcorp",
    accountCode: "1111",
    accountName: "Petty Cash",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1110",
    level: 4,
    isActive: true,
    currentBalance: 50000,
    openingBalance: 25000,
    ytdBalance: 50000,
    lastYearBalance: 25000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: true,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1112",
    tenantId: "tenant_buildcorp",
    accountCode: "1112",
    accountName: "HDFC Bank - Current Account",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1110",
    level: 4,
    isActive: true,
    currentBalance: 25700000,
    openingBalance: 20000000,
    ytdBalance: 25700000,
    lastYearBalance: 20000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: true,
    isCashAccount: false,
    isStatutoryAccount: false,
    bankDetails: {
      bankName: "HDFC Bank",
      accountNumber: "50200012345678",
      routingNumber: "HDFC0001234",
      bankAddress: "Mumbai, Maharashtra",
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1113",
    tenantId: "tenant_buildcorp",
    accountCode: "1113",
    accountName: "ICICI Bank - Savings Account",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1110",
    level: 4,
    isActive: true,
    currentBalance: 20000000,
    openingBalance: 14975000,
    ytdBalance: 20000000,
    lastYearBalance: 14975000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: true,
    isCashAccount: false,
    isStatutoryAccount: false,
    bankDetails: {
      bankName: "ICICI Bank",
      accountNumber: "012345678901",
      routingNumber: "ICIC0001234",
      bankAddress: "Delhi, India",
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1120",
    tenantId: "tenant_buildcorp",
    accountCode: "1120",
    accountName: "Accounts Receivable",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1100",
    level: 3,
    isActive: true,
    currentBalance: 85000000,
    openingBalance: 75000000,
    ytdBalance: 85000000,
    lastYearBalance: 75000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    industryAttributes: {
      agingBuckets: ["0-30", "31-60", "61-90", "90+"],
      retentionAmount: 8500000, // 10% retention in construction
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1130",
    tenantId: "tenant_buildcorp",
    accountCode: "1130",
    accountName: "Work in Progress",
    accountType: "assets",
    accountSubType: "current_assets",
    parentAccountId: "acc_1100",
    level: 3,
    isActive: true,
    currentBalance: 55000000,
    openingBalance: 55000000,
    ytdBalance: 55000000,
    lastYearBalance: 55000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    industryAttributes: {
      projectIds: ["PROJ_001", "PROJ_002", "PROJ_003"],
      completionMethod: "percentage_completion",
      recognitionBasis: "cost_to_cost",
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  // Fixed Assets
  {
    id: "acc_1200",
    tenantId: "tenant_buildcorp",
    accountCode: "1200",
    accountName: "Fixed Assets",
    accountType: "assets",
    accountSubType: "fixed_assets",
    parentAccountId: "acc_1000",
    level: 2,
    isActive: true,
    currentBalance: 100000000,
    openingBalance: 80000000,
    ytdBalance: 100000000,
    lastYearBalance: 80000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1210",
    tenantId: "tenant_buildcorp",
    accountCode: "1210",
    accountName: "Plant & Equipment",
    accountType: "assets",
    accountSubType: "fixed_assets",
    parentAccountId: "acc_1200",
    level: 3,
    isActive: true,
    currentBalance: 75000000,
    openingBalance: 60000000,
    ytdBalance: 75000000,
    lastYearBalance: 60000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    depreciationConfig: {
      method: "written_down_value",
      rate: 15,
      usefulLife: 10,
      salvageValue: 7500000,
      startDate: "2023-04-01",
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_1220",
    tenantId: "tenant_buildcorp",
    accountCode: "1220",
    accountName: "Buildings",
    accountType: "assets",
    accountSubType: "fixed_assets",
    parentAccountId: "acc_1200",
    level: 3,
    isActive: true,
    currentBalance: 25000000,
    openingBalance: 20000000,
    ytdBalance: 25000000,
    lastYearBalance: 20000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    depreciationConfig: {
      method: "straight_line",
      rate: 5,
      usefulLife: 30,
      salvageValue: 5000000,
      startDate: "2023-04-01",
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },

  // LIABILITIES
  {
    id: "acc_2000",
    tenantId: "tenant_buildcorp",
    accountCode: "2000",
    accountName: "LIABILITIES",
    accountType: "liabilities",
    accountSubType: "current_liabilities",
    level: 1,
    isActive: true,
    currentBalance: 145500000,
    openingBalance: 125000000,
    ytdBalance: 145500000,
    lastYearBalance: 125000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_2100",
    tenantId: "tenant_buildcorp",
    accountCode: "2100",
    accountName: "Current Liabilities",
    accountType: "liabilities",
    accountSubType: "current_liabilities",
    parentAccountId: "acc_2000",
    level: 2,
    isActive: true,
    currentBalance: 95500000,
    openingBalance: 85000000,
    ytdBalance: 95500000,
    lastYearBalance: 85000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_2110",
    tenantId: "tenant_buildcorp",
    accountCode: "2110",
    accountName: "Accounts Payable",
    accountType: "liabilities",
    accountSubType: "current_liabilities",
    parentAccountId: "acc_2100",
    level: 3,
    isActive: true,
    currentBalance: 45000000,
    openingBalance: 35000000,
    ytdBalance: 45000000,
    lastYearBalance: 35000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_2120",
    tenantId: "tenant_buildcorp",
    accountCode: "2120",
    accountName: "GST Output Tax Payable",
    accountType: "liabilities",
    accountSubType: "current_liabilities",
    parentAccountId: "acc_2100",
    level: 3,
    isActive: true,
    currentBalance: 15500000,
    openingBalance: 12000000,
    ytdBalance: 15500000,
    lastYearBalance: 12000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: true,
    taxConfig: {
      gstApplicable: true,
      gstRate: 18,
      tdsApplicable: false,
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },

  // EQUITY
  {
    id: "acc_3000",
    tenantId: "tenant_buildcorp",
    accountCode: "3000",
    accountName: "EQUITY",
    accountType: "equity",
    accountSubType: "contributed_capital",
    level: 1,
    isActive: true,
    currentBalance: 140250000,
    openingBalance: 120000000,
    ytdBalance: 140250000,
    lastYearBalance: 120000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_3100",
    tenantId: "tenant_buildcorp",
    accountCode: "3100",
    accountName: "Share Capital",
    accountType: "equity",
    accountSubType: "contributed_capital",
    parentAccountId: "acc_3000",
    level: 2,
    isActive: true,
    currentBalance: 100000000,
    openingBalance: 100000000,
    ytdBalance: 100000000,
    lastYearBalance: 100000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_3200",
    tenantId: "tenant_buildcorp",
    accountCode: "3200",
    accountName: "Retained Earnings",
    accountType: "equity",
    accountSubType: "retained_earnings",
    parentAccountId: "acc_3000",
    level: 2,
    isActive: true,
    currentBalance: 40250000,
    openingBalance: 20000000,
    ytdBalance: 40250000,
    lastYearBalance: 20000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },

  // REVENUE
  {
    id: "acc_4000",
    tenantId: "tenant_buildcorp",
    accountCode: "4000",
    accountName: "REVENUE",
    accountType: "revenue",
    accountSubType: "operating_revenue",
    level: 1,
    isActive: true,
    currentBalance: 450000000,
    openingBalance: 0,
    ytdBalance: 450000000,
    lastYearBalance: 380000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_4100",
    tenantId: "tenant_buildcorp",
    accountCode: "4100",
    accountName: "Construction Revenue",
    accountType: "revenue",
    accountSubType: "operating_revenue",
    parentAccountId: "acc_4000",
    level: 2,
    isActive: true,
    currentBalance: 420000000,
    openingBalance: 0,
    ytdBalance: 420000000,
    lastYearBalance: 350000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    taxConfig: {
      gstApplicable: true,
      gstRate: 18,
      tdsApplicable: true,
      tdsSection: "194C",
      tdsRate: 1,
    },
    industryAttributes: {
      revenueRecognitionMethod: "percentage_completion",
      projectBased: true,
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },

  // EXPENSES
  {
    id: "acc_5000",
    tenantId: "tenant_buildcorp",
    accountCode: "5000",
    accountName: "EXPENSES",
    accountType: "expenses",
    accountSubType: "operating_expenses",
    level: 1,
    isActive: true,
    currentBalance: 325000000,
    openingBalance: 0,
    ytdBalance: 325000000,
    lastYearBalance: 275000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_5100",
    tenantId: "tenant_buildcorp",
    accountCode: "5100",
    accountName: "Direct Costs",
    accountType: "expenses",
    accountSubType: "cost_of_goods_sold",
    parentAccountId: "acc_5000",
    level: 2,
    isActive: true,
    currentBalance: 250000000,
    openingBalance: 0,
    ytdBalance: 250000000,
    lastYearBalance: 210000000,
    currency: "INR",
    allowDirectPosting: false,
    isControlAccount: true,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_5110",
    tenantId: "tenant_buildcorp",
    accountCode: "5110",
    accountName: "Material Costs",
    accountType: "expenses",
    accountSubType: "cost_of_goods_sold",
    parentAccountId: "acc_5100",
    level: 3,
    isActive: true,
    currentBalance: 180000000,
    openingBalance: 0,
    ytdBalance: 180000000,
    lastYearBalance: 150000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    taxConfig: {
      gstApplicable: true,
      gstRate: 18,
      tdsApplicable: true,
      tdsSection: "194C",
      tdsRate: 1,
    },
    industryAttributes: {
      materialTypes: ["cement", "steel", "sand", "aggregate"],
      projectAllocable: true,
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "acc_5120",
    tenantId: "tenant_buildcorp",
    accountCode: "5120",
    accountName: "Labour Costs",
    accountType: "expenses",
    accountSubType: "cost_of_goods_sold",
    parentAccountId: "acc_5100",
    level: 3,
    isActive: true,
    currentBalance: 70000000,
    openingBalance: 0,
    ytdBalance: 70000000,
    lastYearBalance: 60000000,
    currency: "INR",
    allowDirectPosting: true,
    isControlAccount: false,
    isBankAccount: false,
    isCashAccount: false,
    isStatutoryAccount: false,
    taxConfig: {
      gstApplicable: false,
      tdsApplicable: true,
      tdsSection: "194C",
      tdsRate: 1,
    },
    industryAttributes: {
      labourTypes: ["skilled", "unskilled", "supervisory"],
      projectAllocable: true,
    },
    createdBy: "system",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "accountant",
    updatedAt: "2024-03-15T10:00:00Z",
  },
];

// Sample Journal Entries for BuildCorp
export const buildCorpJournalEntries: TenantJournalEntry[] = [
  {
    id: "je_001",
    tenantId: "tenant_buildcorp",
    entryNumber: "JE-2024-001",
    date: "2024-03-01",
    type: "sales_invoice",
    reference: "INV-2024-0045",
    description: "Project Phoenix - Milestone 3 Billing",
    totalAmount: 12500000,
    currency: "INR",
    lineItems: [
      {
        id: "li_001",
        accountId: "acc_1120",
        accountCode: "1120",
        accountName: "Accounts Receivable",
        description: "Project Phoenix Billing",
        debitAmount: 12500000,
        creditAmount: 0,
        isReconciled: false,
        project: "PROJ_001",
        department: "Construction",
        costCenter: "CC_001",
      },
      {
        id: "li_002",
        accountId: "acc_4100",
        accountCode: "4100",
        accountName: "Construction Revenue",
        description: "Project Phoenix Revenue Recognition",
        debitAmount: 0,
        creditAmount: 12500000,
        isReconciled: true,
        project: "PROJ_001",
        department: "Construction",
        costCenter: "CC_001",
      },
    ],
    status: "posted",
    approvalLevel: 2,
    approvedBy: "manager@buildcorp.com",
    approvedAt: "2024-03-01T14:30:00Z",
    sourceModule: "manual",
    accountingPeriod: "2024-03",
    fiscalYear: "2023-24",
    bookClosingStatus: "open",
    attachments: [
      {
        id: "att_001",
        fileName: "project_phoenix_milestone3.pdf",
        fileType: "pdf",
        fileSize: 2048000,
        fileUrl: "/documents/project_phoenix_milestone3.pdf",
        uploadedBy: "accountant@buildcorp.com",
        uploadedAt: "2024-03-01T10:00:00Z",
        description: "Milestone completion certificate",
      },
    ],
    tags: ["project_billing", "milestone", "revenue_recognition"],
    category: "Revenue",
    department: "Construction",
    project: "PROJ_001",
    costCenter: "CC_001",
    auditTrail: [
      {
        id: "audit_001",
        action: "created",
        performedBy: "accountant@buildcorp.com",
        performedAt: "2024-03-01T10:00:00Z",
        details: { amount: 12500000, project: "PROJ_001" },
        ipAddress: "192.168.1.100",
      },
      {
        id: "audit_002",
        action: "approved",
        performedBy: "manager@buildcorp.com",
        performedAt: "2024-03-01T14:30:00Z",
        details: { approvalLevel: 2 },
        ipAddress: "192.168.1.101",
      },
      {
        id: "audit_003",
        action: "posted",
        performedBy: "system",
        performedAt: "2024-03-01T14:31:00Z",
        details: { posted: true },
      },
    ],
    createdBy: "accountant@buildcorp.com",
    createdAt: "2024-03-01T10:00:00Z",
    updatedBy: "system",
    updatedAt: "2024-03-01T14:31:00Z",
  },
  {
    id: "je_002",
    tenantId: "tenant_buildcorp",
    entryNumber: "JE-2024-002",
    date: "2024-03-02",
    type: "purchase_invoice",
    reference: "BILL-5678",
    description: "Cement Purchase from ABC Suppliers",
    totalAmount: 2500000,
    currency: "INR",
    lineItems: [
      {
        id: "li_003",
        accountId: "acc_5110",
        accountCode: "5110",
        accountName: "Material Costs",
        description: "Cement for Project Phoenix",
        debitAmount: 2118644,
        creditAmount: 0,
        taxAmount: 381356,
        taxRate: 18,
        taxCode: "GST18",
        isReconciled: false,
        project: "PROJ_001",
        department: "Construction",
        quantity: 500,
        rate: 4237.29,
        unit: "MT",
      },
      {
        id: "li_004",
        accountId: "acc_1115", // GST Input Tax Credit
        accountCode: "1115",
        accountName: "GST Input Tax Credit",
        description: "Input GST on Cement Purchase",
        debitAmount: 381356,
        creditAmount: 0,
        isReconciled: false,
        department: "Accounts",
      },
      {
        id: "li_005",
        accountId: "acc_2110",
        accountCode: "2110",
        accountName: "Accounts Payable",
        description: "ABC Suppliers",
        debitAmount: 0,
        creditAmount: 2500000,
        isReconciled: false,
        department: "Accounts",
      },
    ],
    status: "posted",
    approvalLevel: 1,
    approvedBy: "accountant@buildcorp.com",
    approvedAt: "2024-03-02T11:00:00Z",
    sourceModule: "inventory",
    sourceDocumentId: "PO_001",
    sourceDocumentType: "purchase_order",
    accountingPeriod: "2024-03",
    fiscalYear: "2023-24",
    bookClosingStatus: "open",
    attachments: [],
    tags: ["material_purchase", "cement", "gst"],
    category: "Purchase",
    department: "Construction",
    project: "PROJ_001",
    auditTrail: [
      {
        id: "audit_004",
        action: "created",
        performedBy: "system",
        performedAt: "2024-03-02T10:00:00Z",
        details: { sourceModule: "inventory", amount: 2500000 },
      },
      {
        id: "audit_005",
        action: "posted",
        performedBy: "accountant@buildcorp.com",
        performedAt: "2024-03-02T11:00:00Z",
        details: { posted: true },
        ipAddress: "192.168.1.100",
      },
    ],
    createdBy: "system",
    createdAt: "2024-03-02T10:00:00Z",
    updatedBy: "accountant@buildcorp.com",
    updatedAt: "2024-03-02T11:00:00Z",
  },
];

// Budget Data for BuildCorp
export const buildCorpBudgets: TenantBudget[] = [
  {
    id: "budget_001",
    tenantId: "tenant_buildcorp",
    budgetName: "Annual Budget FY 2023-24",
    budgetType: "annual",
    fiscalYear: "2023-24",
    startDate: "2023-04-01",
    endDate: "2024-03-31",
    currency: "INR",
    budgetLines: [
      {
        id: "bl_001",
        accountId: "acc_4100",
        accountCode: "4100",
        accountName: "Construction Revenue",
        budgetAmounts: [
          {
            period: "2023-04",
            amount: 35000000,
            isActual: false,
            lastUpdated: "2023-03-15T00:00:00Z",
          },
          {
            period: "2023-05",
            amount: 38000000,
            isActual: false,
            lastUpdated: "2023-03-15T00:00:00Z",
          },
          // ... more periods
        ],
        actualAmounts: [
          {
            period: "2023-04",
            amount: 37500000,
            isActual: true,
            lastUpdated: "2023-05-01T00:00:00Z",
          },
          {
            period: "2023-05",
            amount: 42000000,
            isActual: true,
            lastUpdated: "2023-06-01T00:00:00Z",
          },
          // ... more periods
        ],
        variance: 6500000,
        variancePercentage: 15.7,
        varianceReason: "Higher than expected project completions",
        allocations: [
          {
            departmentId: "dept_001",
            departmentName: "Residential Projects",
            percentage: 60,
            amount: 252000000,
          },
          {
            departmentId: "dept_002",
            departmentName: "Commercial Projects",
            percentage: 40,
            amount: 168000000,
          },
        ],
      },
      {
        id: "bl_002",
        accountId: "acc_5110",
        accountCode: "5110",
        accountName: "Material Costs",
        budgetAmounts: [
          {
            period: "2023-04",
            amount: 15000000,
            isActual: false,
            lastUpdated: "2023-03-15T00:00:00Z",
          },
          {
            period: "2023-05",
            amount: 16000000,
            isActual: false,
            lastUpdated: "2023-03-15T00:00:00Z",
          },
          // ... more periods
        ],
        actualAmounts: [
          {
            period: "2023-04",
            amount: 16500000,
            isActual: true,
            lastUpdated: "2023-05-01T00:00:00Z",
          },
          {
            period: "2023-05",
            amount: 17200000,
            isActual: true,
            lastUpdated: "2023-06-01T00:00:00Z",
          },
          // ... more periods
        ],
        variance: -15000000,
        variancePercentage: -8.3,
        varianceReason: "Increase in raw material prices",
      },
    ],
    totalBudget: 420000000,
    totalActual: 450000000,
    totalVariance: 30000000,
    status: "active",
    approvalWorkflow: [
      {
        level: 1,
        approverRole: "Budget Manager",
        approverId: "budget_mgr",
        approverName: "Suresh Kumar",
        status: "approved",
        approvedAt: "2023-03-10T10:00:00Z",
      },
      {
        level: 2,
        approverRole: "CFO",
        approverId: "cfo",
        approverName: "Rajesh Kumar",
        status: "approved",
        approvedAt: "2023-03-12T14:00:00Z",
      },
    ],
    version: 1,
    revisionHistory: [],
    createdBy: "budget_manager@buildcorp.com",
    createdAt: "2023-03-01T00:00:00Z",
    updatedBy: "accountant@buildcorp.com",
    updatedAt: "2024-03-01T00:00:00Z",
  },
];

// Analytics Data for BuildCorp
export const buildCorpAnalytics: TenantAccountingAnalytics = {
  tenantId: "tenant_buildcorp",
  period: "2023-24",
  generatedAt: "2024-03-15T18:00:00Z",
  liquidityRatios: {
    currentRatio: 1.94,
    quickRatio: 1.37,
    cashRatio: 0.48,
  },
  profitabilityRatios: {
    grossProfitMargin: 44.4,
    netProfitMargin: 27.8,
    returnOnAssets: 43.7,
    returnOnEquity: 89.2,
    operatingMargin: 32.1,
  },
  leverageRatios: {
    debtToEquityRatio: 1.04,
    debtToAssetsRatio: 0.51,
    interestCoverageRatio: 12.5,
    debtServiceCoverageRatio: 2.8,
  },
  efficiencyRatios: {
    assetTurnover: 1.57,
    inventoryTurnover: 8.2,
    receivablesTurnover: 5.3,
    payablesTurnover: 7.2,
    workingCapitalTurnover: 4.9,
  },
  cashFlowMetrics: {
    operatingCashFlow: 95000000,
    investingCashFlow: -25000000,
    financingCashFlow: -15000000,
    netCashFlow: 55000000,
    cashConversionCycle: 45,
  },
  trends: {
    revenueGrowth: 18.4,
    expenseGrowth: 18.2,
    profitGrowth: 25.7,
    assetGrowth: 16.6,
    monthlyTrends: [
      {
        month: "2023-04",
        revenue: 37500000,
        expenses: 27000000,
        profit: 10500000,
        cashFlow: 8500000,
        metrics: { margin: 28.0 },
      },
      {
        month: "2023-05",
        revenue: 42000000,
        expenses: 30000000,
        profit: 12000000,
        cashFlow: 9800000,
        metrics: { margin: 28.6 },
      },
      {
        month: "2023-06",
        revenue: 38500000,
        expenses: 28000000,
        profit: 10500000,
        cashFlow: 8200000,
        metrics: { margin: 27.3 },
      },
      // ... more months
    ],
  },
  industryBenchmarks: {
    industryType: "construction",
    benchmarkRatios: {
      currentRatio: 1.75,
      grossProfitMargin: 25.0,
      netProfitMargin: 15.0,
      returnOnAssets: 18.0,
      debtToEquityRatio: 1.2,
    },
    percentileRanking: {
      currentRatio: 75,
      grossProfitMargin: 95,
      netProfitMargin: 90,
      returnOnAssets: 85,
    },
  },
  riskIndicators: {
    riskScore: 25,
    riskLevel: "low",
    riskFactors: [
      "High receivables concentration",
      "Seasonal revenue patterns",
    ],
    recommendations: [
      "Diversify customer base to reduce concentration risk",
      "Implement better cash flow forecasting",
      "Consider factoring for large receivables",
    ],
  },
};

// Cost Centers for BuildCorp
export const buildCorpCostCenters: TenantCostCenter[] = [
  {
    id: "cc_001",
    tenantId: "tenant_buildcorp",
    costCenterCode: "CC-RES",
    costCenterName: "Residential Projects",
    description: "All residential construction projects",
    level: 1,
    isActive: true,
    managerId: "mgr_001",
    managerName: "Suresh Reddy",
    managerEmail: "suresh@buildcorp.com",
    budgetAmount: 252000000,
    actualAmount: 275000000,
    variance: -23000000,
    allocationMethod: "direct",
    allocationRules: [
      {
        id: "rule_001",
        expenseType: "Direct Labor",
        allocationBasis: "Project Hours",
        percentage: 100,
        isActive: true,
      },
      {
        id: "rule_002",
        expenseType: "Overhead",
        allocationBasis: "Revenue Percentage",
        percentage: 60,
        isActive: true,
      },
    ],
    performanceMetrics: {
      projectsCompleted: 8,
      averageProjectMargin: 28.5,
      customerSatisfactionScore: 4.2,
      safetyIncidents: 2,
    },
    createdBy: "admin@buildcorp.com",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "manager@buildcorp.com",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "cc_002",
    tenantId: "tenant_buildcorp",
    costCenterCode: "CC-COM",
    costCenterName: "Commercial Projects",
    description: "All commercial construction projects",
    level: 1,
    isActive: true,
    managerId: "mgr_002",
    managerName: "Priya Sharma",
    managerEmail: "priya@buildcorp.com",
    budgetAmount: 168000000,
    actualAmount: 175000000,
    variance: -7000000,
    allocationMethod: "percentage",
    allocationRules: [
      {
        id: "rule_003",
        expenseType: "Direct Labor",
        allocationBasis: "Project Hours",
        percentage: 100,
        isActive: true,
      },
      {
        id: "rule_004",
        expenseType: "Overhead",
        allocationBasis: "Revenue Percentage",
        percentage: 40,
        isActive: true,
      },
    ],
    performanceMetrics: {
      projectsCompleted: 5,
      averageProjectMargin: 32.1,
      customerSatisfactionScore: 4.5,
      safetyIncidents: 1,
    },
    createdBy: "admin@buildcorp.com",
    createdAt: "2023-04-01T00:00:00Z",
    updatedBy: "manager@buildcorp.com",
    updatedAt: "2024-03-01T00:00:00Z",
  },
];

// Helper functions to get data by tenant
export const getAccountsByTenant = (tenantId: string): TenantAccount[] => {
  switch (tenantId) {
    case "tenant_buildcorp":
      return buildCorpAccounts;
    default:
      return [];
  }
};

export const getJournalEntriesByTenant = (
  tenantId: string,
): TenantJournalEntry[] => {
  switch (tenantId) {
    case "tenant_buildcorp":
      return buildCorpJournalEntries;
    default:
      return [];
  }
};

export const getBudgetsByTenant = (tenantId: string): TenantBudget[] => {
  switch (tenantId) {
    case "tenant_buildcorp":
      return buildCorpBudgets;
    default:
      return [];
  }
};

export const getAnalyticsByTenant = (
  tenantId: string,
): TenantAccountingAnalytics | undefined => {
  switch (tenantId) {
    case "tenant_buildcorp":
      return buildCorpAnalytics;
    default:
      return undefined;
  }
};

export const getCostCentersByTenant = (
  tenantId: string,
): TenantCostCenter[] => {
  switch (tenantId) {
    case "tenant_buildcorp":
      return buildCorpCostCenters;
    default:
      return [];
  }
};

export const getTenantConfiguration = (
  tenantId: string,
): TenantAccountingConfiguration | undefined => {
  const tenant = accountingTenants.find((t) => t.id === tenantId);
  return tenant?.configuration;
};

// Industry-specific chart of accounts templates
export const chartOfAccountsTemplates = {
  construction_standard: buildCorpAccounts,
  real_estate_standard: [], // Would be populated with real estate specific accounts
  technology_saas: [], // Would be populated with tech company accounts
  manufacturing_standard: [], // Would be populated with manufacturing accounts
};

// Financial ratios calculation helpers
export const calculateLiquidityRatios = (accounts: TenantAccount[]) => {
  const currentAssets = accounts
    .filter((acc) => acc.accountSubType === "current_assets")
    .reduce((sum, acc) => sum + acc.currentBalance, 0);

  const currentLiabilities = accounts
    .filter((acc) => acc.accountSubType === "current_liabilities")
    .reduce((sum, acc) => sum + Math.abs(acc.currentBalance), 0);

  const cash = accounts
    .filter((acc) => acc.isCashAccount || acc.isBankAccount)
    .reduce((sum, acc) => sum + acc.currentBalance, 0);

  return {
    currentRatio:
      currentLiabilities > 0 ? currentAssets / currentLiabilities : 0,
    quickRatio:
      currentLiabilities > 0 ? (currentAssets - 0) / currentLiabilities : 0, // Assuming no inventory for construction
    cashRatio: currentLiabilities > 0 ? cash / currentLiabilities : 0,
  };
};

export const calculateProfitabilityRatios = (
  revenue: number,
  grossProfit: number,
  netIncome: number,
  totalAssets: number,
  equity: number,
) => {
  return {
    grossProfitMargin: revenue > 0 ? (grossProfit / revenue) * 100 : 0,
    netProfitMargin: revenue > 0 ? (netIncome / revenue) * 100 : 0,
    returnOnAssets: totalAssets > 0 ? (netIncome / totalAssets) * 100 : 0,
    returnOnEquity: equity > 0 ? (netIncome / equity) * 100 : 0,
    operatingMargin: revenue > 0 ? (grossProfit / revenue) * 100 : 0, // Simplified
  };
};

// Period management helpers
export const getCurrentPeriod = (): string => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  return `${year}-${month}`;
};

export const getFiscalYearFromDate = (date: string): string => {
  const d = new Date(date);
  const year = d.getFullYear();
  const month = d.getMonth() + 1;

  // Assuming April to March fiscal year
  if (month >= 4) {
    return `${year}-${String(year + 1).slice(-2)}`;
  } else {
    return `${year - 1}-${String(year).slice(-2)}`;
  }
};

export default {
  accountingTenants,
  getAccountsByTenant,
  getJournalEntriesByTenant,
  getBudgetsByTenant,
  getAnalyticsByTenant,
  getCostCentersByTenant,
  getTenantConfiguration,
  calculateLiquidityRatios,
  calculateProfitabilityRatios,
  getCurrentPeriod,
  getFiscalYearFromDate,
};
