// Unified Human Resources Data - Consolidating HRMS + User Management + Organization

import {
  HRTenant,
  Employee,
  User,
  Role,
  Department,
  Location,
  HRAnalytics,
  HRConfiguration,
  EmployeeStatus,
  UserStatus,
  AttendanceStatus,
  LeaveStatus,
  PayrollStatus,
} from './types';

// Available HR Tenants
export const getHRTenants = (): HRTenant[] => [
  {
    id: "tenant_buildcorp",
    name: "BuildCorp Constructions",
    legalName: "BuildCorp Constructions Private Limited",
    industryType: "construction",
    configuration: {
      id: "hr_config_buildcorp",
      tenantId: "tenant_buildcorp",
      companyName: "BuildCorp Constructions",
      legalName: "BuildCorp Constructions Private Limited",
      industryType: "construction",
      hrPolicies: {
        workingHours: {
          standardHours: 8,
          flexibleHours: true,
          overtimePolicy: true,
        },
        leavePolicy: {
          annualLeave: 21,
          sickLeave: 12,
          maternityLeave: 182,
          paternityLeave: 15,
        },
        attendancePolicy: {
          graceTime: 15,
          lateMarkAfter: 30,
          halfDayAfter: 240,
        },
      },
      payrollSettings: {
        payFrequency: "monthly",
        currency: "INR",
        financialYearStart: "04-01",
        providentFund: true,
        esi: true,
        professionalTax: true,
      },
      complianceSettings: {
        pfRegistration: "DLCPM1234567000",
        esiRegistration: "12345678901234567",
        laborLicense: "LC/DL/2023/001234",
        contractorLicense: "CC/DL/2023/005678",
      },
    },
  },
  {
    id: "tenant_metro_realty",
    name: "Metro Realty Group",
    legalName: "Metro Realty Group Private Limited",
    industryType: "real_estate",
    configuration: {
      id: "hr_config_metro",
      tenantId: "tenant_metro_realty",
      companyName: "Metro Realty Group",
      legalName: "Metro Realty Group Private Limited",
      industryType: "real_estate",
      hrPolicies: {
        workingHours: {
          standardHours: 9,
          flexibleHours: false,
          overtimePolicy: true,
        },
        leavePolicy: {
          annualLeave: 18,
          sickLeave: 10,
          maternityLeave: 182,
          paternityLeave: 10,
        },
        attendancePolicy: {
          graceTime: 10,
          lateMarkAfter: 15,
          halfDayAfter: 300,
        },
      },
      payrollSettings: {
        payFrequency: "monthly",
        currency: "INR",
        financialYearStart: "04-01",
        providentFund: true,
        esi: false,
        professionalTax: true,
      },
      complianceSettings: {
        pfRegistration: "HRCPM5678901000",
        esiRegistration: "",
        laborLicense: "LC/HR/2023/002345",
        contractorLicense: "CC/HR/2023/006789",
      },
    },
  },
  {
    id: "tenant_skyline_dev",
    name: "Skyline Developers",
    legalName: "Skyline Developers Limited",
    industryType: "real_estate",
    configuration: {
      id: "hr_config_skyline",
      tenantId: "tenant_skyline_dev",
      companyName: "Skyline Developers",
      legalName: "Skyline Developers Limited",
      industryType: "real_estate",
      hrPolicies: {
        workingHours: {
          standardHours: 8.5,
          flexibleHours: true,
          overtimePolicy: false,
        },
        leavePolicy: {
          annualLeave: 24,
          sickLeave: 15,
          maternityLeave: 182,
          paternityLeave: 21,
        },
        attendancePolicy: {
          graceTime: 20,
          lateMarkAfter: 30,
          halfDayAfter: 240,
        },
      },
      payrollSettings: {
        payFrequency: "monthly",
        currency: "INR",
        financialYearStart: "01-01",
        providentFund: true,
        esi: true,
        professionalTax: true,
      },
      complianceSettings: {
        pfRegistration: "KACPM9012345000",
        esiRegistration: "90123456789012345",
        laborLicense: "LC/KA/2023/003456",
        contractorLicense: "CC/KA/2023/007890",
      },
    },
  },
];

// Employees by tenant
export const getEmployeesByTenant = (tenantId: string): Employee[] => {
  const baseEmployees: Employee[] = [
    {
      id: `emp_${tenantId.split('_')[1]}_001`,
      tenantId,
      employeeId: "EMP001",
      firstName: "Arjun",
      lastName: "Singh",
      email: "arjun.singh@company.com",
      phone: "+91-9876543210",
      dateOfBirth: "1985-03-15",
      gender: "male",
      nationality: "Indian",
      maritalStatus: "married",
      address: {
        street: "45, Sector 15",
        city: "Gurgaon",
        state: "Haryana",
        country: "India",
        zipCode: "122001",
      },
      designation: "Project Manager",
      departmentId: "dept_engineering",
      department: "Engineering",
      reportingTo: `emp_${tenantId.split('_')[1]}_002`,
      joinDate: "2020-01-15",
      employmentType: "full_time",
      workLocation: "hybrid",
      status: "active",
      salary: {
        basic: 75000,
        allowances: 25000,
        currency: "INR",
        payFrequency: "monthly",
        effectiveDate: "2024-01-01",
        ctc: 1200000,
        pfContribution: 9000,
        esiContribution: 750,
      },
      skills: ["Project Management", "AutoCAD", "Team Leadership", "Risk Assessment"],
      certifications: [
        {
          id: "cert_001",
          name: "PMP Certification",
          issuedBy: "PMI",
          issuedDate: "2022-06-15",
          expiryDate: "2025-06-15",
          credentialId: "PMP12345",
          isVerified: true,
        },
      ],
      performanceRating: 4.2,
      userId: `user_${tenantId.split('_')[1]}_001`,
      createdBy: "system",
      createdAt: "2020-01-15T00:00:00Z",
      emergencyContact: {
        name: "Priya Singh",
        relationship: "Spouse",
        phone: "+91-9876543211",
        email: "priya.singh@email.com",
      },
      bankDetails: {
        accountNumber: "1234567890123456",
        ifscCode: "HDFC0001234",
        bankName: "HDFC Bank",
        accountHolderName: "Arjun Singh",
        accountType: "savings",
      },
    },
    {
      id: `emp_${tenantId.split('_')[1]}_002`,
      tenantId,
      employeeId: "EMP002",
      firstName: "Priya",
      lastName: "Sharma",
      email: "priya.sharma@company.com",
      phone: "+91-9876543220",
      dateOfBirth: "1987-08-22",
      gender: "female",
      nationality: "Indian",
      maritalStatus: "single",
      address: {
        street: "78, MG Road",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        zipCode: "400001",
      },
      designation: "Senior Engineering Manager",
      departmentId: "dept_engineering",
      department: "Engineering",
      joinDate: "2018-03-10",
      employmentType: "full_time",
      workLocation: "office",
      status: "active",
      salary: {
        basic: 95000,
        allowances: 35000,
        currency: "INR",
        payFrequency: "monthly",
        effectiveDate: "2024-01-01",
        ctc: 1560000,
        pfContribution: 11400,
        esiContribution: 975,
      },
      skills: ["Team Management", "Strategic Planning", "Process Improvement", "Stakeholder Management"],
      certifications: [
        {
          id: "cert_002",
          name: "Six Sigma Black Belt",
          issuedBy: "ASQ",
          issuedDate: "2021-09-20",
          credentialId: "6SBB67890",
          isVerified: true,
        },
      ],
      performanceRating: 4.5,
      userId: `user_${tenantId.split('_')[1]}_002`,
      createdBy: "system",
      createdAt: "2018-03-10T00:00:00Z",
      emergencyContact: {
        name: "Raj Sharma",
        relationship: "Father",
        phone: "+91-9876543221",
      },
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "ICICI0001234",
        bankName: "ICICI Bank",
        accountHolderName: "Priya Sharma",
        accountType: "savings",
      },
    },
    {
      id: `emp_${tenantId.split('_')[1]}_003`,
      tenantId,
      employeeId: "EMP003",
      firstName: "Rohit",
      lastName: "Kumar",
      email: "rohit.kumar@company.com",
      phone: "+91-9876543230",
      dateOfBirth: "1990-12-05",
      gender: "male",
      nationality: "Indian",
      maritalStatus: "married",
      address: {
        street: "12, Tech Park",
        city: "Bangalore",
        state: "Karnataka",
        country: "India",
        zipCode: "560001",
      },
      designation: "HR Manager",
      departmentId: "dept_hr",
      department: "Human Resources",
      reportingTo: `emp_${tenantId.split('_')[1]}_002`,
      joinDate: "2021-06-01",
      employmentType: "full_time",
      workLocation: "hybrid",
      status: "active",
      salary: {
        basic: 65000,
        allowances: 20000,
        currency: "INR",
        payFrequency: "monthly",
        effectiveDate: "2024-01-01",
        ctc: 1020000,
        pfContribution: 7800,
        esiContribution: 637,
      },
      skills: ["HR Management", "Employee Relations", "Recruitment", "Performance Management"],
      certifications: [
        {
          id: "cert_003",
          name: "SHRM-CP",
          issuedBy: "SHRM",
          issuedDate: "2023-04-10",
          expiryDate: "2026-04-10",
          credentialId: "SHRM123456",
          isVerified: true,
        },
      ],
      performanceRating: 4.0,
      userId: `user_${tenantId.split('_')[1]}_003`,
      createdBy: "system",
      createdAt: "2021-06-01T00:00:00Z",
      emergencyContact: {
        name: "Kavya Kumar",
        relationship: "Spouse",
        phone: "+91-9876543231",
      },
      bankDetails: {
        accountNumber: "3456789012345678",
        ifscCode: "SBI0001234",
        bankName: "State Bank of India",
        accountHolderName: "Rohit Kumar",
        accountType: "savings",
      },
    },
  ];

  return baseEmployees;
};

// Users by tenant
export const getUsersByTenant = (tenantId: string): User[] => {
  const baseUsers: User[] = [
    {
      id: `user_${tenantId.split('_')[1]}_001`,
      tenantId,
      employeeId: `emp_${tenantId.split('_')[1]}_001`,
      username: "arjun.singh",
      email: "arjun.singh@company.com",
      phone: "+91-9876543210",
      firstName: "Arjun",
      lastName: "Singh",
      avatar: "AS",
      roleId: "role_project_manager",
      role: {
        id: "role_project_manager",
        tenantId,
        name: "Project Manager",
        description: "Manages construction projects and teams",
        permissions: [
          { id: "perm_001", module: "projects", action: "view", resource: "*", description: "View all projects", isSystem: true },
          { id: "perm_002", module: "projects", action: "create", resource: "*", description: "Create new projects", isSystem: true },
          { id: "perm_003", module: "projects", action: "edit", resource: "own", description: "Edit own projects", isSystem: true },
        ],
        isSystem: false,
        isActive: true,
        userCount: 8,
        createdBy: "system",
        createdAt: "2024-01-01T00:00:00Z",
      },
      permissions: ["projects.view", "projects.create", "projects.edit", "teams.manage", "reports.view"],
      customPermissions: [],
      status: "active",
      emailVerified: true,
      phoneVerified: true,
      mfaEnabled: true,
      lastLogin: "2024-01-25T10:30:00Z",
      lastPasswordChange: "2024-01-01T00:00:00Z",
      failedLoginAttempts: 0,
      accountLocked: false,
      sessionTimeout: 480,
      deviceTrust: true,
      createdBy: "system",
      createdAt: "2020-01-15T00:00:00Z",
    },
    {
      id: `user_${tenantId.split('_')[1]}_002`,
      tenantId,
      employeeId: `emp_${tenantId.split('_')[1]}_002`,
      username: "priya.sharma",
      email: "priya.sharma@company.com",
      phone: "+91-9876543220",
      firstName: "Priya",
      lastName: "Sharma",
      avatar: "PS",
      roleId: "role_engineering_manager",
      role: {
        id: "role_engineering_manager",
        tenantId,
        name: "Engineering Manager",
        description: "Senior engineering management role",
        permissions: [
          { id: "perm_004", module: "engineering", action: "view", resource: "*", description: "View all engineering data", isSystem: true },
          { id: "perm_005", module: "engineering", action: "manage", resource: "*", description: "Manage engineering operations", isSystem: true },
          { id: "perm_006", module: "hr", action: "view", resource: "team", description: "View team HR data", isSystem: true },
        ],
        isSystem: false,
        isActive: true,
        userCount: 3,
        createdBy: "system",
        createdAt: "2024-01-01T00:00:00Z",
      },
      permissions: ["engineering.view", "engineering.manage", "hr.view", "reports.generate"],
      customPermissions: [],
      status: "active",
      emailVerified: true,
      phoneVerified: true,
      mfaEnabled: true,
      lastLogin: "2024-01-25T09:15:00Z",
      lastPasswordChange: "2024-01-01T00:00:00Z",
      failedLoginAttempts: 0,
      accountLocked: false,
      sessionTimeout: 600,
      deviceTrust: true,
      createdBy: "system",
      createdAt: "2018-03-10T00:00:00Z",
    },
    {
      id: `user_${tenantId.split('_')[1]}_003`,
      tenantId,
      employeeId: `emp_${tenantId.split('_')[1]}_003`,
      username: "rohit.kumar",
      email: "rohit.kumar@company.com",
      phone: "+91-9876543230",
      firstName: "Rohit",
      lastName: "Kumar",
      avatar: "RK",
      roleId: "role_hr_manager",
      role: {
        id: "role_hr_manager",
        tenantId,
        name: "HR Manager",
        description: "Human resources management role",
        permissions: [
          { id: "perm_007", module: "hr", action: "view", resource: "*", description: "View all HR data", isSystem: true },
          { id: "perm_008", module: "hr", action: "manage", resource: "*", description: "Manage HR operations", isSystem: true },
          { id: "perm_009", module: "payroll", action: "process", resource: "*", description: "Process payroll", isSystem: true },
        ],
        isSystem: false,
        isActive: true,
        userCount: 5,
        createdBy: "system",
        createdAt: "2024-01-01T00:00:00Z",
      },
      permissions: ["hr.view", "hr.manage", "payroll.process", "employee.create", "employee.edit"],
      customPermissions: [],
      status: "active",
      emailVerified: true,
      phoneVerified: false,
      mfaEnabled: false,
      lastLogin: "2024-01-25T08:45:00Z",
      lastPasswordChange: "2024-01-01T00:00:00Z",
      failedLoginAttempts: 0,
      accountLocked: false,
      sessionTimeout: 480,
      deviceTrust: true,
      createdBy: "system",
      createdAt: "2021-06-01T00:00:00Z",
    },
  ];

  return baseUsers;
};

// Departments by tenant
export const getDepartmentsByTenant = (tenantId: string): Department[] => [
  {
    id: "dept_engineering",
    tenantId,
    name: "Engineering",
    code: "ENG",
    description: "Engineering and technical development",
    level: 1,
    headOfDepartment: `emp_${tenantId.split('_')[1]}_002`,
    location: "Head Office",
    budget: 5000000,
    employeeCount: 25,
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dept_hr",
    tenantId,
    name: "Human Resources",
    code: "HR",
    description: "Human resources and administration",
    level: 1,
    headOfDepartment: `emp_${tenantId.split('_')[1]}_003`,
    location: "Head Office",
    budget: 2000000,
    employeeCount: 8,
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dept_finance",
    tenantId,
    name: "Finance & Accounting",
    code: "FIN",
    description: "Financial management and accounting",
    level: 1,
    location: "Head Office",
    budget: 1500000,
    employeeCount: 12,
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "dept_operations",
    tenantId,
    name: "Operations",
    code: "OPS",
    description: "Business operations and management",
    level: 1,
    location: "Multiple Locations",
    budget: 3000000,
    employeeCount: 35,
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

// Locations by tenant
export const getLocationsByTenant = (tenantId: string): Location[] => [
  {
    id: "loc_head_office",
    tenantId,
    name: "Corporate Headquarters",
    code: "HQ",
    address: {
      street: "123 Business District",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      zipCode: "400001",
    },
    timezone: "Asia/Kolkata",
    isHeadOffice: true,
    capacity: 500,
    employeeCount: 342,
    facilities: ["Conference Rooms", "Cafeteria", "Gym", "Parking", "Medical Room"],
    contactPerson: "Priya Sharma",
    phone: "+91-22-12345678",
    email: "mumbai@company.com",
    coordinates: { lat: 19.076, lng: 72.8777 },
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "loc_regional_north",
    tenantId,
    name: "Delhi NCR Office",
    code: "DEL",
    address: {
      street: "456 Cyber City",
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
      zipCode: "122002",
    },
    timezone: "Asia/Kolkata",
    isHeadOffice: false,
    capacity: 200,
    employeeCount: 156,
    facilities: ["Conference Rooms", "Cafeteria", "Parking"],
    contactPerson: "Rahul Gupta",
    phone: "+91-124-9876543",
    email: "delhi@company.com",
    coordinates: { lat: 28.4595, lng: 77.0266 },
    isActive: true,
    createdBy: "system",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

// HR Analytics
export const getHRAnalyticsByTenant = (
  tenantId: string, 
  timeRange: string = "current_month"
): HRAnalytics => {
  // Mock analytics data - in real app, this would be calculated from actual data
  return {
    tenantId,
    period: timeRange,
    employeeMetrics: {
      totalEmployees: 80,
      activeEmployees: 78,
      newJoinees: 5,
      departures: 2,
      departmentWiseCount: {
        "Engineering": 25,
        "Human Resources": 8,
        "Finance & Accounting": 12,
        "Operations": 35,
      },
      locationWiseCount: {
        "Corporate Headquarters": 50,
        "Delhi NCR Office": 25,
        "Other Locations": 5,
      },
      averageAge: 32.5,
      genderDistribution: {
        "male": 48,
        "female": 30,
        "other": 2,
      },
    },
    attendanceMetrics: {
      averageAttendance: 94.5,
      punctualityRate: 87.2,
      absenteeismRate: 5.5,
      overtimeHours: 240,
      workFromHomeUtilization: 35.8,
    },
    leaveMetrics: {
      totalLeavesTaken: 156,
      averageLeavesPerEmployee: 1.95,
      leaveTypeDistribution: {
        "annual": 89,
        "sick": 35,
        "casual": 25,
        "emergency": 7,
      },
      pendingLeaveRequests: 12,
      leaveUtilizationRate: 68.5,
    },
    performanceMetrics: {
      averageRating: 4.1,
      ratingDistribution: {
        "5": 18,
        "4": 32,
        "3": 22,
        "2": 6,
        "1": 2,
      },
      completedReviews: 72,
      pendingReviews: 8,
      topPerformers: ["Priya Sharma", "Arjun Singh", "Rohit Kumar", "Anita Desai", "Vikram Patel"],
    },
    recruitmentMetrics: {
      totalOpenings: 15,
      totalApplications: 280,
      conversionRate: 12.5,
      averageTimeToHire: 28,
      sourceWiseApplications: {
        "Job Portals": 145,
        "Employee Referrals": 89,
        "Direct Applications": 32,
        "Campus Hiring": 14,
      },
    },
    turnoverMetrics: {
      turnoverRate: 8.5,
      voluntaryTurnover: 6.2,
      involuntaryTurnover: 2.3,
      retentionRate: 91.5,
      averageTenure: 3.8,
      exitReasons: {
        "Better Opportunity": 45,
        "Career Growth": 25,
        "Personal Reasons": 15,
        "Relocation": 10,
        "Other": 5,
      },
    },
  };
};

// Unified HR Summary
export const getUnifiedHRSummary = (tenantId: string) => {
  const employees = getEmployeesByTenant(tenantId);
  const users = getUsersByTenant(tenantId);
  const departments = getDepartmentsByTenant(tenantId);

  return {
    tenantId,
    summary: {
      totalEmployees: employees.length,
      totalUsers: users.length,
      totalDepartments: departments.length,
      activeEmployees: employees.filter(e => e.status === 'active').length,
      pendingApprovals: 8,
    },
    recentActivities: [
      {
        id: "activity_001",
        type: "employee" as const,
        description: "New employee onboarding completed",
        user: "Rohit Kumar",
        timestamp: "2024-01-25T10:30:00Z",
        status: "completed" as const,
      },
      {
        id: "activity_002",
        type: "user" as const,
        description: "User permissions updated",
        user: "System Admin",
        timestamp: "2024-01-25T09:15:00Z",
        status: "completed" as const,
      },
      {
        id: "activity_003",
        type: "attendance" as const,
        description: "Monthly attendance report generated",
        user: "HR System",
        timestamp: "2024-01-25T08:00:00Z",
        status: "completed" as const,
      },
      {
        id: "activity_004",
        type: "payroll" as const,
        description: "Payroll processing in progress",
        user: "Rohit Kumar",
        timestamp: "2024-01-25T07:30:00Z",
        status: "pending" as const,
      },
      {
        id: "activity_005",
        type: "performance" as const,
        description: "Performance review cycle initiated",
        user: "Priya Sharma",
        timestamp: "2024-01-24T16:45:00Z",
        status: "pending" as const,
      },
    ],
  };
};

// Helper functions
export const formatCurrency = (amount: number, currency: string = 'INR'): string => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatPercentage = (value: number): string => {
  return new Intl.NumberFormat('en-IN', {
    style: 'percent',
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  }).format(value / 100);
};

export const formatDate = (date: string): string => {
  return new Date(date).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
};

export const getEmployeeFullName = (employee: Employee): string => {
  return `${employee.firstName} ${employee.lastName}`;
};

export const getEmployeeDisplayId = (employee: Employee): string => {
  return `${employee.employeeId} - ${getEmployeeFullName(employee)}`;
};
