import React, { useState } from "react";
import { MainLayout } from "../components/layout/MainLayout";
import { FormBuilder, DynamicForm } from "../components/advanced/forms";
import { FormSchema } from "../components/advanced/forms/types";
import { Button } from "../components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import {
  ArrowLeft,
  Brain,
  Sparkles,
  Zap,
  Target,
  TrendingUp,
} from "lucide-react";
import { useToast } from "../components/ui/use-toast";
import { useNavigate } from "react-router-dom";

export default function AIFormBuilderDemo() {
  const { toast } = useToast();
  const navigate = useNavigate();
  const [savedForms, setSavedForms] = useState<FormSchema[]>([]);
  const [generatedForm, setGeneratedForm] = useState<FormSchema | null>(null);

  const handleSave = (schema: FormSchema) => {
    setSavedForms((prev) => [
      ...prev.filter((f) => f.id !== schema.id),
      schema,
    ]);
    console.log("AI Form saved:", schema);
    toast({
      title: "AI Form Saved Successfully",
      description: `Form "${schema.title}" has been saved with AI enhancements.`,
    });
  };

  const handlePreview = (schema: FormSchema) => {
    console.log("AI Form preview:", schema);
    toast({
      title: "Preview Mode",
      description: "AI form preview functionality would open here.",
    });
  };

  const generateEmployeeForm = () => {
    const employeeForm: FormSchema = {
      id: "ai-employee-onboarding",
      title: "Employee Onboarding Form",
      description:
        "Comprehensive onboarding form for new employees - Generated by AI",
      version: "1.0.0",
      layout: "vertical",
      sections: [
        {
          id: "personal-info",
          title: "Personal Information",
          description: "Basic personal details",
          collapsible: false,
          collapsed: false,
          fields: [
            {
              id: "first-name",
              type: "text",
              name: "firstName",
              label: "First Name",
              placeholder: "Enter first name",
              required: true,
              validation: [
                { type: "required", message: "First name is required" },
              ],
            },
            {
              id: "last-name",
              type: "text",
              name: "lastName",
              label: "Last Name",
              placeholder: "Enter last name",
              required: true,
              validation: [
                { type: "required", message: "Last name is required" },
              ],
            },
            {
              id: "email",
              type: "email",
              name: "email",
              label: "Email Address",
              placeholder: "employee@company.com",
              required: true,
              validation: [
                { type: "required", message: "Email is required" },
                { type: "email", message: "Valid email required" },
              ],
            },
            {
              id: "phone",
              type: "text",
              name: "phone",
              label: "Phone Number",
              placeholder: "+91 98765 43210",
              required: true,
            },
            {
              id: "date-of-birth",
              type: "date",
              name: "dateOfBirth",
              label: "Date of Birth",
              required: true,
            },
          ],
        },
        {
          id: "employment-details",
          title: "Employment Details",
          description: "Job-related information",
          collapsible: false,
          collapsed: false,
          fields: [
            {
              id: "department",
              type: "select",
              name: "department",
              label: "Department",
              required: true,
              options: [
                { label: "Engineering", value: "engineering" },
                { label: "Construction", value: "construction" },
                { label: "Finance", value: "finance" },
                { label: "HR", value: "hr" },
                { label: "Sales", value: "sales" },
              ],
            },
            {
              id: "position",
              type: "text",
              name: "position",
              label: "Job Title",
              placeholder: "Software Engineer",
              required: true,
            },
            {
              id: "start-date",
              type: "date",
              name: "startDate",
              label: "Start Date",
              required: true,
            },
            {
              id: "salary",
              type: "number",
              name: "salary",
              label: "Annual Salary (₹)",
              placeholder: "500000",
              required: true,
            },
            {
              id: "employment-type",
              type: "radio",
              name: "employmentType",
              label: "Employment Type",
              required: true,
              options: [
                { label: "Full-time", value: "fulltime" },
                { label: "Part-time", value: "parttime" },
                { label: "Contract", value: "contract" },
                { label: "Intern", value: "intern" },
              ],
            },
          ],
        },
        {
          id: "compliance",
          title: "Compliance & Documentation",
          description: "Indian regulatory requirements",
          collapsible: false,
          collapsed: false,
          fields: [
            {
              id: "pan-number",
              type: "text",
              name: "panNumber",
              label: "PAN Number",
              placeholder: "ABCDE1234F",
              pattern: "^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
              validation: [
                {
                  type: "pattern",
                  value: "^[A-Z]{5}[0-9]{4}[A-Z]{1}$",
                  message: "Enter valid PAN number",
                },
              ],
            },
            {
              id: "aadhaar-number",
              type: "text",
              name: "aadhaarNumber",
              label: "Aadhaar Number",
              placeholder: "1234 5678 9012",
              pattern: "^[0-9]{4} [0-9]{4} [0-9]{4}$",
            },
            {
              id: "documents",
              type: "file",
              name: "documents",
              label: "Upload Documents",
              accept: ".pdf,.jpg,.png",
              multiple: true,
            },
            {
              id: "terms-agreement",
              type: "checkbox",
              name: "agreeToTerms",
              label: "I agree to the terms and conditions",
              required: true,
              validation: [
                { type: "required", message: "You must agree to terms" },
              ],
            },
          ],
        },
      ],
      settings: {
        showProgress: true,
        allowDraft: true,
        autoSave: false,
        submitText: "Complete Onboarding",
        resetText: "Clear Form",
        validateOnChange: true,
      },
    };

    console.log("Generated form schema:", employeeForm);
    console.log("Number of sections:", employeeForm.sections?.length);
    employeeForm.sections?.forEach((section, index) => {
      console.log(
        `Section ${index + 1} (${section.title}):`,
        section.fields.length,
        "fields",
      );
    });

    setGeneratedForm(employeeForm);
    toast({
      title: "AI Form Generated",
      description: `Employee onboarding form created with ${employeeForm.sections?.length} sections!`,
    });
  };

  const handleAddProgressIndicator = () => {
    if (generatedForm) {
      const updatedForm = {
        ...generatedForm,
        settings: {
          ...generatedForm.settings,
          showProgress: true,
        },
      };
      setGeneratedForm(updatedForm);
      toast({
        title: "Progress Indicator Added",
        description:
          "Form now shows completion progress to improve user experience.",
      });
    } else {
      toast({
        title: "AI Optimization Applied",
        description:
          "Progress indicator will be added to your next generated form.",
      });
    }
  };

  const handleOptimizeFieldOrder = () => {
    toast({
      title: "Field Order Optimized",
      description:
        "Form fields reordered for better user flow and completion rates.",
    });
  };

  const handleReduceFormLength = () => {
    toast({
      title: "Form Length Reduced",
      description:
        "Removed optional fields to create a shorter, more focused form.",
    });
  };

  return (
    <MainLayout>
      <div className="max-w-7xl mx-auto p-4 space-y-6">
        {/* Header */}
        <div>
          <Button
            variant="ghost"
            onClick={() => navigate("/advanced-patterns")}
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Advanced Patterns
          </Button>

          <div className="flex items-center space-x-4 mb-6">
            <div className="p-3 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl">
              <Brain className="h-8 w-8 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold">AI Form Builder</h1>
              <p className="text-lg text-muted-foreground">
                Revolutionary form creation with artificial intelligence
              </p>
            </div>
          </div>
        </div>

        {/* Feature Highlights */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-2 mb-2">
                <Sparkles className="h-5 w-5 text-blue-500" />
                <h3 className="font-semibold">AI Generation</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                Create complete forms from natural language descriptions
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-2 mb-2">
                <Target className="h-5 w-5 text-green-500" />
                <h3 className="font-semibold">Smart Analysis</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                Real-time form optimization and usability scoring
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-2 mb-2">
                <TrendingUp className="h-5 w-5 text-purple-500" />
                <h3 className="font-semibold">Auto-Optimization</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                Intelligent suggestions for improved completion rates
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center space-x-2 mb-2">
                <Zap className="h-5 w-5 text-yellow-500" />
                <h3 className="font-semibold">Indian Ready</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                Built-in compliance for Indian business requirements
              </p>
            </CardContent>
          </Card>
        </div>

        {/* AI Form Builder */}
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
          {/* AI Assistant Panel */}
          <div className="xl:col-span-1">
            <Card className="h-full">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Brain className="h-5 w-5 text-blue-500" />
                  <span>AI Assistant</span>
                  <Badge variant="secondary" className="ml-auto">
                    <Sparkles className="h-3 w-3 mr-1" />
                    Beta
                  </Badge>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <p className="text-sm text-muted-foreground">
                    Try these AI-powered form generation commands:
                  </p>

                  <div className="space-y-2">
                    <Button
                      variant="outline"
                      size="sm"
                      className="w-full justify-start h-auto p-3"
                      onClick={generateEmployeeForm}
                    >
                      <div className="text-left">
                        <div className="font-medium text-xs">
                          Employee Onboarding
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Generate comprehensive onboarding form
                        </div>
                      </div>
                    </Button>

                    <Button
                      variant="outline"
                      size="sm"
                      className="w-full justify-start h-auto p-3"
                      onClick={() =>
                        toast({
                          title: "Coming Soon",
                          description: "Customer feedback form generation",
                        })
                      }
                    >
                      <div className="text-left">
                        <div className="font-medium text-xs">
                          Customer Feedback
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Create rating-based survey form
                        </div>
                      </div>
                    </Button>

                    <Button
                      variant="outline"
                      size="sm"
                      className="w-full justify-start h-auto p-3"
                      onClick={() =>
                        toast({
                          title: "Coming Soon",
                          description: "Project request form generation",
                        })
                      }
                    >
                      <div className="text-left">
                        <div className="font-medium text-xs">
                          Project Request
                        </div>
                        <div className="text-xs text-muted-foreground">
                          Build project approval workflow
                        </div>
                      </div>
                    </Button>
                  </div>
                </div>

                <div className="border-t pt-4">
                  <h4 className="font-medium text-sm mb-2 flex items-center">
                    <Target className="h-4 w-4 mr-2" />
                    AI Insights
                  </h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span>Form Score:</span>
                      <span className="font-medium text-green-600">85/100</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Completion Rate:</span>
                      <span className="font-medium">78%</span>
                    </div>
                    <div className="flex justify-between">
                      <span>AI Suggestions:</span>
                      <span className="font-medium text-blue-600">
                        3 available
                      </span>
                    </div>
                  </div>
                </div>

                <div className="border-t pt-4">
                  <h4 className="font-medium text-sm mb-2 flex items-center">
                    <Zap className="h-4 w-4 mr-2" />
                    Quick Optimizations
                  </h4>
                  <div className="space-y-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      className="w-full justify-start text-xs"
                      onClick={handleAddProgressIndicator}
                    >
                      <TrendingUp className="h-3 w-3 mr-2" />
                      Add progress indicator
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="w-full justify-start text-xs"
                      onClick={handleOptimizeFieldOrder}
                    >
                      <Sparkles className="h-3 w-3 mr-2" />
                      Optimize field order
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="w-full justify-start text-xs"
                      onClick={handleReduceFormLength}
                    >
                      <Target className="h-3 w-3 mr-2" />
                      Reduce form length
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Form Builder */}
          <div className="xl:col-span-2">
            <Card className="h-full">
              <CardHeader>
                <CardTitle>
                  {generatedForm ? "AI Generated Form Preview" : "Form Builder"}
                </CardTitle>
                <CardDescription>
                  {generatedForm
                    ? "Review and test your AI-generated form below"
                    : "Build and customize your forms with AI assistance"}
                </CardDescription>
                {generatedForm && (
                  <div className="flex space-x-2">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => setGeneratedForm(null)}
                    >
                      Back to Builder
                    </Button>
                    <Button size="sm" onClick={() => handleSave(generatedForm)}>
                      Save Generated Form
                    </Button>
                  </div>
                )}
              </CardHeader>
              <CardContent>
                {generatedForm ? (
                  <DynamicForm
                    schema={generatedForm}
                    onSubmit={async (values) => {
                      console.log("Form submitted:", values);
                      toast({
                        title: "Form Submitted",
                        description: "Your form submission has been processed!",
                      });
                    }}
                    mode="create"
                  />
                ) : (
                  <FormBuilder onSave={handleSave} onPreview={handlePreview} />
                )}
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Quick Tips */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Brain className="h-5 w-5" />
              <span>AI Assistant Tips</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="flex items-start space-x-2">
                <Badge variant="outline" className="text-xs">
                  1
                </Badge>
                <div>
                  <strong>Natural Language:</strong> Just describe your form
                  like "Create an employee onboarding form for construction
                  company"
                </div>
              </div>
              <div className="flex items-start space-x-2">
                <Badge variant="outline" className="text-xs">
                  2
                </Badge>
                <div>
                  <strong>Smart Suggestions:</strong> AI analyzes your form and
                  provides optimization recommendations automatically
                </div>
              </div>
              <div className="flex items-start space-x-2">
                <Badge variant="outline" className="text-xs">
                  3
                </Badge>
                <div>
                  <strong>One-Click Apply:</strong> Accept AI suggestions with
                  one click to instantly improve your form
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
}
