import {
  Integration,
  MarketingCampaign,
  CRMLead,
  Document,
  SyncLog,
} from "./types";

export const mockIntegrations: Integration[] = [
  // Marketing Integrations
  {
    id: "mailchimp-1",
    name: "Mailchimp",
    category: "marketing",
    provider: "Mailchimp",
    status: "connected",
    description: "Email marketing automation and audience management",
    icon: "📧",
    features: [
      "Email Campaigns",
      "Audience Segmentation",
      "Analytics",
      "A/B Testing",
    ],
    config: {
      apiKey: "mc_*********************",
      region: "us1",
      syncFrequency: "hourly",
      enabledFeatures: ["campaigns", "lists", "automation"],
    },
    lastSync: "2024-01-15T10:30:00Z",
    usage: {
      apiCalls: 1250,
      apiLimit: 10000,
      dataTransferred: 45.2,
      lastActivity: "2024-01-15T10:30:00Z",
      errors: 0,
    },
  },
  {
    id: "interakt-marketing",
    name: "Interakt",
    category: "marketing",
    provider: "Interakt",
    status: "connected",
    description: "WhatsApp Business API and marketing automation",
    icon: "💬",
    features: [
      "WhatsApp Marketing",
      "Chatbots",
      "Broadcast Messages",
      "Analytics",
    ],
    config: {
      apiKey: "int_*********************",
      baseUrl: "https://api.interakt.ai",
      syncFrequency: "realtime",
      enabledFeatures: ["whatsapp", "chatbot", "broadcast"],
    },
    lastSync: "2024-01-15T11:15:00Z",
    usage: {
      apiCalls: 3420,
      apiLimit: 50000,
      dataTransferred: 125.8,
      lastActivity: "2024-01-15T11:15:00Z",
      errors: 2,
    },
  },
  {
    id: "zoho-campaigns",
    name: "Zoho Campaigns",
    category: "marketing",
    provider: "Zoho",
    status: "connected",
    description: "Email marketing and automation platform",
    icon: "📨",
    features: ["Email Marketing", "Drip Campaigns", "Landing Pages", "Reports"],
    config: {
      apiKey: "zoho_*********************",
      region: "com",
      syncFrequency: "daily",
      enabledFeatures: ["campaigns", "automation", "reports"],
    },
    lastSync: "2024-01-15T09:00:00Z",
    usage: {
      apiCalls: 890,
      apiLimit: 5000,
      dataTransferred: 32.1,
      lastActivity: "2024-01-15T09:00:00Z",
      errors: 0,
    },
  },

  // Sales Automation
  {
    id: "salesforce-1",
    name: "Salesforce",
    category: "sales",
    provider: "Salesforce",
    status: "connected",
    description: "CRM and sales automation platform",
    icon: "☁️",
    features: [
      "Lead Management",
      "Opportunity Tracking",
      "Contact Sync",
      "Reports",
    ],
    config: {
      apiKey: "sf_*********************",
      baseUrl: "https://buildpro.salesforce.com",
      syncFrequency: "hourly",
      enabledFeatures: ["leads", "opportunities", "contacts", "accounts"],
    },
    lastSync: "2024-01-15T11:00:00Z",
    usage: {
      apiCalls: 2100,
      apiLimit: 15000,
      dataTransferred: 78.5,
      lastActivity: "2024-01-15T11:00:00Z",
      errors: 1,
    },
  },
  {
    id: "pipedrive-1",
    name: "Pipedrive",
    category: "sales",
    provider: "Pipedrive",
    status: "connected",
    description: "Sales pipeline management and CRM",
    icon: "🔄",
    features: [
      "Pipeline Management",
      "Deal Tracking",
      "Activity Sync",
      "Analytics",
    ],
    config: {
      apiKey: "pd_*********************",
      baseUrl: "https://buildpro.pipedrive.com",
      syncFrequency: "realtime",
      enabledFeatures: ["deals", "activities", "contacts", "pipelines"],
    },
    lastSync: "2024-01-15T11:20:00Z",
    usage: {
      apiCalls: 1890,
      apiLimit: 20000,
      dataTransferred: 67.3,
      lastActivity: "2024-01-15T11:20:00Z",
      errors: 0,
    },
  },

  // ERP Systems
  {
    id: "sap-erp",
    name: "SAP ERP",
    category: "erp",
    provider: "SAP",
    status: "connected",
    description: "Enterprise resource planning and business processes",
    icon: "🏢",
    features: [
      "Customer Sync",
      "Order Management",
      "Inventory",
      "Financial Data",
    ],
    config: {
      apiKey: "sap_*********************",
      baseUrl: "https://buildpro.sap.com",
      syncFrequency: "daily",
      enabledFeatures: ["customers", "orders", "inventory", "financials"],
    },
    lastSync: "2024-01-15T08:00:00Z",
    usage: {
      apiCalls: 450,
      apiLimit: 2000,
      dataTransferred: 234.7,
      lastActivity: "2024-01-15T08:00:00Z",
      errors: 0,
    },
  },
  {
    id: "oracle-erp",
    name: "Oracle ERP Cloud",
    category: "erp",
    provider: "Oracle",
    status: "disconnected",
    description: "Cloud-based enterprise resource planning",
    icon: "🔶",
    features: [
      "Financial Management",
      "Project Management",
      "Supply Chain",
      "HCM",
    ],
    config: {
      syncFrequency: "daily",
      enabledFeatures: [],
    },
    usage: {
      apiCalls: 0,
      apiLimit: 5000,
      dataTransferred: 0,
      lastActivity: "",
      errors: 0,
    },
  },

  // Communication
  {
    id: "msg91-sms",
    name: "MSG91",
    category: "communication",
    provider: "MSG91",
    status: "connected",
    description: "SMS and voice communication platform",
    icon: "📱",
    features: ["SMS Campaigns", "OTP Services", "Voice Calls", "Analytics"],
    config: {
      apiKey: "msg91_*********************",
      baseUrl: "https://api.msg91.com",
      syncFrequency: "realtime",
      enabledFeatures: ["sms", "otp", "voice"],
    },
    lastSync: "2024-01-15T11:25:00Z",
    usage: {
      apiCalls: 5670,
      apiLimit: 100000,
      dataTransferred: 23.4,
      lastActivity: "2024-01-15T11:25:00Z",
      errors: 3,
    },
  },
  {
    id: "twilio-comm",
    name: "Twilio",
    category: "communication",
    provider: "Twilio",
    status: "connected",
    description: "Cloud communications platform",
    icon: "☁️",
    features: ["SMS", "Voice Calls", "WhatsApp API", "Video Calls"],
    config: {
      apiKey: "twilio_*********************",
      apiSecret: "tw_*********************",
      baseUrl: "https://api.twilio.com",
      syncFrequency: "realtime",
      enabledFeatures: ["sms", "voice", "whatsapp"],
    },
    lastSync: "2024-01-15T11:30:00Z",
    usage: {
      apiCalls: 3240,
      apiLimit: 75000,
      dataTransferred: 87.2,
      lastActivity: "2024-01-15T11:30:00Z",
      errors: 1,
    },
  },
  {
    id: "gupshup-wa",
    name: "Gupshup",
    category: "communication",
    provider: "Gupshup",
    status: "connected",
    description: "Conversational messaging platform",
    icon: "💬",
    features: ["WhatsApp Business", "Chatbots", "Rich Messaging", "Analytics"],
    config: {
      apiKey: "gupshup_*********************",
      baseUrl: "https://api.gupshup.io",
      syncFrequency: "realtime",
      enabledFeatures: ["whatsapp", "chatbot", "templates"],
    },
    lastSync: "2024-01-15T11:35:00Z",
    usage: {
      apiCalls: 4560,
      apiLimit: 60000,
      dataTransferred: 156.8,
      lastActivity: "2024-01-15T11:35:00Z",
      errors: 2,
    },
  },

  // Maps & Location
  {
    id: "google-maps",
    name: "Google Maps",
    category: "maps",
    provider: "Google",
    status: "connected",
    description: "Maps, geocoding, and location services",
    icon: "🗺️",
    features: ["Geocoding", "Places API", "Directions", "Street View"],
    config: {
      apiKey: "gmap_*********************",
      baseUrl: "https://maps.googleapis.com",
      syncFrequency: "realtime",
      enabledFeatures: ["geocoding", "places", "directions"],
    },
    lastSync: "2024-01-15T11:40:00Z",
    usage: {
      apiCalls: 1230,
      apiLimit: 25000,
      dataTransferred: 45.7,
      lastActivity: "2024-01-15T11:40:00Z",
      errors: 0,
    },
  },

  // Digital Signature
  {
    id: "docusign-1",
    name: "DocuSign",
    category: "signature",
    provider: "DocuSign",
    status: "connected",
    description: "Digital signature and document management",
    icon: "✍️",
    features: [
      "E-Signatures",
      "Document Templates",
      "Workflow Automation",
      "Audit Trail",
    ],
    config: {
      apiKey: "docusign_*********************",
      baseUrl: "https://demo.docusign.net",
      syncFrequency: "realtime",
      enabledFeatures: ["signatures", "templates", "webhooks"],
    },
    lastSync: "2024-01-15T11:45:00Z",
    usage: {
      apiCalls: 234,
      apiLimit: 5000,
      dataTransferred: 12.3,
      lastActivity: "2024-01-15T11:45:00Z",
      errors: 0,
    },
  },
  {
    id: "zoho-sign",
    name: "Zoho Sign",
    category: "signature",
    provider: "Zoho",
    status: "connected",
    description: "Digital signature solution",
    icon: "📝",
    features: [
      "Digital Signatures",
      "Document Management",
      "Templates",
      "Mobile Signing",
    ],
    config: {
      apiKey: "zsign_*********************",
      baseUrl: "https://sign.zoho.com",
      syncFrequency: "realtime",
      enabledFeatures: ["signatures", "templates", "mobile"],
    },
    lastSync: "2024-01-15T11:50:00Z",
    usage: {
      apiCalls: 156,
      apiLimit: 3000,
      dataTransferred: 8.9,
      lastActivity: "2024-01-15T11:50:00Z",
      errors: 0,
    },
  },

  // Cloud Storage
  {
    id: "google-drive",
    name: "Google Drive",
    category: "storage",
    provider: "Google",
    status: "connected",
    description: "Cloud storage and document collaboration",
    icon: "📁",
    features: [
      "File Storage",
      "Document Sharing",
      "Collaboration",
      "Version Control",
    ],
    config: {
      apiKey: "gdrive_*********************",
      baseUrl: "https://www.googleapis.com/drive",
      syncFrequency: "realtime",
      enabledFeatures: ["storage", "sharing", "collaboration"],
    },
    lastSync: "2024-01-15T11:55:00Z",
    usage: {
      apiCalls: 2340,
      apiLimit: 30000,
      dataTransferred: 234.5,
      lastActivity: "2024-01-15T11:55:00Z",
      errors: 1,
    },
  },
  {
    id: "dropbox-1",
    name: "Dropbox",
    category: "storage",
    provider: "Dropbox",
    status: "connected",
    description: "Cloud storage and file synchronization",
    icon: "📦",
    features: [
      "File Storage",
      "File Sharing",
      "Team Folders",
      "Version History",
    ],
    config: {
      apiKey: "dropbox_*********************",
      baseUrl: "https://api.dropboxapi.com",
      syncFrequency: "hourly",
      enabledFeatures: ["storage", "sharing", "sync"],
    },
    lastSync: "2024-01-15T11:00:00Z",
    usage: {
      apiCalls: 1890,
      apiLimit: 20000,
      dataTransferred: 189.3,
      lastActivity: "2024-01-15T11:00:00Z",
      errors: 0,
    },
  },
];

export const mockCampaigns: MarketingCampaign[] = [
  {
    id: "camp-1",
    name: "New Project Launch - Email Campaign",
    type: "email",
    status: "active",
    integration: "mailchimp-1",
    audience: 2500,
    sent: 2500,
    opened: 1200,
    clicked: 340,
    createdAt: "2024-01-14T09:00:00Z",
    scheduledAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "camp-2",
    name: "Site Visit Reminders - WhatsApp",
    type: "whatsapp",
    status: "completed",
    integration: "interakt-marketing",
    audience: 150,
    sent: 150,
    opened: 142,
    clicked: 89,
    createdAt: "2024-01-13T14:30:00Z",
  },
  {
    id: "camp-3",
    name: "Safety Training Notifications - SMS",
    type: "sms",
    status: "active",
    integration: "msg91-sms",
    audience: 800,
    sent: 756,
    opened: 720,
    clicked: 0,
    createdAt: "2024-01-15T08:00:00Z",
  },
];

export const mockLeads: CRMLead[] = [
  {
    id: "lead-1",
    name: "Rajesh Sharma",
    email: "rajesh.sharma@example.com",
    phone: "+91 98765 43210",
    source: "Salesforce",
    status: "qualified",
    location: {
      address: "Sector 14, Gurgaon, Haryana",
      coordinates: { lat: 28.4595, lng: 77.0266 },
    },
    assignedTo: "John Smith",
    lastActivity: "2024-01-15T10:30:00Z",
    value: 2500000,
  },
  {
    id: "lead-2",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    phone: "+91 87654 32109",
    source: "Pipedrive",
    status: "new",
    location: {
      address: "Bandra West, Mumbai, Maharashtra",
      coordinates: { lat: 19.0596, lng: 72.8295 },
    },
    lastActivity: "2024-01-15T09:15:00Z",
    value: 1800000,
  },
  {
    id: "lead-3",
    name: "Tech Innovations Pvt Ltd",
    email: "contact@techinnovations.com",
    phone: "+91 76543 21098",
    source: "Google Maps",
    status: "contacted",
    location: {
      address: "Electronic City, Bangalore, Karnataka",
      coordinates: { lat: 12.8456, lng: 77.6603 },
    },
    assignedTo: "Sarah Wilson",
    lastActivity: "2024-01-15T11:45:00Z",
    value: 5200000,
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc-1",
    name: "Construction Agreement - Skyline Tower",
    type: "contract",
    status: "sent",
    signatureProvider: "docusign-1",
    storageProvider: "google-drive",
    url: "https://drive.google.com/file/d/abc123",
    recipients: [
      {
        email: "client@example.com",
        name: "Client Company",
        status: "pending",
      },
      {
        email: "contractor@buildpro.com",
        name: "BuildPro Contractor",
        status: "signed",
        signedAt: "2024-01-14T15:30:00Z",
      },
    ],
    createdAt: "2024-01-14T10:00:00Z",
    updatedAt: "2024-01-14T15:30:00Z",
  },
  {
    id: "doc-2",
    name: "Project Proposal - Green Valley Homes",
    type: "proposal",
    status: "completed",
    signatureProvider: "zoho-sign",
    storageProvider: "dropbox-1",
    url: "https://dropbox.com/s/xyz789",
    recipients: [
      {
        email: "investor@greenvalley.com",
        name: "Green Valley Investor",
        status: "signed",
        signedAt: "2024-01-13T11:20:00Z",
      },
    ],
    createdAt: "2024-01-12T09:00:00Z",
    updatedAt: "2024-01-13T11:20:00Z",
  },
  {
    id: "doc-3",
    name: "Material Supply Invoice - Q4 2024",
    type: "invoice",
    status: "viewed",
    storageProvider: "google-drive",
    url: "https://drive.google.com/file/d/def456",
    recipients: [
      {
        email: "accounts@supplier.com",
        name: "Material Supplier",
        status: "pending",
      },
    ],
    createdAt: "2024-01-15T08:30:00Z",
    updatedAt: "2024-01-15T10:15:00Z",
  },
];

export const mockSyncLogs: SyncLog[] = [
  {
    id: "sync-1",
    integrationId: "salesforce-1",
    timestamp: "2024-01-15T11:00:00Z",
    status: "success",
    recordsProcessed: 45,
    duration: 1200,
  },
  {
    id: "sync-2",
    integrationId: "mailchimp-1",
    timestamp: "2024-01-15T10:30:00Z",
    status: "success",
    recordsProcessed: 1200,
    duration: 3400,
  },
  {
    id: "sync-3",
    integrationId: "msg91-sms",
    timestamp: "2024-01-15T11:25:00Z",
    status: "partial",
    recordsProcessed: 180,
    errors: ["Rate limit exceeded for 3 messages"],
    duration: 890,
  },
];
