import { UnifiedNotification, NotificationAnalytics } from "./types";

export function generateMockNotifications(): UnifiedNotification[] {
  return [
    {
      id: "notif_001",
      tenantId: "tenant_001",
      type: "approval_request",
      category: "operational",
      title: "Purchase Order Approval Required",
      message:
        "PO-2024-003 from Mumbai Central Beverages requires your approval. Value: ₹75,500",
      content: {
        shortText: "PO approval needed - ₹75,500",
        fullText:
          "Purchase Order PO-2024-003 from Mumbai Central Beverages requires your approval. The order contains 15 items with a total value of ₹75,500. This order is marked as urgent and needs to be processed within 24 hours.\n\nOrder Details:\n- Supplier: Mumbai Central Beverages\n- Delivery Date: 2024-01-25\n- Payment Terms: Net 30\n- Items: 15 different beverage products\n\nPlease review the attached documents and approve or reject this order.",
      },
      status: "pending",
      priority: "high",
      senderType: "franchisee",
      senderId: "FRAN001",
      senderName: "Mumbai Central Beverages",
      recipientType: "user",
      recipients: [
        {
          id: "rec_001",
          type: "user",
          identifier: "CORP001",
          name: "Corporate Reviewer",
          status: "pending",
        },
      ],
      userTypeScope: "corporate",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: true,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: true,
      },
      channels: ["in_app", "email"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date().toISOString(),
        },
        {
          channel: "email",
          status: "sent",
          timestamp: new Date().toISOString(),
        },
      ],
      relatedEntity: {
        type: "purchase_order",
        id: "PO-2024-003",
        name: "PO-2024-003",
        url: "/corporate-po-review/pending?po=PO-2024-003",
      },
      businessContext: {
        processType: "purchase_order_workflow",
        processId: "PO-2024-003",
        stakeholders: [
          {
            userId: "CORP001",
            role: "Approver",
            responsibility: "Review and approve purchase order",
            canApprove: true,
            canReject: true,
            mustAcknowledge: false,
          },
        ],
        deadlines: [
          {
            name: "Approval Deadline",
            dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
            priority: "high",
          },
        ],
        approvals: [
          {
            id: "approval_001",
            approverIds: ["CORP001"],
            type: "individual",
            status: "pending",
            deadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
            comments: [],
          },
        ],
      },
      actions: [
        {
          id: "action_approve",
          type: "approve",
          label: "Approve",
          style: "success",
          action: {
            type: "api_call",
            target: "/api/po/approve",
            method: "POST",
            payload: { poId: "PO-2024-003" },
          },
          confirmation: {
            required: true,
            title: "Approve Purchase Order",
            message:
              "Are you sure you want to approve PO-2024-003 for ₹75,500?",
            confirmText: "Approve",
            cancelText: "Cancel",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_reject",
          type: "reject",
          label: "Reject",
          style: "danger",
          action: {
            type: "api_call",
            target: "/api/po/reject",
            method: "POST",
            payload: { poId: "PO-2024-003" },
          },
          confirmation: {
            required: true,
            title: "Reject Purchase Order",
            message: "Are you sure you want to reject PO-2024-003?",
            confirmText: "Reject",
            cancelText: "Cancel",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_view",
          type: "view_details",
          label: "View Details",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/corporate-po-review/pending?po=PO-2024-003",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      tags: ["urgent", "approval", "high-value"],
      openCount: 0,
      clickCount: 0,
    },
    {
      id: "notif_002",
      tenantId: "tenant_001",
      type: "delivery_update",
      category: "operational",
      title: "Delivery Status Update",
      message:
        "Your delivery DEL-2024-156 has been successfully delivered to Delhi North outlet",
      content: {
        shortText: "Delivery completed - DEL-2024-156",
        fullText:
          "Your delivery DEL-2024-156 containing 25 cases of beverages has been successfully delivered to Delhi North outlet. The delivery was completed at 2:30 PM today. Please verify the received items and update the GRN accordingly.",
      },
      status: "read",
      priority: "medium",
      senderType: "system",
      senderId: "SYSTEM",
      senderName: "Delivery System",
      recipientType: "user",
      recipients: [
        {
          id: "rec_002",
          type: "user",
          identifier: "FRAN002",
          name: "Delhi North Manager",
          status: "delivered",
        },
      ],
      userTypeScope: "franchisee",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: false,
      },
      channels: ["in_app", "sms"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        },
        {
          channel: "sms",
          status: "delivered",
          timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        },
      ],
      relatedEntity: {
        type: "delivery_schedule",
        id: "DEL-2024-156",
        name: "DEL-2024-156",
        url: "/delivery-logistics/track?id=DEL-2024-156",
      },
      businessContext: {
        processType: "delivery_process",
        processId: "DEL-2024-156",
        stakeholders: [
          {
            userId: "FRAN002",
            role: "Receiver",
            responsibility: "Verify delivery and update GRN",
            canApprove: false,
            canReject: false,
            mustAcknowledge: true,
          },
        ],
      },
      actions: [
        {
          id: "action_grn",
          type: "view_details",
          label: "Create GRN",
          style: "primary",
          action: {
            type: "navigate",
            target: "/delivery-logistics/grn/create?delivery=DEL-2024-156",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_track",
          type: "view_details",
          label: "Track Delivery",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/delivery-logistics/track?id=DEL-2024-156",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      readAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      tags: ["delivery", "completed", "grn-pending"],
      openCount: 1,
      clickCount: 0,
    },
    {
      id: "notif_payment_001",
      tenantId: "tenant_001",
      type: "payment_completed",
      category: "financial",
      priority: "high",
      title: "Payment Successful",
      message:
        "Payment of ₹25,000 for invoice INV-2024-001 completed successfully. Transaction ID: TXN-2024-001",
      channels: ["email", "sms", "dashboard"],
      recipients: [
        {
          type: "user",
          identifier: "FRAN001",
        },
      ],
      status: "sent",
      scheduledAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      sentAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      readAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      businessContext: {
        processType: "payment_process",
        processId: "PAY-2024-001",
        stakeholders: [
          {
            userId: "FRAN001",
            role: "Payer",
            responsibility: "Payment completed",
            canApprove: false,
            canReject: false,
            mustAcknowledge: false,
          },
        ],
      },
      metadata: {
        paymentId: "PAY-2024-001",
        transactionId: "TXN-2024-001",
        invoiceId: "INV-2024-001",
        amount: 25000,
        gateway: "razorpay",
        bankReference: "RZP123456789",
      },
      actions: [
        {
          id: "view_payment",
          type: "view_details",
          label: "View Payment",
          style: "primary",
          action: {
            type: "navigate",
            target: "/finance/payments?payment=PAY-2024-001",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "download_receipt",
          type: "download",
          label: "Download Receipt",
          style: "secondary",
          action: {
            type: "download",
            target: "/api/payments/PAY-2024-001/receipt",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      tags: ["payment", "successful", "invoice"],
      openCount: 1,
      clickCount: 1,
    },
    {
      id: "notif_payment_002",
      tenantId: "tenant_001",
      type: "late_payment_reminder",
      category: "financial",
      priority: "high",
      title: "Payment Overdue",
      message:
        "Invoice INV-2024-003 is 7 days overdue. Amount: ₹18,500. Please make payment immediately to avoid penalties.",
      channels: ["email", "sms"],
      recipients: [
        {
          type: "user",
          identifier: "FRAN001",
        },
      ],
      status: "sent",
      scheduledAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      sentAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      businessContext: {
        processType: "collection_process",
        processId: "ALERT-2024-001",
        stakeholders: [
          {
            userId: "FRAN001",
            role: "Debtor",
            responsibility: "Make overdue payment",
            canApprove: false,
            canReject: false,
            mustAcknowledge: true,
          },
        ],
      },
      metadata: {
        alertId: "ALERT-2024-001",
        invoiceId: "INV-2024-003",
        daysOverdue: 7,
        overdueAmount: 18500,
        alertLevel: 2,
      },
      actions: [
        {
          id: "pay_invoice",
          type: "payment",
          label: "Pay Now",
          style: "primary",
          action: {
            type: "navigate",
            target: "/finance/invoices?invoice=INV-2024-003&action=pay",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "view_invoice",
          type: "view_details",
          label: "View Invoice",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/finance/invoices?invoice=INV-2024-003",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      tags: ["payment", "overdue", "reminder"],
      openCount: 2,
      clickCount: 0,
    },
    {
      id: "notif_credit_001",
      tenantId: "tenant_001",
      type: "credit_limit_warning",
      category: "financial",
      priority: "medium",
      title: "Credit Limit Warning",
      message:
        "Credit utilization is at 85%. Available credit: ₹1,50,000. Consider making payments to maintain healthy credit.",
      channels: ["email", "dashboard"],
      recipients: [
        {
          type: "user",
          identifier: "FRAN001",
        },
      ],
      status: "sent",
      scheduledAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      sentAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      businessContext: {
        processType: "credit_monitoring",
        processId: "CL-001",
        stakeholders: [
          {
            userId: "FRAN001",
            role: "Credit_Holder",
            responsibility: "Monitor credit utilization",
            canApprove: false,
            canReject: false,
            mustAcknowledge: false,
          },
        ],
      },
      metadata: {
        creditLimitId: "CL-001",
        utilizationPercentage: 85,
        availableLimit: 150000,
        totalLimit: 1000000,
        warningThreshold: 80,
      },
      actions: [
        {
          id: "view_credit_status",
          type: "view_details",
          label: "View Credit Status",
          style: "primary",
          action: {
            type: "navigate",
            target: "/finance/payments/credit",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "make_payment",
          type: "payment",
          label: "Make Payment",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/finance/payments/invoices",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      tags: ["credit", "warning", "utilization"],
      openCount: 1,
      clickCount: 1,
    },
    {
      id: "notif_003",
      tenantId: "tenant_001",
      type: "grn_update",
      category: "quality",
      title: "GRN Quality Issue Detected",
      message:
        "Quality discrepancy found in GRN-2024-089. 3 items damaged during delivery.",
      content: {
        shortText: "Quality issue - GRN-2024-089",
        fullText:
          "A quality discrepancy has been identified in GRN-2024-089. During the inspection, 3 items were found to be damaged during delivery:\n\n- Product A: 2 units damaged (packaging torn)\n- Product B: 1 unit damaged (bottle cracked)\n\nTotal impact: ₹2,350\n\nPlease review and decide on the corrective action. You can either accept with deduction, reject the damaged items, or request replacement from the supplier.",
      },
      status: "pending",
      priority: "urgent",
      senderType: "system",
      senderId: "QUALITY_SYSTEM",
      senderName: "Quality Control System",
      recipientType: "user",
      recipients: [
        {
          id: "rec_003",
          type: "user",
          identifier: "FRAN002",
          name: "Delhi North Manager",
          status: "pending",
        },
      ],
      userTypeScope: "franchisee",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: false,
        canForward: true,
        canComment: true,
      },
      channels: ["in_app", "email"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        },
        {
          channel: "email",
          status: "delivered",
          timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        },
      ],
      relatedEntity: {
        type: "grn",
        id: "GRN-2024-089",
        name: "GRN-2024-089",
        url: "/delivery-logistics/grn/manage?id=GRN-2024-089",
      },
      businessContext: {
        processType: "grn_process",
        processId: "GRN-2024-089",
        stakeholders: [
          {
            userId: "FRAN002",
            role: "QC Manager",
            responsibility: "Resolve quality issues",
            canApprove: true,
            canReject: true,
            mustAcknowledge: true,
          },
        ],
        deadlines: [
          {
            name: "Resolution Deadline",
            dueDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
            priority: "urgent",
          },
        ],
      },
      actions: [
        {
          id: "action_accept_deduction",
          type: "approve",
          label: "Accept with Deduction",
          style: "warning",
          action: {
            type: "api_call",
            target: "/api/grn/accept-deduction",
            method: "POST",
            payload: { grnId: "GRN-2024-089", deduction: 2350 },
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_reject_items",
          type: "reject",
          label: "Reject Damaged Items",
          style: "danger",
          action: {
            type: "api_call",
            target: "/api/grn/reject-items",
            method: "POST",
            payload: { grnId: "GRN-2024-089", items: ["item_a", "item_b"] },
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_request_replacement",
          type: "button",
          label: "Request Replacement",
          style: "secondary",
          action: {
            type: "api_call",
            target: "/api/grn/request-replacement",
            method: "POST",
            payload: { grnId: "GRN-2024-089" },
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_view_grn",
          type: "view_details",
          label: "View GRN",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/delivery-logistics/grn/manage?id=GRN-2024-089",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [
        {
          id: "att_001",
          fileName: "damage_photos.zip",
          fileType: "application/zip",
          fileSize: 2458630,
          filePath: "/attachments/damage_photos.zip",
          description: "Photos of damaged items",
          requiresAuth: true,
          uploadedBy: "QUALITY_SYSTEM",
          uploadedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
          downloadCount: 0,
        },
      ],
      createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      tags: ["quality", "urgent", "damages", "grn"],
      openCount: 0,
      clickCount: 0,
    },
    {
      id: "notif_004",
      tenantId: "tenant_001",
      type: "system_announcement",
      category: "system",
      title: "System Maintenance Scheduled",
      message:
        "Scheduled maintenance will occur on Jan 25, 2024 from 2:00 AM to 4:00 AM IST",
      content: {
        shortText: "System maintenance - Jan 25, 2:00-4:00 AM",
        fullText:
          "We have scheduled system maintenance for January 25, 2024 from 2:00 AM to 4:00 AM IST. During this time, the system will be temporarily unavailable.\n\nWhat to expect:\n- Complete system downtime for 2 hours\n- All transactions will be queued and processed after maintenance\n- Mobile app will show maintenance mode\n- Email notifications will continue to work\n\nWe apologize for any inconvenience and appreciate your understanding.",
      },
      status: "read",
      priority: "medium",
      senderType: "admin",
      senderId: "ADMIN001",
      senderName: "System Administrator",
      recipientType: "user_type",
      recipients: [
        {
          id: "rec_004",
          type: "user_type",
          identifier: "all_users",
          name: "All Users",
          status: "sent",
        },
      ],
      userTypeScope: "both",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: false,
      },
      channels: ["in_app", "email"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
          channel: "email",
          status: "delivered",
          timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        },
      ],
      actions: [
        {
          id: "action_acknowledge",
          type: "acknowledge",
          label: "Acknowledge",
          style: "primary",
          action: {
            type: "api_call",
            target: "/api/notifications/acknowledge",
            method: "POST",
            payload: { notificationId: "notif_004" },
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      readAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      tags: ["maintenance", "system", "downtime"],
      openCount: 1,
      clickCount: 0,
    },
    {
      id: "notif_005",
      tenantId: "tenant_001",
      type: "inventory_alert",
      category: "operational",
      title: "Low Stock Alert",
      message:
        "5 products in your inventory are running low and need restocking",
      content: {
        shortText: "Low stock alert - 5 products",
        fullText:
          "The following products in your inventory are running low and require immediate attention:\n\n1. Coca Cola 500ml - Current: 45 units, Min: 100 units\n2. Pepsi 250ml - Current: 23 units, Min: 50 units\n3. Sprite 300ml - Current: 12 units, Min: 30 units\n4. Mountain Dew 500ml - Current: 8 units, Min: 25 units\n5. Fanta Orange 250ml - Current: 15 units, Min: 40 units\n\nRecommended action: Create purchase orders for these items to avoid stockouts.",
      },
      status: "acknowledged",
      priority: "high",
      senderType: "system",
      senderId: "INVENTORY_SYSTEM",
      senderName: "Inventory Management System",
      recipientType: "user",
      recipients: [
        {
          id: "rec_005",
          type: "user",
          identifier: "FRAN001",
          name: "Mumbai Central Manager",
          status: "delivered",
        },
      ],
      userTypeScope: "franchisee",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: false,
      },
      channels: ["in_app", "email"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
          channel: "email",
          status: "delivered",
          timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        },
      ],
      relatedEntity: {
        type: "inventory_item",
        id: "inventory_alert_001",
        name: "Low Stock Items",
        url: "/franchisee-inventory?filter=low_stock",
      },
      actions: [
        {
          id: "action_create_po",
          type: "button",
          label: "Create Purchase Order",
          style: "primary",
          action: {
            type: "navigate",
            target: "/franchisee-purchase-order/create?preset=low_stock",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_view_inventory",
          type: "view_details",
          label: "View Inventory",
          style: "secondary",
          action: {
            type: "navigate",
            target: "/franchisee-inventory?filter=low_stock",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      readAt: new Date(Date.now() - 5.5 * 60 * 60 * 1000).toISOString(),
      acknowledgedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      tags: ["inventory", "low-stock", "urgent"],
      openCount: 2,
      clickCount: 1,
    },
    {
      id: "notif_006",
      tenantId: "tenant_001",
      type: "order_status",
      category: "financial",
      title: "Invoice Generated",
      message:
        "Invoice INV-2024-001 has been generated for PO PO-2024-003. Amount: ₹75,500",
      content: {
        shortText: "Invoice INV-2024-001 - ₹75,500",
        fullText:
          "Invoice INV-2024-001 has been successfully generated from Purchase Order PO-2024-003.\n\nInvoice Details:\n- Amount: ₹75,500\n- Due Date: " +
          new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString() +
          "\n- GST: ₹11,580\n- Payment Terms: Net 30 days\n\nThe invoice has been sent to Mumbai Central Beverages and is now awaiting payment.",
      },
      status: "pending",
      priority: "medium",
      senderType: "system",
      senderId: "INVOICE_SYSTEM",
      senderName: "Invoice Management System",
      recipientType: "user",
      recipients: [
        {
          id: "rec_006",
          type: "user",
          identifier: "FRAN001",
          name: "Mumbai Central Beverages",
          status: "pending",
        },
      ],
      userTypeScope: "franchisee",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: false,
      },
      channels: ["in_app", "email"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
          channel: "email",
          status: "delivered",
          timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        },
      ],
      relatedEntity: {
        type: "invoice",
        id: "INV-2024-001",
        name: "INV-2024-001",
        url: "/invoice-management/franchisee/pending?invoice=INV-2024-001",
      },
      businessContext: {
        processType: "grn_process",
        processId: "INV-2024-001",
        stakeholders: [
          {
            userId: "FRAN001",
            role: "Payer",
            responsibility: "Process payment",
            canApprove: false,
            canReject: false,
            mustAcknowledge: true,
          },
        ],
        deadlines: [
          {
            name: "Payment Due Date",
            dueDate: new Date(
              Date.now() + 30 * 24 * 60 * 60 * 1000,
            ).toISOString(),
            priority: "medium",
          },
        ],
      },
      actions: [
        {
          id: "action_view_invoice",
          type: "view_details",
          label: "View Invoice",
          style: "primary",
          action: {
            type: "navigate",
            target:
              "/invoice-management/franchisee/pending?invoice=INV-2024-001",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_download_pdf",
          type: "download",
          label: "Download PDF",
          style: "secondary",
          action: {
            type: "api_call",
            target: "/api/invoices/INV-2024-001/pdf",
            method: "GET",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_make_payment",
          type: "button",
          label: "Make Payment",
          style: "success",
          action: {
            type: "navigate",
            target:
              "/invoice-management/franchisee/payment?invoice=INV-2024-001",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      tags: ["invoice", "generated", "payment-pending"],
      openCount: 0,
      clickCount: 0,
    },
    {
      id: "notif_007",
      tenantId: "tenant_001",
      type: "payment_reminder",
      category: "financial",
      title: "Payment Due in 3 Days",
      message: "Invoice INV-2024-002 payment of ₹45,200 is due in 3 days.",
      content: {
        shortText: "Payment due in 3 days - ₹45,200",
        fullText:
          "Payment Reminder for Invoice INV-2024-002\n\nAmount Due: ₹45,200\nDue Date: " +
          new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toLocaleDateString() +
          "\nDays Until Due: 3\n\nOriginal Invoice Amount: ₹45,200\nAmount Paid: ₹0\nBalance Amount: ₹45,200\n\nPlease ensure payment is processed before the due date to avoid late fees.",
      },
      status: "pending",
      priority: "high",
      senderType: "system",
      senderId: "PAYMENT_REMINDER_SYSTEM",
      senderName: "Payment Reminder System",
      recipientType: "user",
      recipients: [
        {
          id: "rec_007",
          type: "user",
          identifier: "FRAN002",
          name: "Delhi North Distributors",
          status: "pending",
        },
      ],
      userTypeScope: "franchisee",
      permissions: {
        canRead: true,
        canEdit: false,
        canDelete: false,
        canResend: false,
        canAcknowledge: true,
        canDismiss: true,
        canForward: false,
        canComment: false,
      },
      channels: ["in_app", "email", "sms"],
      deliveryStatus: [
        {
          channel: "in_app",
          status: "delivered",
          timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        },
        {
          channel: "email",
          status: "delivered",
          timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        },
      ],
      relatedEntity: {
        type: "invoice",
        id: "INV-2024-002",
        name: "INV-2024-002",
        url: "/invoice-management/franchisee/pending?invoice=INV-2024-002",
      },
      businessContext: {
        processType: "payment_process",
        processId: "INV-2024-002",
        stakeholders: [
          {
            userId: "FRAN002",
            role: "Payer",
            responsibility: "Process payment",
            canApprove: false,
            canReject: false,
            mustAcknowledge: true,
          },
        ],
        deadlines: [
          {
            name: "Payment Due Date",
            dueDate: new Date(
              Date.now() + 3 * 24 * 60 * 60 * 1000,
            ).toISOString(),
            priority: "high",
          },
        ],
      },
      actions: [
        {
          id: "action_make_payment",
          type: "button",
          label: "Make Payment",
          style: "success",
          action: {
            type: "navigate",
            target:
              "/invoice-management/franchisee/payment?invoice=INV-2024-002",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_view_invoice",
          type: "view_details",
          label: "View Invoice",
          style: "secondary",
          action: {
            type: "navigate",
            target:
              "/invoice-management/franchisee/pending?invoice=INV-2024-002",
          },
          visible: true,
          enabled: true,
        },
        {
          id: "action_contact_support",
          type: "button",
          label: "Contact Support",
          style: "secondary",
          action: {
            type: "external_link",
            target: "mailto:support@buildpro.com",
          },
          visible: true,
          enabled: true,
        },
      ],
      attachments: [],
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      tags: ["payment", "due", "reminder", "high"],
      openCount: 0,
      clickCount: 0,
    },
  ];
}

export function generateMockAnalytics(): NotificationAnalytics {
  return {
    totalNotifications: 1456,
    totalSent: 1398,
    totalDelivered: 1356,
    totalRead: 1142,
    totalClicked: 856,
    totalAcknowledged: 723,
    deliveryRate: 97.0,
    readRate: 84.2,
    clickRate: 75.0,
    acknowledgmentRate: 63.3,
    responseRate: 68.5,
    engagementScore: 82.4,
    averageResponseTime: 45.6,
    averageDeliveryTime: 1.8,
    peakEngagementHours: [9, 10, 14, 15, 16],
    channelMetrics: [
      {
        channel: "in_app",
        sent: 1398,
        delivered: 1356,
        read: 1142,
        clicked: 856,
        deliveryRate: 97.0,
        readRate: 84.2,
        clickRate: 75.0,
        averageDeliveryTime: 0.5,
        cost: 0,
        revenue: 0,
      },
      {
        channel: "email",
        sent: 892,
        delivered: 847,
        read: 623,
        clicked: 445,
        deliveryRate: 94.9,
        readRate: 73.5,
        clickRate: 71.4,
        averageDeliveryTime: 2.3,
        cost: 178.4,
        revenue: 2340,
      },
      {
        channel: "sms",
        sent: 234,
        delivered: 228,
        read: 215,
        clicked: 89,
        deliveryRate: 97.4,
        readRate: 94.3,
        clickRate: 41.4,
        averageDeliveryTime: 1.2,
        cost: 468,
        revenue: 890,
      },
    ],
    channelPreferences: [
      { channel: "in_app", userCount: 1456, percentage: 100 },
      { channel: "email", userCount: 1205, percentage: 82.7 },
      { channel: "sms", userCount: 456, percentage: 31.3 },
      { channel: "push", userCount: 892, percentage: 61.3 },
    ],
    categoryMetrics: [
      {
        category: "operational",
        sent: 756,
        engagementRate: 78.5,
        conversionRate: 45.2,
        averageResponseTime: 32.4,
      },
      {
        category: "financial",
        sent: 234,
        engagementRate: 89.3,
        conversionRate: 67.8,
        averageResponseTime: 18.7,
      },
      {
        category: "quality",
        sent: 189,
        engagementRate: 92.1,
        conversionRate: 78.9,
        averageResponseTime: 15.2,
      },
      {
        category: "system",
        sent: 145,
        engagementRate: 56.7,
        conversionRate: 23.4,
        averageResponseTime: 89.3,
      },
    ],
    userEngagement: [
      {
        userId: "CORP001",
        sentCount: 89,
        readCount: 82,
        clickCount: 67,
        engagementScore: 85.4,
        averageResponseTime: 25.6,
        preferredChannel: "email",
        activeHours: [9, 10, 11, 14, 15, 16],
      },
      {
        userId: "FRAN001",
        sentCount: 156,
        readCount: 145,
        clickCount: 123,
        engagementScore: 91.2,
        averageResponseTime: 18.3,
        preferredChannel: "in_app",
        activeHours: [8, 9, 10, 13, 14, 15, 16, 17],
      },
    ],
    userPreferences: [
      {
        userId: "CORP001",
        channels: ["email", "in_app"],
        frequency: "immediate",
        categories: ["operational", "financial", "quality"],
        quietHours: { enabled: true, start: "20:00", end: "08:00" },
      },
    ],
    templatePerformance: [
      {
        templateId: "template_001",
        name: "PO Approval Request",
        sent: 245,
        openRate: 87.3,
        clickRate: 67.8,
        conversionRate: 45.2,
        revenue: 125000,
        cost: 49,
        engagementScore: 78.4,
        lastUsed: "2024-01-22T09:15:00Z",
      },
      {
        templateId: "template_002",
        name: "Delivery Status Update",
        sent: 1567,
        openRate: 94.8,
        clickRate: 23.4,
        conversionRate: 12.1,
        revenue: 0,
        cost: 313.4,
        engagementScore: 45.2,
        lastUsed: "2024-01-22T11:30:00Z",
      },
    ],
    workflowMetrics: [
      {
        workflowId: "workflow_001",
        name: "PO Approval Notification",
        executions: 45,
        successRate: 97.8,
        averageExecutionTime: 1250,
        notificationsSent: 89,
        engagementRate: 78.9,
        conversionRate: 67.4,
        lastRun: "2024-01-22T09:15:00Z",
      },
    ],
    businessMetrics: {
      revenueGenerated: 250000,
      revenuePerNotification: 171.7,
      conversionValue: 45.2,
      customerAcquisition: 23,
      customerRetention: 89.5,
      customerSatisfaction: 4.2,
      processEfficiency: 78.9,
      responseTimeImprovement: 34.5,
      automationSavings: 12500,
      errorReduction: 23.4,
      complianceScore: 92.1,
      riskMitigation: 67.8,
    },
    timeSeriesData: {
      hourlyData: generateHourlyData(),
      dailyData: generateDailyData(),
      weeklyData: generateWeeklyData(),
      monthlyData: generateMonthlyData(),
    },
    comparativeMetrics: {
      previousPeriod: {
        current: {
          period: "Jan 2024",
          sent: 1398,
          engagementRate: 82.4,
          conversionRate: 45.2,
          revenue: 250000,
          userCount: 1456,
        },
        previous: {
          period: "Dec 2023",
          sent: 1256,
          engagementRate: 78.9,
          conversionRate: 42.1,
          revenue: 220000,
          userCount: 1398,
        },
        change: 142,
        changePercentage: 11.3,
        trend: "up",
      },
      yearOverYear: {
        current: {
          period: "Jan 2024",
          sent: 1398,
          engagementRate: 82.4,
          conversionRate: 45.2,
          revenue: 250000,
          userCount: 1456,
        },
        previous: {
          period: "Jan 2023",
          sent: 892,
          engagementRate: 67.8,
          conversionRate: 34.5,
          revenue: 145000,
          userCount: 1123,
        },
        change: 506,
        changePercentage: 56.7,
        trend: "up",
      },
      internalBenchmarks: {
        deliveryRate: 98.5,
        readRate: 85.7,
        clickRate: 72.3,
        engagementRate: 80.1,
        responseTime: 42.0,
        source: "Industry Standard",
        lastUpdated: "2024-01-15T00:00:00Z",
      },
      cohortAnalysis: [
        {
          cohort: "New Users (0-30 days)",
          userCount: 123,
          engagementRate: 89.3,
          conversionRate: 56.7,
          retentionRate: 78.9,
        },
        {
          cohort: "Regular Users (31-90 days)",
          userCount: 456,
          engagementRate: 82.1,
          conversionRate: 45.8,
          retentionRate: 91.2,
        },
        {
          cohort: "Power Users (90+ days)",
          userCount: 877,
          engagementRate: 78.4,
          conversionRate: 41.3,
          retentionRate: 95.6,
        },
      ],
    },
    predictions: {
      engagementForecast: [
        { date: "2024-01-23", predicted: 84.2, confidence: 0.89 },
        { date: "2024-01-24", predicted: 83.8, confidence: 0.87 },
        { date: "2024-01-25", predicted: 82.1, confidence: 0.85 },
      ],
      optimalSendTimes: [
        { hour: 9, score: 0.92, userType: "corporate" },
        { hour: 14, score: 0.89, userType: "corporate" },
        { hour: 10, score: 0.95, userType: "franchisee" },
        { hour: 15, score: 0.91, userType: "franchisee" },
      ],
      churnPrediction: [
        { userId: "USER123", churnProbability: 0.78, riskLevel: "high" },
        { userId: "USER456", churnProbability: 0.34, riskLevel: "low" },
      ],
      engagementPrediction: [
        { userId: "USER123", predictedEngagement: 0.67, trend: "decreasing" },
        { userId: "USER456", predictedEngagement: 0.89, trend: "increasing" },
      ],
      channelPerformanceForecast: [
        { channel: "email", predictedPerformance: 0.82, confidence: 0.91 },
        { channel: "sms", predictedPerformance: 0.76, confidence: 0.87 },
      ],
      templatePerformancePrediction: [
        {
          templateId: "template_001",
          predictedEngagement: 0.85,
          confidence: 0.93,
        },
      ],
      revenueImpactForecast: [
        { date: "2024-01-23", predictedRevenue: 12500, confidence: 0.88 },
        { date: "2024-01-24", predictedRevenue: 13200, confidence: 0.86 },
      ],
      modelAccuracy: 0.89,
      lastTrainingDate: "2024-01-20T00:00:00Z",
      dataQualityScore: 0.94,
    },
  };
}

function generateHourlyData() {
  return Array.from({ length: 24 }, (_, hour) => ({
    hour,
    sent: Math.floor(Math.random() * 100) + 20,
    delivered: Math.floor(Math.random() * 95) + 18,
    read: Math.floor(Math.random() * 80) + 15,
    clicked: Math.floor(Math.random() * 60) + 10,
  }));
}

function generateDailyData() {
  return Array.from({ length: 30 }, (_, day) => ({
    date: new Date(2024, 0, day + 1).toISOString().split("T")[0],
    sent: Math.floor(Math.random() * 200) + 50,
    delivered: Math.floor(Math.random() * 190) + 45,
    read: Math.floor(Math.random() * 160) + 40,
    clicked: Math.floor(Math.random() * 120) + 30,
  }));
}

function generateWeeklyData() {
  return Array.from({ length: 12 }, (_, week) => ({
    week: `Week ${week + 1}`,
    sent: Math.floor(Math.random() * 1000) + 500,
    delivered: Math.floor(Math.random() * 950) + 475,
    read: Math.floor(Math.random() * 800) + 400,
    clicked: Math.floor(Math.random() * 600) + 300,
  }));
}

function generateMonthlyData() {
  return Array.from({ length: 12 }, (_, month) => ({
    month: new Date(2023, month).toLocaleString("default", { month: "long" }),
    sent: Math.floor(Math.random() * 5000) + 2000,
    delivered: Math.floor(Math.random() * 4800) + 1900,
    read: Math.floor(Math.random() * 4000) + 1600,
    clicked: Math.floor(Math.random() * 3000) + 1200,
  }));
}
