// Unified Financial Management Data - Consolidating Finance + Accounting + Payment Gateway

import {
  FinancialTenant,
  ChartOfAccount,
  FinancialTransaction,
  Invoice,
  Budget,
  PaymentTransaction,
  FinancialAnalytics,
  FinancialConfiguration,
  PaymentGatewayConfig,
  BankConnectionConfig,
  TaxSystemConfig,
  Currency,
  AccountType,
  TransactionStatus,
  PaymentGateway,
  PaymentMethod,
  PaymentStatus,
} from "./types";

// Available Financial Tenants
export const getFinancialTenants = (): FinancialTenant[] => [
  {
    id: "tenant_buildcorp",
    name: "BuildCorp Constructions",
    legalName: "BuildCorp Constructions Private Limited",
    industryType: "construction",
    baseCurrency: "INR",
    fiscalYearStart: "04-01", // April 1st
    configuration: {
      id: "config_buildcorp",
      tenantId: "tenant_buildcorp",
      companyName: "BuildCorp Constructions",
      legalName: "BuildCorp Constructions Private Limited",
      industryType: "construction",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 4, // April
      fiscalYearEnd: 3, // March
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "construction_standard",
      accountCodeFormat: "####",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
        budgets: true,
      },
      workflows: {
        transactionApproval: true,
        budgetApproval: true,
        paymentApproval: true,
        invoiceApproval: true,
      },
      integrations: {
        paymentGateways: [
          {
            id: "pg_razorpay_001",
            gatewayName: "razorpay",
            isActive: true,
            credentials: {
              merchantId: "buildcorp_rzp",
              apiKey: "rzp_test_1234567890",
              secretKey: "secret_key_placeholder",
              webhookSecret: "webhook_secret_placeholder",
              environment: "production",
            },
            supportedMethods: [
              "credit_card",
              "debit_card",
              "net_banking",
              "upi",
              "wallet",
            ],
            transactionFees: [
              { method: "credit_card", feeType: "percentage", feeValue: 2.0 },
              { method: "debit_card", feeType: "percentage", feeValue: 1.5 },
              { method: "net_banking", feeType: "percentage", feeValue: 1.0 },
              { method: "upi", feeType: "percentage", feeValue: 0.5 },
            ],
            settingsConfiguration: {
              autoCapture: true,
              webhookEnabled: true,
              refundEnabled: true,
            },
          },
        ],
        bankConnections: [
          {
            id: "bank_hdfc_001",
            bankName: "HDFC Bank",
            connectionType: "api",
            isActive: true,
            credentials: {
              clientId: "hdfc_client_id",
              clientSecret: "hdfc_client_secret",
              environment: "production",
            },
            accountMappings: [
              {
                bankAccountNumber: "50100123456789",
                chartOfAccountId: "acc_bc_003",
                accountName: "HDFC Bank - Current Account",
                isActive: true,
              },
            ],
          },
        ],
        taxSystems: [
          {
            id: "tax_gst_001",
            taxSystemName: "GST India",
            isActive: true,
            taxRates: [
              {
                id: "gst_5",
                taxName: "GST 5%",
                rate: 5,
                applicableFrom: "2024-01-01",
                isActive: true,
              },
              {
                id: "gst_12",
                taxName: "GST 12%",
                rate: 12,
                applicableFrom: "2024-01-01",
                isActive: true,
              },
              {
                id: "gst_18",
                taxName: "GST 18%",
                rate: 18,
                applicableFrom: "2024-01-01",
                isActive: true,
              },
              {
                id: "gst_28",
                taxName: "GST 28%",
                rate: 28,
                applicableFrom: "2024-01-01",
                isActive: true,
              },
            ],
            complianceSettings: {
              gstEnabled: true,
              tdsEnabled: true,
              autoCalculation: true,
              complianceReporting: true,
            },
          },
        ],
      },
    },
  },
  {
    id: "tenant_metro_realty",
    name: "Metro Realty Group",
    legalName: "Metro Realty Group Private Limited",
    industryType: "real_estate",
    baseCurrency: "INR",
    fiscalYearStart: "04-01",
    configuration: {
      id: "config_metro",
      tenantId: "tenant_metro_realty",
      companyName: "Metro Realty Group",
      legalName: "Metro Realty Group Private Limited",
      industryType: "real_estate",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 4,
      fiscalYearEnd: 3,
      currentFiscalYear: "2023-24",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "real_estate_standard",
      accountCodeFormat: "####",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
        budgets: true,
      },
      workflows: {
        transactionApproval: true,
        budgetApproval: true,
        paymentApproval: true,
        invoiceApproval: true,
      },
      integrations: {
        paymentGateways: [
          {
            id: "pg_payu_001",
            gatewayName: "payu",
            isActive: true,
            credentials: {
              merchantId: "metro_payu",
              apiKey: "payu_test_1234567890",
              secretKey: "payu_secret_placeholder",
              webhookSecret: "payu_webhook_placeholder",
              environment: "production",
            },
            supportedMethods: [
              "credit_card",
              "debit_card",
              "net_banking",
              "upi",
            ],
            transactionFees: [
              { method: "credit_card", feeType: "percentage", feeValue: 2.3 },
              { method: "debit_card", feeType: "percentage", feeValue: 1.8 },
            ],
            settingsConfiguration: {
              autoCapture: true,
              webhookEnabled: true,
            },
          },
        ],
        bankConnections: [],
        taxSystems: [],
      },
    },
  },
  {
    id: "tenant_skyline_dev",
    name: "Skyline Developers",
    legalName: "Skyline Developers Limited",
    industryType: "real_estate",
    baseCurrency: "INR",
    fiscalYearStart: "01-01",
    configuration: {
      id: "config_skyline",
      tenantId: "tenant_skyline_dev",
      companyName: "Skyline Developers",
      legalName: "Skyline Developers Limited",
      industryType: "real_estate",
      baseCurrency: "INR",
      functionalCurrency: "INR",
      reportingCurrency: "INR",
      fiscalYearStart: 1,
      fiscalYearEnd: 12,
      currentFiscalYear: "2024",
      accountingStandard: "ind_as",
      chartOfAccountsTemplate: "real_estate_standard",
      accountCodeFormat: "####",
      autoNumbering: {
        journalEntries: true,
        invoices: true,
        receipts: true,
        payments: true,
        budgets: true,
      },
      workflows: {
        transactionApproval: true,
        budgetApproval: true,
        paymentApproval: true,
        invoiceApproval: true,
      },
      integrations: {
        paymentGateways: [],
        bankConnections: [],
        taxSystems: [],
      },
    },
  },
];

// Chart of Accounts for different tenants
export const getChartOfAccountsByTenant = (
  tenantId: string,
): ChartOfAccount[] => {
  const baseAccounts: ChartOfAccount[] = [
    // Assets
    {
      id: `acc_${tenantId.split("_")[1]}_001`,
      tenantId,
      accountCode: "1000",
      accountName: "Current Assets",
      accountType: "assets",
      level: 1,
      isActive: true,
      currentBalance: 25000000,
      openingBalance: 22000000,
      currency: "INR",
      allowDirectPosting: false,
      isBankAccount: false,
      isCashAccount: false,
      isControlAccount: true,
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
    {
      id: `acc_${tenantId.split("_")[1]}_002`,
      tenantId,
      accountCode: "1100",
      accountName: "Cash and Bank",
      accountType: "assets",
      parentAccountId: `acc_${tenantId.split("_")[1]}_001`,
      level: 2,
      isActive: true,
      currentBalance: 8500000,
      openingBalance: 7200000,
      currency: "INR",
      allowDirectPosting: false,
      isBankAccount: false,
      isCashAccount: false,
      isControlAccount: true,
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
    {
      id: `acc_${tenantId.split("_")[1]}_003`,
      tenantId,
      accountCode: "1101",
      accountName: "HDFC Bank - Current Account",
      accountType: "assets",
      parentAccountId: `acc_${tenantId.split("_")[1]}_002`,
      level: 3,
      isActive: true,
      currentBalance: 5500000,
      openingBalance: 4800000,
      currency: "INR",
      allowDirectPosting: true,
      isBankAccount: true,
      isCashAccount: false,
      isControlAccount: false,
      bankDetails: {
        bankName: "HDFC Bank",
        accountNumber: "50100123456789",
        ifscCode: "HDFC0001234",
        accountType: "current",
      },
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
    // Liabilities
    {
      id: `acc_${tenantId.split("_")[1]}_010`,
      tenantId,
      accountCode: "2000",
      accountName: "Current Liabilities",
      accountType: "liabilities",
      level: 1,
      isActive: true,
      currentBalance: 8500000,
      openingBalance: 7800000,
      currency: "INR",
      allowDirectPosting: false,
      isBankAccount: false,
      isCashAccount: false,
      isControlAccount: true,
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
    // Revenue
    {
      id: `acc_${tenantId.split("_")[1]}_020`,
      tenantId,
      accountCode: "4000",
      accountName: "Revenue",
      accountType: "revenue",
      level: 1,
      isActive: true,
      currentBalance: 45000000,
      openingBalance: 42000000,
      currency: "INR",
      allowDirectPosting: false,
      isBankAccount: false,
      isCashAccount: false,
      isControlAccount: true,
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
    // Expenses
    {
      id: `acc_${tenantId.split("_")[1]}_030`,
      tenantId,
      accountCode: "5000",
      accountName: "Expenses",
      accountType: "expenses",
      level: 1,
      isActive: true,
      currentBalance: 35000000,
      openingBalance: 32000000,
      currency: "INR",
      allowDirectPosting: false,
      isBankAccount: false,
      isCashAccount: false,
      isControlAccount: true,
      createdBy: "system",
      createdAt: "2024-01-01T00:00:00Z",
    },
  ];

  return baseAccounts;
};

// Financial Transactions
export const getFinancialTransactionsByTenant = (
  tenantId: string,
): FinancialTransaction[] => [
  {
    id: `txn_${tenantId.split("_")[1]}_001`,
    tenantId,
    transactionNumber: "TXN-2024-0001",
    date: "2024-01-15T10:30:00Z",
    type: "invoice",
    reference: "INV-2024-0001",
    description: "Project Phase 1 Invoice - ABC Tower",
    totalAmount: 2500000,
    currency: "INR",
    journalEntries: [
      {
        id: "je_001",
        accountId: `acc_${tenantId.split("_")[1]}_001`,
        accountCode: "1200",
        accountName: "Accounts Receivable",
        debitAmount: 2500000,
        creditAmount: 0,
        description: "Invoice raised for ABC Tower Project",
      },
      {
        id: "je_002",
        accountId: `acc_${tenantId.split("_")[1]}_020`,
        accountCode: "4100",
        accountName: "Construction Revenue",
        debitAmount: 0,
        creditAmount: 2500000,
        description: "Revenue recognition for ABC Tower Project",
      },
    ],
    attachments: [],
    status: "approved",
    approvalLevel: 2,
    approvedBy: "user_finance_manager",
    approvedAt: "2024-01-15T14:30:00Z",
    sourceModule: "manual",
    createdBy: "user_accountant",
    createdAt: "2024-01-15T10:30:00Z",
  },
  {
    id: `txn_${tenantId.split("_")[1]}_002`,
    tenantId,
    transactionNumber: "TXN-2024-0002",
    date: "2024-01-16T09:15:00Z",
    type: "payment",
    reference: "PAY-2024-0001",
    description: "Payment received - ABC Tower Invoice",
    totalAmount: 1000000,
    currency: "INR",
    journalEntries: [
      {
        id: "je_003",
        accountId: `acc_${tenantId.split("_")[1]}_003`,
        accountCode: "1101",
        accountName: "HDFC Bank - Current Account",
        debitAmount: 1000000,
        creditAmount: 0,
        description: "Payment received via NEFT",
      },
      {
        id: "je_004",
        accountId: `acc_${tenantId.split("_")[1]}_001`,
        accountCode: "1200",
        accountName: "Accounts Receivable",
        debitAmount: 0,
        creditAmount: 1000000,
        description: "Payment against ABC Tower Invoice",
      },
    ],
    attachments: [],
    status: "approved",
    approvalLevel: 1,
    approvedBy: "user_accountant",
    approvedAt: "2024-01-16T09:30:00Z",
    sourceModule: "payment_gateway",
    sourceReference: "pay_razorpay_123456",
    createdBy: "system",
    createdAt: "2024-01-16T09:15:00Z",
  },
];

// Invoices
export const getInvoicesByTenant = (tenantId: string): Invoice[] => [
  {
    id: `inv_${tenantId.split("_")[1]}_001`,
    tenantId,
    invoiceNumber: "INV-2024-0001",
    invoiceDate: "2024-01-15",
    dueDate: "2024-02-14",
    customerId: "cust_001",
    customerName: "ABC Infrastructure Ltd",
    customerAddress: {
      street: "123 Business Park",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      zipCode: "400001",
    },
    companyDetails: {
      name: "BuildCorp Constructions",
      legalName: "BuildCorp Constructions Private Limited",
      address: {
        street: "456 Corporate Plaza",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        zipCode: "400002",
      },
      phone: "+91-22-12345678",
      email: "finance@buildcorp.com",
      taxId: "27AABCU9603R1ZX",
    },
    lineItems: [
      {
        id: "line_001",
        description: "Construction Work - Phase 1",
        quantity: 1,
        rate: 2000000,
        amount: 2000000,
        taxRate: 18,
        taxAmount: 360000,
        discountPercentage: 0,
        discountAmount: 0,
        lineTotal: 2360000,
      },
      {
        id: "line_002",
        description: "Material Supply",
        quantity: 1,
        rate: 500000,
        amount: 500000,
        taxRate: 18,
        taxAmount: 90000,
        discountPercentage: 5,
        discountAmount: 25000,
        lineTotal: 565000,
      },
    ],
    subtotal: 2500000,
    taxAmount: 450000,
    discountAmount: 25000,
    grandTotal: 2925000,
    paidAmount: 1000000,
    balanceAmount: 1925000,
    currency: "INR",
    status: "partially_paid",
    paymentTerms: 30,
    notes: "Payment terms: 30 days from invoice date",
    termsAndConditions: "Standard terms and conditions apply",
    createdBy: "user_accountant",
    createdAt: "2024-01-15T10:30:00Z",
    attachments: [],
    paymentHistory: [
      {
        id: "pay_001",
        paymentDate: "2024-01-16",
        amount: 1000000,
        paymentMethod: "bank_transfer",
        gateway: "razorpay",
        transactionId: "pay_razorpay_123456",
        status: "success",
        reference: "NEFT12345678",
        createdBy: "system",
      },
    ],
  },
];

// Budgets
export const getBudgetsByTenant = (tenantId: string): Budget[] => [
  {
    id: `bud_${tenantId.split("_")[1]}_001`,
    tenantId,
    budgetName: "Annual Budget 2024",
    fiscalYear: "2024",
    startDate: "2024-01-01",
    endDate: "2024-12-31",
    totalBudget: 100000000,
    allocatedAmount: 85000000,
    spentAmount: 25000000,
    remainingAmount: 60000000,
    currency: "INR",
    status: "active",
    budgetItems: [
      {
        id: "bitem_001",
        accountId: `acc_${tenantId.split("_")[1]}_030`,
        accountName: "Operating Expenses",
        budgetedAmount: 30000000,
        allocatedAmount: 25000000,
        spentAmount: 8000000,
        remainingAmount: 17000000,
        varianceAmount: -3000000,
        variancePercentage: -10,
        quarter1Budget: 7500000,
        quarter2Budget: 7500000,
        quarter3Budget: 7500000,
        quarter4Budget: 7500000,
      },
      {
        id: "bitem_002",
        accountId: `acc_${tenantId.split("_")[1]}_030`,
        accountName: "Material Costs",
        budgetedAmount: 40000000,
        allocatedAmount: 35000000,
        spentAmount: 12000000,
        remainingAmount: 23000000,
        varianceAmount: 5000000,
        variancePercentage: 12.5,
        quarter1Budget: 10000000,
        quarter2Budget: 10000000,
        quarter3Budget: 10000000,
        quarter4Budget: 10000000,
      },
    ],
    approvalWorkflow: {
      currentLevel: 3,
      maxLevel: 3,
      approvers: [
        {
          level: 1,
          userId: "user_accountant",
          userName: "John Accountant",
          status: "approved",
          approvedAt: "2024-01-01T10:00:00Z",
        },
        {
          level: 2,
          userId: "user_finance_manager",
          userName: "Jane Manager",
          status: "approved",
          approvedAt: "2024-01-01T14:00:00Z",
        },
        {
          level: 3,
          userId: "user_director",
          userName: "Robert Director",
          status: "approved",
          approvedAt: "2024-01-02T09:00:00Z",
        },
      ],
      status: "approved",
    },
    createdBy: "user_finance_manager",
    createdAt: "2024-01-01T09:00:00Z",
  },
];

// Payment Transactions
export const getPaymentTransactionsByTenant = (
  tenantId: string,
): PaymentTransaction[] => [
  {
    id: `paytxn_${tenantId.split("_")[1]}_001`,
    tenantId,
    transactionId: "TXN_20240116_001",
    gatewayTransactionId: "pay_razorpay_123456",
    invoiceId: `inv_${tenantId.split("_")[1]}_001`,
    customerId: "cust_001",
    amount: 1000000,
    currency: "INR",
    paymentMethod: "bank_transfer",
    gateway: "razorpay",
    status: "success",
    gatewayResponse: {
      status: "success",
      message: "Payment processed successfully",
      gatewayTransactionId: "pay_razorpay_123456",
      additionalData: {
        bankReferenceNumber: "NEFT12345678",
        paymentMode: "NEFT",
      },
    },
    merchantReference: "INV-2024-0001",
    customerReference: "Customer Payment for ABC Tower",
    paymentDate: "2024-01-16T09:15:00Z",
    settlementDate: "2024-01-17T09:00:00Z",
    fees: {
      gatewayFee: 10000,
      gst: 1800,
      totalDeduction: 11800,
      netAmount: 988200,
    },
    metadata: {
      customerIp: "192.168.1.100",
      userAgent: "Mozilla/5.0...",
      invoiceNumber: "INV-2024-0001",
    },
    createdAt: "2024-01-16T09:15:00Z",
    updatedAt: "2024-01-16T09:16:00Z",
  },
];

// Financial Analytics
export const getFinancialAnalyticsByTenant = (
  tenantId: string,
  timeRange: string = "current_month",
): FinancialAnalytics => {
  // Mock analytics data - in real app, this would be calculated from actual data
  return {
    tenantId,
    period: timeRange,
    kpis: {
      totalRevenue: 45000000,
      totalExpenses: 35000000,
      netProfit: 10000000,
      grossMargin: 22.2,
      operatingMargin: 18.5,
      totalAssets: 150000000,
      totalLiabilities: 85000000,
      totalEquity: 65000000,
      cashPosition: 25000000,
      accountsReceivable: 15000000,
      accountsPayable: 8500000,
      outstandingInvoices: 12,
      overdueInvoices: 3,
    },
    ratios: {
      currentRatio: 2.94,
      quickRatio: 2.1,
      debtToEquityRatio: 1.31,
      returnOnAssets: 6.67,
      returnOnEquity: 15.38,
      grossProfitMargin: 22.2,
      netProfitMargin: 18.5,
      assetTurnoverRatio: 0.36,
      receivablesTurnover: 3.6,
      payablesTurnover: 4.8,
    },
    trends: {
      revenueGrowth: 12.5,
      expenseGrowth: 8.3,
      profitGrowth: 18.2,
      cashFlowTrend: 15.7,
      monthlyComparisons: [
        {
          month: "Jan",
          revenue: 4500000,
          expenses: 3500000,
          profit: 1000000,
          cashFlow: 750000,
        },
        {
          month: "Feb",
          revenue: 4200000,
          expenses: 3300000,
          profit: 900000,
          cashFlow: 680000,
        },
        {
          month: "Mar",
          revenue: 4800000,
          expenses: 3600000,
          profit: 1200000,
          cashFlow: 820000,
        },
      ],
    },
    cashFlowAnalysis: {
      operatingCashFlow: 12000000,
      investingCashFlow: -3000000,
      financingCashFlow: -2000000,
      netCashFlow: 7000000,
      cashFlowProjection: [
        {
          month: "Apr",
          projectedInflow: 5000000,
          projectedOutflow: 3800000,
          netCashFlow: 1200000,
          cumulativeCashFlow: 26200000,
        },
        {
          month: "May",
          projectedInflow: 4800000,
          projectedOutflow: 3600000,
          netCashFlow: 1200000,
          cumulativeCashFlow: 27400000,
        },
        {
          month: "Jun",
          projectedInflow: 5200000,
          projectedOutflow: 3900000,
          netCashFlow: 1300000,
          cumulativeCashFlow: 28700000,
        },
      ],
    },
    profitLossAnalysis: {
      totalRevenue: 45000000,
      costOfGoodsSold: 28000000,
      grossProfit: 17000000,
      operatingExpenses: 8500000,
      operatingIncome: 8500000,
      otherIncome: 500000,
      otherExpenses: 200000,
      netIncome: 8800000,
      categoryBreakdown: [
        {
          category: "Construction Revenue",
          amount: 35000000,
          percentage: 77.8,
          trend: 15.2,
        },
        {
          category: "Material Sales",
          amount: 8000000,
          percentage: 17.8,
          trend: 8.5,
        },
        {
          category: "Consulting",
          amount: 2000000,
          percentage: 4.4,
          trend: 22.1,
        },
      ],
    },
    balanceSheetAnalysis: {
      totalAssets: 150000000,
      currentAssets: 45000000,
      nonCurrentAssets: 105000000,
      totalLiabilities: 85000000,
      currentLiabilities: 25000000,
      nonCurrentLiabilities: 60000000,
      totalEquity: 65000000,
      retainedEarnings: 35000000,
      assetBreakdown: [
        { category: "Current Assets", amount: 45000000, percentage: 30 },
        { category: "Fixed Assets", amount: 80000000, percentage: 53.3 },
        { category: "Investments", amount: 25000000, percentage: 16.7 },
      ],
      liabilityBreakdown: [
        { category: "Current Liabilities", amount: 25000000, percentage: 29.4 },
        { category: "Long-term Debt", amount: 45000000, percentage: 52.9 },
        { category: "Other Liabilities", amount: 15000000, percentage: 17.6 },
      ],
    },
  };
};

// Unified Financial Summary
export const getUnifiedFinancialSummary = (tenantId: string) => {
  const transactions = getFinancialTransactionsByTenant(tenantId);
  const invoices = getInvoicesByTenant(tenantId);
  const payments = getPaymentTransactionsByTenant(tenantId);

  return {
    tenantId,
    summary: {
      totalTransactions: transactions.length,
      totalInvoices: invoices.length,
      totalPayments: payments.length,
      pendingApprovals: transactions.filter((t) => t.status === "pending")
        .length,
    },
    recentTransactions: [
      ...transactions.map((t) => ({
        id: t.id,
        type: t.type,
        description: t.description,
        amount: t.totalAmount,
        currency: t.currency,
        date: t.date,
        status: t.status,
        reference: t.reference,
        module: "finance",
      })),
      ...payments.map((p) => ({
        id: p.id,
        type: "payment" as const,
        description: `Payment via ${p.gateway}`,
        amount: p.amount,
        currency: p.currency,
        date: p.paymentDate,
        status: p.status,
        reference: p.gatewayTransactionId,
        module: "payments",
      })),
    ].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
  };
};

// Helper functions for currency formatting
export const formatCurrency = (
  amount: number,
  currency: Currency = "INR",
): string => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const formatPercentage = (value: number): string => {
  return new Intl.NumberFormat("en-IN", {
    style: "percent",
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  }).format(value / 100);
};
