import {
  SalesPerformanceMetrics,
  SalesAnalyticsDashboard,
  FranchiseePerformance,
  RegionalPerformance,
  TopSellingProduct,
  ProductMarginAnalysis,
  PerformanceAlert,
  SalesTarget,
  PerformanceComparison,
  SalesForecast,
} from "./types";

// Generate comprehensive sales performance metrics
export function generateSalesPerformanceMetrics(
  tenantId: string,
  userType: string,
): SalesPerformanceMetrics {
  return {
    tenantId,
    period: "2024-01",
    userType: userType as any,

    revenue: {
      total: 15650000,
      growth: 18.5,
      target: 14000000,
      achievement: 111.8,
      monthlyRevenue: [
        {
          month: "Oct",
          year: 2023,
          revenue: 12800000,
          orders: 1250,
          growth: 12.3,
          target: 12000000,
          achievement: 106.7,
        },
        {
          month: "Nov",
          year: 2023,
          revenue: 13200000,
          orders: 1320,
          growth: 15.8,
          target: 12500000,
          achievement: 105.6,
        },
        {
          month: "Dec",
          year: 2023,
          revenue: 14800000,
          orders: 1480,
          growth: 22.1,
          target: 13000000,
          achievement: 113.8,
        },
        {
          month: "Jan",
          year: 2024,
          revenue: 15650000,
          orders: 1565,
          growth: 18.5,
          target: 14000000,
          achievement: 111.8,
        },
      ],
      revenueByChannel: [
        {
          channel: "retail",
          revenue: 8500000,
          percentage: 54.3,
          growth: 15.2,
          orders: 850,
        },
        {
          channel: "wholesale",
          revenue: 4200000,
          percentage: 26.8,
          growth: 22.5,
          orders: 420,
        },
        {
          channel: "online",
          revenue: 2100000,
          percentage: 13.4,
          growth: 35.8,
          orders: 210,
        },
        {
          channel: "b2b",
          revenue: 850000,
          percentage: 5.4,
          growth: 8.9,
          orders: 85,
        },
      ],
    },

    sales: {
      totalOrders: 1565,
      orderGrowth: 12.8,
      averageOrderValue: 10000,
      conversionRate: 68.5,
      totalCustomers: 2847,
      newCustomers: 285,
      customerRetention: 78.9,
    },

    regional: [
      {
        regionId: "REG-001",
        regionName: "North India",
        state: "Delhi",
        city: "New Delhi",
        franchiseeCount: 25,
        totalRevenue: 5850000,
        growth: 22.5,
        target: 5200000,
        achievement: 112.5,
        averageRevenuePerFranchisee: 234000,
        topFranchisee: { name: "Delhi Central Franchise", revenue: 485000 },
        marketPenetration: 65.8,
      },
      {
        regionId: "REG-002",
        regionName: "West India",
        state: "Maharashtra",
        city: "Mumbai",
        franchiseeCount: 32,
        totalRevenue: 4920000,
        growth: 18.9,
        target: 4500000,
        achievement: 109.3,
        averageRevenuePerFranchisee: 153750,
        topFranchisee: { name: "Mumbai West Franchise", revenue: 425000 },
        marketPenetration: 72.3,
      },
      {
        regionId: "REG-003",
        regionName: "South India",
        state: "Karnataka",
        city: "Bangalore",
        franchiseeCount: 28,
        totalRevenue: 3680000,
        growth: 15.6,
        target: 3200000,
        achievement: 115.0,
        averageRevenuePerFranchisee: 131429,
        topFranchisee: { name: "Bangalore Tech Franchise", revenue: 380000 },
        marketPenetration: 58.9,
      },
      {
        regionId: "REG-004",
        regionName: "East India",
        state: "West Bengal",
        city: "Kolkata",
        franchiseeCount: 18,
        totalRevenue: 1200000,
        growth: 8.5,
        target: 1100000,
        achievement: 109.1,
        averageRevenuePerFranchisee: 66667,
        topFranchisee: { name: "Kolkata Central Franchise", revenue: 185000 },
        marketPenetration: 42.1,
      },
    ],

    products: {
      topSelling: [
        {
          productId: "PROD-001",
          productCode: "CEM-OPC-50",
          productName: "OPC Cement 50kg",
          category: "Cement",
          brand: "UltraTech",
          quantitySold: 125000,
          revenue: 4375000,
          growth: 28.5,
          margin: 875000,
          marginPercentage: 20.0,
          salesRank: 1,
          previousRank: 1,
          customers: 485,
          avgOrderQuantity: 250,
        },
        {
          productId: "PROD-002",
          productCode: "STL-REB-12",
          productName: "Steel Rebar 12mm",
          category: "Steel",
          brand: "Tata Steel",
          quantitySold: 85000,
          revenue: 3825000,
          growth: 22.1,
          margin: 688500,
          marginPercentage: 18.0,
          salesRank: 2,
          previousRank: 3,
          customers: 312,
          avgOrderQuantity: 150,
        },
        {
          productId: "PROD-003",
          productCode: "BRK-RED-STD",
          productName: "Red Bricks Standard",
          category: "Bricks",
          quantitySold: 450000,
          revenue: 2250000,
          growth: 15.8,
          margin: 450000,
          marginPercentage: 20.0,
          salesRank: 3,
          previousRank: 2,
          customers: 625,
          avgOrderQuantity: 1000,
        },
      ],
      slowMoving: [
        {
          productId: "PROD-015",
          productCode: "MAR-EXP-WH",
          productName: "Expensive White Marble",
          category: "Marble",
          currentStock: 250,
          daysSinceLastSale: 45,
          lastSaleDate: "2023-12-15",
          stockValue: 1250000,
          recommendedAction: "discount",
          potentialLoss: 125000,
        },
        {
          productId: "PROD-018",
          productCode: "TIL-LUX-CER",
          productName: "Luxury Ceramic Tiles",
          category: "Tiles",
          currentStock: 180,
          daysSinceLastSale: 62,
          lastSaleDate: "2023-11-28",
          stockValue: 720000,
          recommendedAction: "bundle",
          potentialLoss: 72000,
        },
      ],
      marginAnalysis: [
        {
          productId: "PROD-001",
          productCode: "CEM-OPC-50",
          productName: "OPC Cement 50kg",
          category: "Cement",
          sellingPrice: 350,
          costPrice: 280,
          margin: 70,
          marginPercentage: 20.0,
          volume: 125000,
          totalMargin: 8750000,
          benchmarkMargin: 65,
          marginTrend: "improving",
          recommendation: "Maintain current pricing strategy",
        },
        {
          productId: "PROD-002",
          productCode: "STL-REB-12",
          productName: "Steel Rebar 12mm",
          category: "Steel",
          sellingPrice: 45,
          costPrice: 36.9,
          margin: 8.1,
          marginPercentage: 18.0,
          volume: 85000,
          totalMargin: 688500,
          benchmarkMargin: 9.0,
          marginTrend: "declining",
          recommendation: "Review supplier contracts for better pricing",
        },
      ],
    },

    franchisees: generateFranchiseePerformance(tenantId, userType),

    alerts: [
      {
        id: "ALERT-001",
        type: "low_performance",
        severity: "high",
        title: "Low Performance Alert",
        description: "East Region franchisees showing 15% decline in sales",
        regionId: "REG-004",
        regionName: "East India",
        value: -15,
        threshold: -10,
        trend: "declining",
        actionRequired: "Regional manager intervention needed",
        status: "open",
        createdAt: "2024-01-28T09:00:00Z",
        impact: "revenue",
        priority: 1,
      },
      {
        id: "ALERT-002",
        type: "missed_target",
        severity: "medium",
        title: "Target Missed",
        description: "Kolkata Central Franchise missed Q4 target by 25%",
        franchiseeId: "FRAN-018",
        franchiseeName: "Kolkata Central Franchise",
        value: 75,
        threshold: 100,
        trend: "declining",
        actionRequired: "Performance improvement plan required",
        status: "acknowledged",
        createdAt: "2024-01-25T14:30:00Z",
        impact: "revenue",
        priority: 2,
      },
      {
        id: "ALERT-003",
        type: "inventory_issue",
        severity: "critical",
        title: "Slow Moving Inventory",
        description: "High-value marble inventory not moving for 45+ days",
        productId: "PROD-015",
        productName: "Expensive White Marble",
        value: 1250000,
        threshold: 1000000,
        trend: "stable",
        actionRequired: "Immediate discount or promotional campaign",
        status: "in_progress",
        createdAt: "2024-01-20T11:15:00Z",
        impact: "operational",
        priority: 1,
      },
    ],
  };
}

// Generate franchisee performance data
export function generateFranchiseePerformance(
  tenantId: string,
  userType: string,
): FranchiseePerformance[] {
  const baseData: Omit<
    FranchiseePerformance,
    "franchiseeId" | "franchiseeName" | "rank"
  >[] = [
    {
      regionId: "REG-001",
      regionName: "North India",
      state: "Delhi",
      city: "New Delhi",
      revenue: 485000,
      revenueGrowth: 25.8,
      revenueTarget: 450000,
      revenueAchievement: 107.8,
      totalOrders: 485,
      orderGrowth: 18.5,
      averageOrderValue: 1000,
      totalCustomers: 125,
      newCustomers: 25,
      customerRetention: 82.5,
      topProducts: ["OPC Cement 50kg", "Steel Rebar 12mm", "Red Bricks"],
      categoriesSold: 12,
      performanceRating: "excellent",
      totalFranchisees: 103,
      inventoryTurnover: 8.5,
      paymentDelays: 2,
      complianceScore: 95,
      monthlyPerformance: [
        {
          month: "Oct",
          revenue: 420000,
          orders: 420,
          customers: 105,
          achievement: 105.0,
        },
        {
          month: "Nov",
          revenue: 445000,
          orders: 445,
          customers: 115,
          achievement: 108.5,
        },
        {
          month: "Dec",
          revenue: 465000,
          orders: 465,
          customers: 120,
          achievement: 106.8,
        },
        {
          month: "Jan",
          revenue: 485000,
          orders: 485,
          customers: 125,
          achievement: 107.8,
        },
      ],
      hasLowPerformanceAlert: false,
      alertCount: 0,
    },
    {
      regionId: "REG-002",
      regionName: "West India",
      state: "Maharashtra",
      city: "Mumbai",
      revenue: 425000,
      revenueGrowth: 22.1,
      revenueTarget: 400000,
      revenueAchievement: 106.3,
      totalOrders: 425,
      orderGrowth: 15.8,
      averageOrderValue: 1000,
      totalCustomers: 98,
      newCustomers: 18,
      customerRetention: 78.9,
      topProducts: ["Steel Rebar 12mm", "OPC Cement 50kg", "Tiles"],
      categoriesSold: 10,
      performanceRating: "excellent",
      totalFranchisees: 103,
      inventoryTurnover: 7.8,
      paymentDelays: 1,
      complianceScore: 92,
      monthlyPerformance: [
        {
          month: "Oct",
          revenue: 385000,
          orders: 385,
          customers: 88,
          achievement: 102.5,
        },
        {
          month: "Nov",
          revenue: 405000,
          orders: 405,
          customers: 92,
          achievement: 105.2,
        },
        {
          month: "Dec",
          revenue: 415000,
          orders: 415,
          customers: 95,
          achievement: 104.8,
        },
        {
          month: "Jan",
          revenue: 425000,
          orders: 425,
          customers: 98,
          achievement: 106.3,
        },
      ],
      hasLowPerformanceAlert: false,
      alertCount: 0,
    },
    {
      regionId: "REG-003",
      regionName: "South India",
      state: "Karnataka",
      city: "Bangalore",
      revenue: 380000,
      revenueGrowth: 18.5,
      revenueTarget: 350000,
      revenueAchievement: 108.6,
      totalOrders: 380,
      orderGrowth: 12.8,
      averageOrderValue: 1000,
      totalCustomers: 85,
      newCustomers: 15,
      customerRetention: 85.2,
      topProducts: ["OPC Cement 50kg", "Steel Rebar 12mm", "Granite"],
      categoriesSold: 11,
      performanceRating: "good",
      totalFranchisees: 103,
      inventoryTurnover: 6.9,
      paymentDelays: 3,
      complianceScore: 88,
      monthlyPerformance: [
        {
          month: "Oct",
          revenue: 340000,
          orders: 340,
          customers: 75,
          achievement: 105.2,
        },
        {
          month: "Nov",
          revenue: 360000,
          orders: 360,
          customers: 80,
          achievement: 107.8,
        },
        {
          month: "Dec",
          revenue: 370000,
          orders: 370,
          customers: 82,
          achievement: 106.5,
        },
        {
          month: "Jan",
          revenue: 380000,
          orders: 380,
          customers: 85,
          achievement: 108.6,
        },
      ],
      hasLowPerformanceAlert: false,
      alertCount: 1,
    },
    {
      regionId: "REG-004",
      regionName: "East India",
      state: "West Bengal",
      city: "Kolkata",
      revenue: 185000,
      revenueGrowth: -8.5,
      revenueTarget: 250000,
      revenueAchievement: 74.0,
      totalOrders: 185,
      orderGrowth: -12.8,
      averageOrderValue: 1000,
      totalCustomers: 45,
      newCustomers: 5,
      customerRetention: 65.8,
      topProducts: ["Red Bricks", "OPC Cement 50kg", "Steel"],
      categoriesSold: 8,
      performanceRating: "poor",
      totalFranchisees: 103,
      inventoryTurnover: 4.2,
      paymentDelays: 12,
      complianceScore: 68,
      monthlyPerformance: [
        {
          month: "Oct",
          revenue: 205000,
          orders: 205,
          customers: 52,
          achievement: 82.0,
        },
        {
          month: "Nov",
          revenue: 195000,
          orders: 195,
          customers: 48,
          achievement: 78.0,
        },
        {
          month: "Dec",
          revenue: 190000,
          orders: 190,
          customers: 46,
          achievement: 76.0,
        },
        {
          month: "Jan",
          revenue: 185000,
          orders: 185,
          customers: 45,
          achievement: 74.0,
        },
      ],
      hasLowPerformanceAlert: true,
      alertCount: 3,
    },
    {
      regionId: "REG-002",
      regionName: "West India",
      state: "Gujarat",
      city: "Ahmedabad",
      revenue: 298000,
      revenueGrowth: 15.2,
      revenueTarget: 280000,
      revenueAchievement: 106.4,
      totalOrders: 298,
      orderGrowth: 8.9,
      averageOrderValue: 1000,
      totalCustomers: 68,
      newCustomers: 12,
      customerRetention: 75.2,
      topProducts: ["OPC Cement 50kg", "Tiles", "Pipes"],
      categoriesSold: 9,
      performanceRating: "good",
      totalFranchisees: 103,
      inventoryTurnover: 5.8,
      paymentDelays: 5,
      complianceScore: 85,
      monthlyPerformance: [
        {
          month: "Oct",
          revenue: 275000,
          orders: 275,
          customers: 62,
          achievement: 103.5,
        },
        {
          month: "Nov",
          revenue: 285000,
          orders: 285,
          customers: 65,
          achievement: 105.2,
        },
        {
          month: "Dec",
          revenue: 292000,
          orders: 292,
          customers: 67,
          achievement: 105.8,
        },
        {
          month: "Jan",
          revenue: 298000,
          orders: 298,
          customers: 68,
          achievement: 106.4,
        },
      ],
      hasLowPerformanceAlert: false,
      alertCount: 0,
    },
  ];

  return baseData.map((data, index) => ({
    ...data,
    franchiseeId: `FRAN-${String(index + 1).padStart(3, "0")}`,
    franchiseeName: `${data.city} ${index % 2 === 0 ? "Central" : "Premium"} Franchise`,
    rank: index + 1,
  }));
}

// Generate sales analytics dashboard
export function generateSalesAnalyticsDashboard(
  tenantId: string,
  userType: string,
): SalesAnalyticsDashboard {
  const metrics = generateSalesPerformanceMetrics(tenantId, userType);

  return {
    tenantId,
    userType,
    period: "2024-01",
    lastUpdated: new Date().toISOString(),

    kpis: {
      totalRevenue: {
        value: 15650000,
        target: 14000000,
        achievement: 111.8,
        growth: 18.5,
        trend: "up",
        status: "excellent",
        unit: "currency",
      },
      revenueGrowth: {
        value: 18.5,
        growth: 2.8,
        trend: "up",
        status: "excellent",
        unit: "percentage",
      },
      totalOrders: {
        value: 1565,
        target: 1400,
        achievement: 111.8,
        growth: 12.8,
        trend: "up",
        status: "good",
        unit: "number",
      },
      averageOrderValue: {
        value: 10000,
        target: 9500,
        achievement: 105.3,
        growth: 5.3,
        trend: "up",
        status: "good",
        unit: "currency",
      },
      customerCount: {
        value: 2847,
        growth: 15.8,
        trend: "up",
        status: "excellent",
        unit: "number",
      },
      conversionRate: {
        value: 68.5,
        target: 65.0,
        achievement: 105.4,
        growth: 3.8,
        trend: "up",
        status: "good",
        unit: "percentage",
      },
      franchiseeCount: {
        value: 103,
        growth: 8.5,
        trend: "up",
        status: "good",
        unit: "number",
      },
      regionCount: {
        value: 4,
        growth: 0,
        trend: "stable",
        status: "good",
        unit: "number",
      },
    },

    charts: {
      revenueChart: {
        type: "line",
        title: "Monthly Revenue Trend",
        data: [
          { label: "Oct 2023", value: 12800000, growth: 12.3 },
          { label: "Nov 2023", value: 13200000, growth: 15.8 },
          { label: "Dec 2023", value: 14800000, growth: 22.1 },
          { label: "Jan 2024", value: 15650000, growth: 18.5 },
        ],
        xAxis: "Month",
        yAxis: "Revenue (INR)",
      },
      salesChart: {
        type: "bar",
        title: "Orders by Channel",
        data: [
          { label: "Retail", value: 850, percentage: 54.3, color: "#3b82f6" },
          {
            label: "Wholesale",
            value: 420,
            percentage: 26.8,
            color: "#10b981",
          },
          { label: "Online", value: 210, percentage: 13.4, color: "#f59e0b" },
          { label: "B2B", value: 85, percentage: 5.4, color: "#ef4444" },
        ],
      },
      regionalChart: {
        type: "pie",
        title: "Revenue by Region",
        data: [
          {
            label: "North India",
            value: 5850000,
            percentage: 37.4,
            color: "#3b82f6",
          },
          {
            label: "West India",
            value: 4920000,
            percentage: 31.4,
            color: "#10b981",
          },
          {
            label: "South India",
            value: 3680000,
            percentage: 23.5,
            color: "#f59e0b",
          },
          {
            label: "East India",
            value: 1200000,
            percentage: 7.7,
            color: "#ef4444",
          },
        ],
      },
      productChart: {
        type: "bar",
        title: "Top Selling Products",
        data: [
          { label: "OPC Cement 50kg", value: 4375000, category: "Cement" },
          { label: "Steel Rebar 12mm", value: 3825000, category: "Steel" },
          { label: "Red Bricks Standard", value: 2250000, category: "Bricks" },
        ],
      },
      franchiseeChart: {
        type: "bar",
        title: "Top Performing Franchisees",
        data: [
          { label: "Delhi Central", value: 485000, growth: 25.8 },
          { label: "Mumbai West", value: 425000, growth: 22.1 },
          { label: "Bangalore Tech", value: 380000, growth: 18.5 },
          { label: "Ahmedabad Premium", value: 298000, growth: 15.2 },
        ],
      },
      marginChart: {
        type: "area",
        title: "Margin Analysis by Category",
        data: [
          { label: "Cement", value: 20.0, category: "High Volume" },
          { label: "Steel", value: 18.0, category: "Medium Volume" },
          { label: "Bricks", value: 20.0, category: "High Volume" },
          { label: "Tiles", value: 25.0, category: "Low Volume" },
        ],
      },
    },

    tables: {
      topRegions: metrics.regional,
      topFranchisees: metrics.franchisees.slice(0, 5),
      topProducts: metrics.products.topSelling,
      lowPerformers: metrics.franchisees.filter(
        (f) =>
          f.performanceRating === "poor" || f.performanceRating === "critical",
      ),
    },
  };
}

// Generate sales targets
export function generateSalesTargets(tenantId: string): SalesTarget[] {
  return [
    {
      id: "TARGET-001",
      tenantId,
      targetType: "revenue",
      level: "corporate",
      entityId: "CORP-001",
      entityName: "Corporate",
      period: "yearly",
      startDate: "2024-01-01",
      endDate: "2024-12-31",
      target: 168000000,
      achieved: 15650000,
      achievement: 9.3,
      status: "on_track",
      breakdown: [
        {
          month: "Jan",
          target: 14000000,
          achieved: 15650000,
          achievement: 111.8,
        },
        { month: "Feb", target: 14000000, achieved: 0, achievement: 0 },
        { month: "Mar", target: 14000000, achieved: 0, achievement: 0 },
      ],
      createdBy: "admin-001",
      createdAt: "2023-12-01T00:00:00Z",
      lastUpdatedAt: "2024-01-31T23:59:59Z",
    },
    {
      id: "TARGET-002",
      tenantId,
      targetType: "revenue",
      level: "regional",
      entityId: "REG-001",
      entityName: "North India",
      period: "monthly",
      startDate: "2024-01-01",
      endDate: "2024-01-31",
      target: 5200000,
      achieved: 5850000,
      achievement: 112.5,
      status: "exceeded",
      breakdown: [
        {
          month: "Jan",
          target: 5200000,
          achieved: 5850000,
          achievement: 112.5,
        },
      ],
      createdBy: "regional-manager-001",
      createdAt: "2023-12-15T00:00:00Z",
      lastUpdatedAt: "2024-01-31T23:59:59Z",
    },
  ];
}

// Generate performance comparison
export function generatePerformanceComparison(
  tenantId: string,
  entityId: string,
): PerformanceComparison {
  return {
    entity: "franchisee",
    entityId,
    entityName: "Delhi Central Franchise",

    current: {
      revenue: 485000,
      growth: 25.8,
      orders: 485,
      customers: 125,
      margin: 20.5,
      efficiency: 8.5,
    },
    previous: {
      revenue: 385000,
      growth: 15.2,
      orders: 385,
      customers: 105,
      margin: 18.2,
      efficiency: 7.2,
    },
    benchmark: {
      revenue: 350000,
      growth: 18.0,
      orders: 350,
      customers: 95,
      margin: 19.0,
      efficiency: 7.8,
    },
    industry: {
      revenue: 320000,
      growth: 15.5,
      orders: 320,
      customers: 85,
      margin: 17.5,
      efficiency: 7.0,
    },

    ranking: {
      current: 1,
      previous: 3,
      total: 103,
      improvement: 2,
    },

    strengths: [
      "Excellent revenue growth of 25.8%",
      "High customer retention at 82.5%",
      "Strong inventory turnover of 8.5x",
      "Consistent margin improvement",
    ],
    weaknesses: [
      "Limited to 12 product categories",
      "Dependency on local market conditions",
      "Need to improve online channel presence",
    ],
    recommendations: [
      "Expand product portfolio to include premium categories",
      "Invest in digital marketing for online channel growth",
      "Implement customer loyalty programs",
      "Focus on bulk order acquisition strategies",
    ],
  };
}

// Generate sales forecast
export function generateSalesForecast(
  tenantId: string,
  entityId: string,
): SalesForecast {
  return {
    entityType: "franchisee",
    entityId,
    entityName: "Delhi Central Franchise",

    forecastPeriod: "next_quarter",
    forecastDate: "2024-02-01T00:00:00Z",

    predictions: {
      revenue: {
        value: 1520000,
        confidence: 85,
        range: { min: 1350000, max: 1680000 },
        factors: [
          "Seasonal demand increase",
          "New product launches",
          "Market expansion",
        ],
      },
      orders: {
        value: 1520,
        confidence: 82,
        range: { min: 1350, max: 1680 },
        factors: [
          "Historical growth pattern",
          "Customer acquisition rate",
          "Market trends",
        ],
      },
      customers: {
        value: 165,
        confidence: 78,
        range: { min: 150, max: 180 },
        factors: [
          "Referral programs",
          "Marketing campaigns",
          "Competitive landscape",
        ],
      },
    },

    assumptions: [
      "No major economic disruptions",
      "Continued supply chain stability",
      "Maintenance of current pricing strategy",
      "No new major competitors in territory",
    ],
    confidence: 82,
    methodology: "trend_analysis",

    scenarios: {
      optimistic: {
        value: 1680000,
        confidence: 70,
        range: { min: 1580000, max: 1780000 },
        factors: [
          "Strong market growth",
          "Successful promotions",
          "Economic upturn",
        ],
      },
      realistic: {
        value: 1520000,
        confidence: 85,
        range: { min: 1420000, max: 1620000 },
        factors: [
          "Normal market conditions",
          "Steady growth trajectory",
          "Consistent performance",
        ],
      },
      pessimistic: {
        value: 1350000,
        confidence: 75,
        range: { min: 1250000, max: 1450000 },
        factors: [
          "Market downturn",
          "Increased competition",
          "Supply chain issues",
        ],
      },
    },
  };
}
